/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\\models\\maxtower_02_1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/maxtower_02_1.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.025}>
        <group position={[0, 126, 0]}>
          <group position={[4, 77.777, -4.108]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.instance_0.geometry} material={materials['noon_3.001']} position={[-1.491, 0, -11.828]} />
            <mesh geometry={nodes.instance_0001.geometry} material={materials['noon_3.001']} position={[-1.491, 0, -11.828]} />
            <mesh geometry={nodes.instance_0002.geometry} material={materials['noon_3.001']} position={[-1.491, 0, -11.828]} />
            <mesh geometry={nodes.instance_0003.geometry} material={materials['noon_3.001']} position={[-1.491, 0, -11.828]} />
            <mesh geometry={nodes.instance_0004.geometry} material={materials['noon_3.001']} position={[-1.491, 0, -11.828]} />
            <mesh geometry={nodes.instance_1.geometry} material={materials['noon_3.001']} position={[0.213, 2, -0.085]} />
            <mesh geometry={nodes.instance_1001.geometry} material={materials['noon_3.001']} position={[0.213, 2, -0.085]} />
            <mesh geometry={nodes.instance_1002.geometry} material={materials['noon_3.001']} position={[0.213, 2, -0.085]} />
            <mesh geometry={nodes.instance_1003.geometry} material={materials['noon_3.001']} position={[0.213, 2, -0.085]} />
            <mesh geometry={nodes.instance_1004.geometry} material={materials['noon_3.001']} position={[0.213, 2, -0.085]} />
            <mesh geometry={nodes.instance_1005.geometry} material={materials['noon_3.001']} position={[0.213, 2, -0.085]} />
            <mesh geometry={nodes.instance_1006.geometry} material={materials['noon_3.001']} position={[0.213, 2, -0.085]} />
            <mesh geometry={nodes.instance_1007.geometry} material={materials['noon_3.001']} position={[0.213, 2, -0.085]} />
            <mesh geometry={nodes.instance_1008.geometry} material={materials['noon_3.001']} position={[0.213, 2, -0.085]} />
          </group>
          <mesh geometry={nodes.group_1.geometry} material={materials['noon1.001']} />
        </group>
        <group position={[26.625, 105.9, -12]} scale={1.34}>
          <group position={[0, 36, 0]}>
            <group position={[2, 1.625, -2]}>
              <group position={[4.56, 0.125, -4.205]}>
                <mesh geometry={nodes.group_31.geometry} material={materials['Color_F06.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_31001.geometry} material={materials['Color_F06.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_31002.geometry} material={materials['Color_F06.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_32.geometry} material={materials['Color_D07.001']} position={[0.417, 0, -0.417]} />
              </group>
              <group position={[3.802, 0.125, -0.743]}>
                <mesh geometry={nodes.group_37.geometry} material={materials['Color_F07.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_37001.geometry} material={materials['Color_F07.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_37002.geometry} material={materials['Color_F07.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_38.geometry} material={materials['Color_D08.001']} position={[0.417, 0, -0.417]} />
              </group>
              <group position={[1.685, 0.125, -4.393]}>
                <mesh geometry={nodes.group_40.geometry} material={materials['Color_F07.001']} position={[-0.139, 0.749, 0.139]} scale={[1.29, 1.793, 1.29]} />
                <mesh geometry={nodes.group_40001.geometry} material={materials['Color_F07.001']} position={[-0.139, 0.749, 0.139]} scale={[1.29, 1.793, 1.29]} />
                <mesh geometry={nodes.group_40002.geometry} material={materials['Color_F07.001']} position={[-0.139, 0.749, 0.139]} scale={[1.29, 1.793, 1.29]} />
                <mesh geometry={nodes.group_41.geometry} material={materials['Color_D07.001']} position={[0.417, 0, -0.417]} />
              </group>
              <group position={[4.123, 0.125, -2.955]}>
                <mesh geometry={nodes.group_43.geometry} material={materials['Color_F08.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_43001.geometry} material={materials['Color_F08.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_43002.geometry} material={materials['Color_F08.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_43003.geometry} material={materials['Color_F08.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_44.geometry} material={materials['Color_D08.001']} position={[0.417, 0, -0.417]} />
              </group>
              <mesh geometry={nodes.group_33.geometry} material={materials['Color_M01.001']} position={[0.25, 0, -5.081]} rotation={[-Math.PI, 0, -Math.PI]} />
              <group position={[0, 0, -6.5]} rotation={[0, -1.571, 0]}>
                <mesh geometry={nodes.ID451.geometry} material={materials['Color_M01.001']} />
                <mesh geometry={nodes.ID451_1.geometry} material={materials['Color_M00.001']} />
                <mesh geometry={nodes.group_35.geometry} material={materials['Color_M01.001']} />
                <mesh geometry={nodes.group_35001.geometry} material={materials['Color_M01.001']} />
              </group>
              <mesh geometry={nodes.group_34001.geometry} material={materials['Color_M01.001']} position={[0, 0, -6.5]} rotation={[0, -1.571, 0]} />
              <group position={[0, 0, -6.5]} rotation={[0, -1.571, 0]}>
                <mesh geometry={nodes.ID465.geometry} material={materials['Color_M01.001']} />
                <mesh geometry={nodes.ID465_1.geometry} material={materials['Color_I03.001']} />
              </group>
              <group position={[0, 0, -6.5]} rotation={[0, -1.571, 0]}>
                <mesh geometry={nodes.ID473.geometry} material={materials['Color_M01.001']} />
                <mesh geometry={nodes.ID473_1.geometry} material={materials['Color_D07.001']} />
              </group>
              <group position={[0, 0, -6.5]} rotation={[0, -1.571, 0]}>
                <mesh geometry={nodes.ID479.geometry} material={materials['Color_F06.001']} />
                <mesh geometry={nodes.ID479_1.geometry} material={materials['Color_M01.001']} />
              </group>
            </group>
            <mesh geometry={nodes.group_11.geometry} material={materials['material.001']} />
            <mesh geometry={nodes.group_11001.geometry} material={materials['material.001']} />
            <mesh geometry={nodes.group_11002.geometry} material={materials['material.001']} />
            <mesh geometry={nodes.group_12.geometry} material={materials['Color_M01.001']} position={[2, 1.625, -16]} rotation={[0, -1.571, 0]}>
              <mesh geometry={nodes.group_13.geometry} material={materials['Color_I01.001']} position={[1, 0, -1]} />
              <mesh geometry={nodes.group_13001.geometry} material={materials['Color_I01.001']} position={[1, 0, -1]} />
              <mesh geometry={nodes.group_13002.geometry} material={materials['Color_I01.001']} position={[1, 0, -1]} />
              <mesh geometry={nodes.group_14.geometry} material={materials['Color_K01.001']} position={[3.75, 0, -4]} />
              <mesh geometry={nodes.group_14001.geometry} material={materials['Color_K01.001']} position={[3.75, 0, -4]} />
              <mesh geometry={nodes.group_15.geometry} material={materials['Color_B01.001']} position={[0.75, 0, -3.875]} />
              <mesh geometry={nodes.group_15001.geometry} material={materials['Color_B01.001']} position={[0.75, 0, -3.875]} />
              <mesh geometry={nodes.group_16.geometry} material={materials['Color_F01.001']} position={[3.75, 0, -1]} />
              <mesh geometry={nodes.group_16001.geometry} material={materials['Color_F01.001']} position={[3.75, 0, -1]} />
              <mesh geometry={nodes.group_17.geometry} material={materials['material.001']} position={[2.309, 2.125, -2.618]} rotation={[0, -1.571, 0]} />
              <mesh geometry={nodes.group_18.geometry} material={materials['material.001']} position={[6.188, 0, -6.25]} rotation={[0, -1.571, 0]} />
              <mesh geometry={nodes.group_19.geometry} material={materials['material.001']} position={[0.313, 0, -7.875]} rotation={[0, 1.571, 0]} />
              <mesh geometry={nodes.group_20.geometry} material={materials['material.001']} position={[6.313, 0, -13.375]} rotation={[0, 1.571, 0]} />
            </mesh>
            <mesh geometry={nodes.group_12001.geometry} material={materials['material.001']} position={[2, 1.625, -16]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.group_21.geometry} material={materials['Color_M01.001']} position={[9.5, 1.625, -2]}>
              <mesh geometry={nodes.group_22.geometry} material={materials['material.001']} position={[0.375, 0, -6.125]} />
              <mesh geometry={nodes.group_23.geometry} material={materials['material.001']} position={[0.375, 0, -0.25]} />
              <mesh geometry={nodes.group_24.geometry} material={materials['Color_H01.001']} position={[0.75, 0, -5.5]} rotation={[0, -1.571, 0]} />
              <mesh geometry={nodes.group_24001.geometry} material={materials['Color_H01.001']} position={[0.75, 0, -5.5]} rotation={[0, -1.571, 0]} />
              <mesh geometry={nodes.group_24002.geometry} material={materials['Color_H01.001']} position={[0.75, 0, -5.5]} rotation={[0, -1.571, 0]} />
              <mesh geometry={nodes.group_25.geometry} material={materials['Color_A01.001']} position={[3.75, 0, -2.75]} rotation={[0, -1.571, 0]} />
              <mesh geometry={nodes.group_25001.geometry} material={materials['Color_A01.001']} position={[3.75, 0, -2.75]} rotation={[0, -1.571, 0]} />
              <mesh geometry={nodes.group_26.geometry} material={materials['Color_E02.001']} position={[3.625, 0, -5.75]} rotation={[0, -1.571, 0]} />
              <mesh geometry={nodes.group_26001.geometry} material={materials['Color_E02.001']} position={[3.625, 0, -5.75]} rotation={[0, -1.571, 0]} />
              <mesh geometry={nodes.group_27.geometry} material={materials['Color_G02.001']} position={[0.75, 0, -2.75]} rotation={[0, -1.571, 0]} />
              <mesh geometry={nodes.group_27001.geometry} material={materials['Color_G02.001']} position={[0.75, 0, -2.75]} rotation={[0, -1.571, 0]} />
              <mesh geometry={nodes.group_28.geometry} material={materials['material.001']} position={[6.125, 0, -0.25]} />
            </mesh>
            <mesh geometry={nodes.group_21001.geometry} material={materials['material.001']} position={[9.5, 1.625, -2]} />
            <mesh geometry={nodes.group_6.geometry} material={materials['material.001']} position={[10.672, 3.75, -6.209]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.group_7.geometry} material={materials['Color_I01.001']} position={[10, 1.625, -15.25]} rotation={[0, -1.571, 0]}>
              <mesh geometry={nodes.group_10.geometry} material={materials['Color_I01.001']} position={[0.375, 3.188, -1.5]} rotation={[0, 1.571, 0]} />
              <mesh geometry={nodes.group_8.geometry} material={materials['Color_I01.001']} position={[0.375, 2.188, -1.5]} rotation={[0, 1.571, 0]} />
              <group position={[0.375, 2.188, -1.5]} rotation={[0, 1.571, 0]}>
                <mesh geometry={nodes.ID132.geometry} material={materials['Color_I01.001']} />
                <mesh geometry={nodes.ID132_1.geometry} material={materials['Color_M07.001']} />
              </group>
              <mesh geometry={nodes.group_9.geometry} material={materials['Color_I01.001']} position={[0.375, 3.188, -3.376]} rotation={[0, 1.571, 0]} />
            </mesh>
            <mesh geometry={nodes.group_7001.geometry} material={materials['Color_I01.001']} position={[10, 1.625, -15.25]} rotation={[0, -1.571, 0]} />
            <group position={[10, 1.625, -15.25]} rotation={[0, -1.571, 0]}>
              <mesh geometry={nodes.ID166.geometry} material={materials['Color_I01.001']} />
              <mesh geometry={nodes.ID166_1.geometry} material={materials['Color_F06.001']} />
            </group>
          </group>
          <mesh geometry={nodes.group_4.geometry} material={materials['material.001']} />
        </group>
        <group position={[33.689, 105.9, -69.255]} rotation={[0, -Math.PI / 4, 0]} scale={1.34}>
          <group position={[0, 36, 0]}>
            <mesh geometry={nodes.group_47.geometry} material={materials['material.001']} position={[8.996, 1.625, -13.647]} />
            <mesh geometry={nodes.group_47001.geometry} material={materials['material.001']} position={[8.996, 1.625, -13.647]} />
            <mesh geometry={nodes.group_48.geometry} material={materials['material.001']} position={[13.434, 2.125, -3.274]}>
              <mesh geometry={nodes.group_49.geometry} material={materials['material.001']} position={[0.563, 0.625, 0.125]} />
            </mesh>
            <mesh geometry={nodes.group_48001.geometry} material={materials['material.001']} position={[13.434, 2.125, -3.274]} />
            <mesh geometry={nodes.group_48002.geometry} material={materials['material.001']} position={[13.434, 2.125, -3.274]} />
            <mesh geometry={nodes.group_50.geometry} material={materials['material.001']} position={[9.371, 2.125, -14.022]}>
              <mesh geometry={nodes.group_49001.geometry} material={materials['material.001']} position={[0.563, 0.625, 0.125]} />
            </mesh>
            <mesh geometry={nodes.group_50001.geometry} material={materials['material.001']} position={[9.371, 2.125, -14.022]} />
            <mesh geometry={nodes.group_50002.geometry} material={materials['material.001']} position={[9.371, 2.125, -14.022]} />
            <mesh geometry={nodes.group_69.geometry} material={materials['material.001']} position={[13.059, 1.625, -2.899]} />
            <mesh geometry={nodes.group_69001.geometry} material={materials['material.001']} position={[13.059, 1.625, -2.899]} />
            <group position={[15.034, 1.625, -7.367]} scale={0.746}>
              <mesh geometry={nodes.ID913001.geometry} material={materials['Color_F01.001']} />
              <mesh geometry={nodes.ID913001_1.geometry} material={materials['Color_M01.001']} />
            </group>
            <group position={[15.034, 1.625, -7.367]} scale={0.746}>
              <mesh geometry={nodes.ID919.geometry} material={materials['Color_F01.001']} />
              <mesh geometry={nodes.ID919_1.geometry} material={materials['Color_M01.001']} />
            </group>
            <mesh geometry={nodes.group_70002.geometry} material={materials['Color_F01.001']} position={[15.034, 1.625, -7.367]} scale={0.746} />
            <group position={[15.034, 1.625, -7.367]} scale={0.746}>
              <mesh geometry={nodes.ID931.geometry} material={materials['Color_F01.001']} />
              <mesh geometry={nodes.ID931_1.geometry} material={materials['Color_H01.001']} />
            </group>
            <group position={[10.769, 1.5, -0.937]}>
              <group position={[-7.38, 0.125, -3.33]}>
                <mesh geometry={nodes.group_31003.geometry} material={materials['Color_F06.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_31004.geometry} material={materials['Color_F06.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_31005.geometry} material={materials['Color_F06.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_32001.geometry} material={materials['Color_D07.001']} position={[0.417, 0, -0.417]} />
              </group>
              <group position={[0.489, 0.125, -1.556]}>
                <mesh geometry={nodes.group_37003.geometry} material={materials['Color_F07.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_37004.geometry} material={materials['Color_F07.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_37005.geometry} material={materials['Color_F07.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_38001.geometry} material={materials['Color_D08.001']} position={[0.417, 0, -0.417]} />
              </group>
              <group position={[-7.955, 0.125, -2.08]}>
                <mesh geometry={nodes.group_40003.geometry} material={materials['Color_F07.001']} position={[-0.139, 0.749, 0.139]} scale={[1.29, 1.793, 1.29]} />
                <mesh geometry={nodes.group_40004.geometry} material={materials['Color_F07.001']} position={[-0.139, 0.749, 0.139]} scale={[1.29, 1.793, 1.29]} />
                <mesh geometry={nodes.group_40005.geometry} material={materials['Color_F07.001']} position={[-0.139, 0.749, 0.139]} scale={[1.29, 1.793, 1.29]} />
                <mesh geometry={nodes.group_41001.geometry} material={materials['Color_D07.001']} position={[0.417, 0, -0.417]} />
              </group>
              <group position={[-6.902, 0.125, -1.509]}>
                <mesh geometry={nodes.group_43004.geometry} material={materials['Color_F08.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_43005.geometry} material={materials['Color_F08.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_43006.geometry} material={materials['Color_F08.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_43007.geometry} material={materials['Color_F08.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_44001.geometry} material={materials['Color_D08.001']} position={[0.417, 0, -0.417]} />
              </group>
              <group position={[-1.002, 0.125, -1.205]}>
                <mesh geometry={nodes.group_31006.geometry} material={materials['Color_F06.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_31007.geometry} material={materials['Color_F06.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_31008.geometry} material={materials['Color_F06.001']} position={[0, 0.75, 0]} />
                <mesh geometry={nodes.group_32002.geometry} material={materials['Color_D07.001']} position={[0.417, 0, -0.417]} />
              </group>
            </group>
            <group position={[6.072, 1.625, -1.669]} rotation={[0, 0.321, 0]}>
              <mesh geometry={nodes.group_60.geometry} material={materials['Color_M08.001']} position={[0, 0, -0.938]} />
              <mesh geometry={nodes.group_61.geometry} material={materials['Color_E04.001']} position={[2.372, 0.125, -1.688]} />
              <mesh geometry={nodes.group_62.geometry} material={materials['Color_E04.001']} position={[2.372, 0.125, -3.688]} />
              <mesh geometry={nodes.group_63.geometry} material={materials['Color_E04.001']} position={[2.372, 0.125, -5.688]} />
              <mesh geometry={nodes.group_64.geometry} material={materials['Color_E04.001']} position={[2.372, 0.125, -7.688]} />
              <mesh geometry={nodes.group_65.geometry} material={materials['Color_E04.001']} position={[2.372, 0.125, -9.688]} />
              <mesh geometry={nodes.group_66.geometry} material={materials['Color_E04.001']} position={[2.372, 0.125, -11.688]} />
            </group>
            <mesh geometry={nodes.group_52.geometry} material={materials['material.001']} />
            <mesh geometry={nodes.group_52001.geometry} material={materials['material.001']} />
            <mesh geometry={nodes.group_52002.geometry} material={materials['material.001']} />
            <mesh geometry={nodes.group_52003.geometry} material={materials['Color_F06.001']} />
            <mesh geometry={nodes.group_52004.geometry} material={materials['Color_D08.001']} />
            <mesh geometry={nodes.group_67.geometry} material={materials.Color_D01} position={[12.996, 1.625, -15.746]} />
            <mesh geometry={nodes.group_67001.geometry} material={materials.Color_D01} position={[12.996, 1.625, -15.746]} />
            <group position={[12.996, 1.974, -12.875]}>
              <mesh geometry={nodes.ID889.geometry} material={materials['Translucent_Glass_Gray.001']} />
              <mesh geometry={nodes.ID889_1.geometry} material={materials['Translucent_Glass_Blue.001']} />
            </group>
          </group>
          <mesh geometry={nodes.group_71.geometry} material={materials['material.001']} />
        </group>
        <group position={[83.88, 105.9, -69.255]} scale={1.34}>
          <group position={[0, 36, 0]}>
            <mesh geometry={nodes.group_74003.geometry} material={materials['Color_M01.001']} />
            <mesh geometry={nodes.group_75.geometry} material={materials['Color_A05.001']} position={[2.004, 1.625, -2.004]} />
            <mesh geometry={nodes.ID947.geometry} material={materials['Color_M01.001']} />
            <mesh geometry={nodes.ID947_1.geometry} material={materials['Color_M00.001']} />
            <mesh geometry={nodes.ID953001.geometry} material={materials['Color_M01.001']} />
            <mesh geometry={nodes.ID953001_1.geometry} material={materials['Color_M00.001']} />
            <mesh geometry={nodes.ID959.geometry} material={materials['Color_M01.001']} />
            <mesh geometry={nodes.ID959_1.geometry} material={materials['Color_M00.001']} />
            <mesh geometry={nodes.ID971.geometry} material={materials['Color_M01.001']} />
            <mesh geometry={nodes.ID971_1.geometry} material={materials['Color_M00.001']} />
          </group>
          <mesh geometry={nodes.group_76.geometry} material={materials['material.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/maxtower_02_1.glb')
