/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\\models\\maxtower_02\\terragraph.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/terragraph.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.025}>
        <group position={[26.625, 154.14, -12]} scale={1.34}>
          <group position={[2, 1.625, -2]}>
            <group position={[4.56, 0.125, -4.205]}>
              <mesh geometry={nodes.group_26.geometry} material={materials['Color_F06.004']} position={[0, 0.75, 0]} />
              <mesh geometry={nodes.group_26001.geometry} material={materials['Color_F06.004']} position={[0, 0.75, 0]} />
              <mesh geometry={nodes.group_26002.geometry} material={materials['Color_F06.004']} position={[0, 0.75, 0]} />
              <mesh geometry={nodes.group_27.geometry} material={materials['Color_D07.002']} position={[0.417, 0, -0.417]} />
            </group>
            <group position={[3.802, 0.125, -0.743]}>
              <mesh geometry={nodes.group_32.geometry} material={materials['Color_F07.002']} position={[0, 0.75, 0]} />
              <mesh geometry={nodes.group_32001.geometry} material={materials['Color_F07.002']} position={[0, 0.75, 0]} />
              <mesh geometry={nodes.group_32002.geometry} material={materials['Color_F07.002']} position={[0, 0.75, 0]} />
              <mesh geometry={nodes.group_33.geometry} material={materials['Color_D08.002']} position={[0.417, 0, -0.417]} />
            </group>
            <group position={[1.685, 0.125, -4.393]}>
              <mesh geometry={nodes.group_35.geometry} material={materials['Color_F07.002']} position={[-0.139, 0.749, 0.139]} scale={[1.29, 1.793, 1.29]} />
              <mesh geometry={nodes.group_35001.geometry} material={materials['Color_F07.002']} position={[-0.139, 0.749, 0.139]} scale={[1.29, 1.793, 1.29]} />
              <mesh geometry={nodes.group_35002.geometry} material={materials['Color_F07.002']} position={[-0.139, 0.749, 0.139]} scale={[1.29, 1.793, 1.29]} />
              <mesh geometry={nodes.group_36.geometry} material={materials['Color_D07.002']} position={[0.417, 0, -0.417]} />
            </group>
            <group position={[4.123, 0.125, -2.955]}>
              <mesh geometry={nodes.group_38.geometry} material={materials['Color_F08.002']} position={[0, 0.75, 0]} />
              <mesh geometry={nodes.group_38001.geometry} material={materials['Color_F08.002']} position={[0, 0.75, 0]} />
              <mesh geometry={nodes.group_38002.geometry} material={materials['Color_F08.002']} position={[0, 0.75, 0]} />
              <mesh geometry={nodes.group_38003.geometry} material={materials['Color_F08.002']} position={[0, 0.75, 0]} />
              <mesh geometry={nodes.group_39.geometry} material={materials['Color_D08.002']} position={[0.417, 0, -0.417]} />
            </group>
            <mesh geometry={nodes.group_28.geometry} material={materials['Color_M01.002']} position={[0.25, 0, -5.081]} rotation={[-Math.PI, 0, -Math.PI]} />
            <group position={[0, 0, -6.5]} rotation={[0, -1.571, 0]}>
              <mesh geometry={nodes.ID342.geometry} material={materials['Color_M01.002']} />
              <mesh geometry={nodes.ID342_1.geometry} material={materials['Color_M00.002']} />
              <mesh geometry={nodes.group_30.geometry} material={materials['Color_M01.002']} />
              <mesh geometry={nodes.group_30001.geometry} material={materials['Color_M01.002']} />
            </group>
            <mesh geometry={nodes.group_29001.geometry} material={materials['Color_M01.002']} position={[0, 0, -6.5]} rotation={[0, -1.571, 0]} />
            <group position={[0, 0, -6.5]} rotation={[0, -1.571, 0]}>
              <mesh geometry={nodes.ID356.geometry} material={materials['Color_M01.002']} />
              <mesh geometry={nodes.ID356_1.geometry} material={materials['Color_I03.002']} />
            </group>
            <group position={[0, 0, -6.5]} rotation={[0, -1.571, 0]}>
              <mesh geometry={nodes.ID364.geometry} material={materials['Color_M01.002']} />
              <mesh geometry={nodes.ID364_1.geometry} material={materials['Color_D07.002']} />
            </group>
            <group position={[0, 0, -6.5]} rotation={[0, -1.571, 0]}>
              <mesh geometry={nodes.ID370.geometry} material={materials['Color_F06.004']} />
              <mesh geometry={nodes.ID370_1.geometry} material={materials['Color_M01.002']} />
            </group>
          </group>
          <mesh geometry={nodes.group_1.geometry} material={materials['material.005']} position={[10.672, 3.75, -6.209]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.group_16.geometry} material={materials['Color_M01.002']} position={[9.5, 1.625, -2]}>
            <mesh geometry={nodes.group_17.geometry} material={materials['material.005']} position={[0.375, 0, -6.125]} />
            <mesh geometry={nodes.group_18.geometry} material={materials['material.005']} position={[0.375, 0, -0.25]} />
            <mesh geometry={nodes.group_19.geometry} material={materials['Color_H01.002']} position={[0.75, 0, -5.5]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.group_19001.geometry} material={materials['Color_H01.002']} position={[0.75, 0, -5.5]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.group_19002.geometry} material={materials['Color_H01.002']} position={[0.75, 0, -5.5]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.group_20.geometry} material={materials['Color_A01.002']} position={[3.75, 0, -2.75]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.group_20001.geometry} material={materials['Color_A01.002']} position={[3.75, 0, -2.75]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.group_21.geometry} material={materials['Color_E02.002']} position={[3.625, 0, -5.75]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.group_21001.geometry} material={materials['Color_E02.002']} position={[3.625, 0, -5.75]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.group_22.geometry} material={materials['Color_G02.002']} position={[0.75, 0, -2.75]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.group_22001.geometry} material={materials['Color_G02.002']} position={[0.75, 0, -2.75]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.group_23.geometry} material={materials['material.005']} position={[6.125, 0, -0.25]} />
          </mesh>
          <mesh geometry={nodes.group_16001.geometry} material={materials['material.005']} position={[9.5, 1.625, -2]} />
          <mesh geometry={nodes.group_2.geometry} material={materials['Color_I01.002']} position={[10, 1.625, -15.25]} rotation={[0, -1.571, 0]}>
            <mesh geometry={nodes.group_3.geometry} material={materials['Color_I01.002']} position={[0.375, 2.188, -1.5]} rotation={[0, 1.571, 0]} />
            <group position={[0.375, 2.188, -1.5]} rotation={[0, 1.571, 0]}>
              <mesh geometry={nodes.ID23.geometry} material={materials['Color_I01.002']} />
              <mesh geometry={nodes.ID23_1.geometry} material={materials['Color_M07.002']} />
            </group>
            <mesh geometry={nodes.group_4.geometry} material={materials['Color_I01.002']} position={[0.375, 3.188, -3.376]} rotation={[0, 1.571, 0]} />
            <mesh geometry={nodes.group_5.geometry} material={materials['Color_I01.002']} position={[0.375, 3.188, -1.5]} rotation={[0, 1.571, 0]} />
          </mesh>
          <mesh geometry={nodes.group_2001.geometry} material={materials['Color_I01.002']} position={[10, 1.625, -15.25]} rotation={[0, -1.571, 0]} />
          <group position={[10, 1.625, -15.25]} rotation={[0, -1.571, 0]}>
            <mesh geometry={nodes.ID57.geometry} material={materials['Color_I01.002']} />
            <mesh geometry={nodes.ID57_1.geometry} material={materials['Color_F06.004']} />
          </group>
          <mesh geometry={nodes.group_40.geometry} material={materials.Color_H03} position={[15.25, 3.125, -9.688]} scale={0.746} />
          <mesh geometry={nodes.group_41.geometry} material={materials.Color_H03} position={[9.75, 3.125, -2.25]} scale={0.746} />
          <mesh geometry={nodes.group_42.geometry} material={materials.Color_H03} position={[15.5, 3.125, -2.25]} scale={0.746} />
          <mesh geometry={nodes.group_43.geometry} material={materials.Color_H03} position={[2.25, 3.125, -6.956]} scale={0.746} />
          <mesh geometry={nodes.group_44.geometry} material={materials.Color_H03} position={[9.75, 3.125, -15.688]} scale={0.746} />
          <mesh geometry={nodes.group_45.geometry} material={materials.Color_H03} position={[4.618, 5.25, -13.566]} scale={0.746} />
          <mesh geometry={nodes.group_46.geometry} material={materials.Color_H03} position={[10.672, 5.25, -6.084]} scale={0.746} />
          <mesh geometry={nodes.group_47.geometry} material={materials.Color_H03} position={[8.25, 3.125, -9.688]} scale={0.746} />
          <mesh geometry={nodes.group_48.geometry} material={materials.Color_H03} position={[12.413, 4.358, -15]} scale={0.746} />
          <mesh geometry={nodes.group_49.geometry} material={materials.Color_H03} position={[9.75, 3.125, -8.125]} scale={0.746} />
          <mesh geometry={nodes.group_6.geometry} material={materials['material.005']} />
          <mesh geometry={nodes.group_6001.geometry} material={materials['material.005']} />
          <mesh geometry={nodes.group_6002.geometry} material={materials['material.005']} />
          <mesh geometry={nodes.group_7.geometry} material={materials['Color_M01.002']} position={[2, 1.625, -16]} rotation={[0, -1.571, 0]}>
            <mesh geometry={nodes.group_10.geometry} material={materials['Color_B01.002']} position={[0.75, 0, -3.875]} />
            <mesh geometry={nodes.group_10001.geometry} material={materials['Color_B01.002']} position={[0.75, 0, -3.875]} />
            <mesh geometry={nodes.group_11.geometry} material={materials['Color_F01.002']} position={[3.75, 0, -1]} />
            <mesh geometry={nodes.group_11001.geometry} material={materials['Color_F01.002']} position={[3.75, 0, -1]} />
            <mesh geometry={nodes.group_12.geometry} material={materials['material.005']} position={[2.309, 2.125, -2.618]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.group_13.geometry} material={materials['material.005']} position={[6.188, 0, -6.25]} rotation={[0, -1.571, 0]} />
            <mesh geometry={nodes.group_14.geometry} material={materials['material.005']} position={[0.313, 0, -7.875]} rotation={[0, 1.571, 0]} />
            <mesh geometry={nodes.group_15.geometry} material={materials['material.005']} position={[6.313, 0, -13.375]} rotation={[0, 1.571, 0]} />
            <mesh geometry={nodes.group_8.geometry} material={materials['Color_I01.002']} position={[1, 0, -1]} />
            <mesh geometry={nodes.group_8001.geometry} material={materials['Color_I01.002']} position={[1, 0, -1]} />
            <mesh geometry={nodes.group_8002.geometry} material={materials['Color_I01.002']} position={[1, 0, -1]} />
            <mesh geometry={nodes.group_9.geometry} material={materials['Color_K01.002']} position={[3.75, 0, -4]} />
            <mesh geometry={nodes.group_9001.geometry} material={materials['Color_K01.002']} position={[3.75, 0, -4]} />
          </mesh>
          <mesh geometry={nodes.group_7001.geometry} material={materials['material.005']} position={[2, 1.625, -16]} rotation={[0, -1.571, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/terragraph.glb')
