/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\\models\\blender\\TEST.glb -k -K 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/TEST.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="group_0" geometry={nodes.group_0.geometry} material={materials['material.001']} position={[-120, 0, 120]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={nodes.Cube.material} scale={[60, 1, 60]} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[0, 61, -59]} scale={[60, 60, 1]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[30, 31, -30]} scale={30} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[-30, 31, -30]} scale={30} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[-1, 90, -29]} rotation={[0, Math.PI / 2, 0]} scale={[29, 29, 1]} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[-31, 90, -1]} scale={[29, 29, 1]} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[-1, 120, 0]} scale={[59.016, 1, 60]} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[-30.5, 150, -59]} scale={[29.5, 29, 1]} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[-59, 150, -29]} rotation={[0, Math.PI / 2, 0]} scale={[29, 29, 1]} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[30, 31, 1]} scale={[30, 30, 1]} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[-57, 150, -29]} rotation={[0, Math.PI / 2, 0]} scale={[29, 29, 1]} />
        <mesh name="Projects" geometry={nodes.Projects.geometry} material={materials['Material.003']} position={[6, 36, 3.05]} rotation={[Math.PI / 2, 0, 0]} scale={[10, 15, 10]} />
        <mesh name="01" geometry={nodes['01'].geometry} material={materials['Material.002']} position={[6, 44, 3.4]} rotation={[Math.PI / 2, 0, 0]} scale={20} />
        <mesh name="02" geometry={nodes['02'].geometry} material={materials['Material.005']} position={[3.4, 104, -6]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={20} />
        <mesh name="Work" geometry={nodes.Work.geometry} material={materials['Material.004']} position={[3.05, 96, -6]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[10, 15, 10]} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[1, 90, -29]} rotation={[0, Math.PI / 2, 0]} scale={[29, 29, 1]} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[1, 121, 13.048]} rotation={[0, 0, -Math.PI / 2]} scale={19.796} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={nodes.Cube015.material} position={[17.007, 62, -13.073]} scale={[6, 1, 6]} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={nodes.Cube016.material} position={[26.929, 76.89, -18.832]} rotation={[Math.PI / 2, 0.777, -Math.PI / 2]} />
        <mesh name="About" geometry={nodes.About.geometry} material={materials['Material.007']} position={[-54.95, 155, -6]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[10, 15, 10]} />
        <mesh name="03" geometry={nodes['03'].geometry} material={materials['Material.006']} position={[-54.6, 163, -6]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={20} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} position={[-59, 102, 2]} scale={[1, 2, 2]} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} position={[-59, 80, 2]} scale={[1, 2, 2]} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} position={[-59, 100.242, 18.56]} scale={[2, 30, 14.5]} />
        <mesh name="02001" geometry={nodes['02001'].geometry} material={materials['Material.008']} position={[-55.95, 118.087, 16.632]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[20, 15, 13]} />
      </group>
    </group>
  )
}

useGLTF.preload('/TEST.glb')
