/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\\models\\blender\\tower.glb -k -K 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tower.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="base_floor" geometry={nodes.base_floor.geometry} material={nodes.base_floor.material} scale={[60, 1, 60]} />
        <mesh name="base_backwall" geometry={nodes.base_backwall.geometry} material={nodes.base_backwall.material} position={[0, 61, -59]} scale={[60, 60, 1]} />
        <mesh name="base_01" geometry={nodes.base_01.geometry} material={nodes.base_01.material} position={[30, 31, -30]} scale={30} />
        <mesh name="base_01_1" geometry={nodes.base_01_1.geometry} material={materials.Color_M07} position={[-30, 31, -30]} scale={30} />
        <mesh name="base_02" geometry={nodes.base_02.geometry} material={nodes.base_02.material} position={[-1, 90, -29]} rotation={[0, Math.PI / 2, 0]} scale={[29, 29, 1]} />
        <mesh name="base_02_1" geometry={nodes.base_02_1.geometry} material={nodes.base_02_1.material} position={[-31, 90, -1]} scale={[29, 29, 1]} />
        <mesh name="base_03" geometry={nodes.base_03.geometry} material={nodes.base_03.material} position={[-1, 120, 0]} scale={[59.016, 1, 60]} />
        <mesh name="base_03_1" geometry={nodes.base_03_1.geometry} material={nodes.base_03_1.material} position={[-30.5, 150, -59]} scale={[29.5, 29, 1]} />
        <mesh name="base_03_2" geometry={nodes.base_03_2.geometry} material={nodes.base_03_2.material} position={[-59, 150, -29]} rotation={[0, Math.PI / 2, 0]} scale={[29, 29, 1]} />
        <mesh name="Projects" geometry={nodes.Projects.geometry} material={materials['Material.003']} position={[6, 36, 3.05]} rotation={[Math.PI / 2, 0, 0]} scale={[10, 15, 10]} />
        <mesh name="01" geometry={nodes['01'].geometry} material={materials['Material.002']} position={[6, 44, 3.4]} rotation={[Math.PI / 2, 0, 0]} scale={20} />
        <mesh name="01_bg" geometry={nodes['01_bg'].geometry} material={materials.edge_color000255} position={[30, 31, 1]} scale={[30, 30, 1]} />
        <mesh name="02" geometry={nodes['02'].geometry} material={materials['Material.005']} position={[3.4, 104, -6]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={20} />
        <mesh name="Work" geometry={nodes.Work.geometry} material={materials['Material.004']} position={[3.05, 96, -6]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[10, 15, 10]} />
        <mesh name="02_bg" geometry={nodes['02_bg'].geometry} material={materials.edge_color000255} position={[1, 90, -29]} rotation={[0, Math.PI / 2, 0]} scale={[29, 29, 1]} />
        <mesh name="02_carpet" geometry={nodes['02_carpet'].geometry} material={materials.Color_001} position={[39.517, 61.25, -30.039]} scale={[8, 0.25, 26]} />
        <mesh name="Terragraph_Display" geometry={nodes.Terragraph_Display.geometry} material={nodes.Terragraph_Display.material} position={[17.007, 62, -13.073]} scale={[6, 1, 6]} />
        <mesh name="Terragraph_btn" geometry={nodes.Terragraph_btn.geometry} material={nodes.Terragraph_btn.material} position={[27.336, 77.011, -18.853]} rotation={[Math.PI / 2, 0.777, -Math.PI / 2]} />
        <mesh name="Terragraph_btn_base" geometry={nodes.Terragraph_btn_base.geometry} material={materials.Color_M08} position={[27.116, 76.8, -18.841]} rotation={[Math.PI / 2, 0.777, -Math.PI / 2]} />
        <mesh name="city_building" geometry={nodes.city_building.geometry} material={materials['Material.015']} position={[21.508, 79.517, -17.574]} scale={[0.75, 1, 0.75]} />
        <mesh name="city_building001" geometry={nodes.city_building001.geometry} material={materials['Material.017']} position={[21.508, 79.207, -15.573]} scale={[0.75, 0.69, 0.75]} />
        <mesh name="round_city_building" geometry={nodes.round_city_building.geometry} material={materials['Material.016']} position={[19.493, 79.253, -17.588]} scale={0.736} />
        <mesh name="city_building002" geometry={nodes.city_building002.geometry} material={materials['Material.011']} position={[19.508, 79.207, -15.573]} scale={[0.75, 0.69, 0.75]} />
        <mesh name="city_building004" geometry={nodes.city_building004.geometry} material={materials['Material.017']} position={[21.508, 79.207, -8.572]} scale={[0.75, 0.69, 0.75]} />
        <mesh name="city_building003" geometry={nodes.city_building003.geometry} material={materials['Material.015']} position={[19.508, 79.207, -8.572]} scale={[0.75, 0.69, 0.75]} />
        <mesh name="city_building005" geometry={nodes.city_building005.geometry} material={materials['Material.016']} position={[21.508, 79.207, -10.573]} scale={[0.75, 0.69, 0.75]} />
        <mesh name="round_city_building001" geometry={nodes.round_city_building001.geometry} material={materials['Material.011']} position={[19.493, 79.253, -10.587]} scale={0.736} />
        <mesh name="stadium" geometry={nodes.stadium.geometry} material={materials.Color_M07} position={[13.662, 79.117, -16.418]} scale={[1.906, 0.6, 1.906]} />
        <mesh name="city_building008" geometry={nodes.city_building008.geometry} material={materials['Material.015']} position={[16.422, 79.055, -17.739]} scale={[0.585, 0.538, 0.585]} />
        <mesh name="round_city_building002" geometry={nodes.round_city_building002.geometry} material={materials['Material.017']} position={[15.989, 79.536, -14.092]} scale={1.019} />
        <mesh name="city_building009" geometry={nodes.city_building009.geometry} material={materials['Material.011']} position={[12.341, 79.055, -13.658]} rotation={[0, Math.PI / 2, 0]} scale={[0.585, 0.538, 0.585]} />
        <mesh name="round_city_building005" geometry={nodes.round_city_building005.geometry} material={materials['Material.015']} position={[21.523, 79.253, -13.809]} scale={0.736} />
        <mesh name="city_building012" geometry={nodes.city_building012.geometry} material={materials['Material.016']} position={[19.508, 79.207, -13.823]} rotation={[0, Math.PI / 2, 0]} scale={[0.75, 0.69, 0.75]} />
        <mesh name="park" geometry={nodes.park.geometry} material={materials.Color_G07} position={[12.756, 78.617, -8.822]} scale={[1, 0.1, 1]} />
        <mesh name="tree" geometry={nodes.tree.geometry} material={materials['Material.010']} position={[16.062, 79.117, -8.662]} scale={[0.059, 0.5, 0.059]} />
        <mesh name="tree001" geometry={nodes.tree001.geometry} material={materials.Color_G07} position={[16.037, 79.782, -8.659]} scale={0.543} />
        <mesh name="tree002" geometry={nodes.tree002.geometry} material={materials.Color_G07} position={[16.48, 79.438, -9.678]} scale={0.383} />
        <mesh name="tree003" geometry={nodes.tree003.geometry} material={materials['Material.010']} position={[16.498, 78.969, -9.68]} scale={[0.042, 0.353, 0.042]} />
        <mesh name="tree004" geometry={nodes.tree004.geometry} material={materials['Material.010']} position={[15.04, 78.969, -8.116]} scale={[0.042, 0.353, 0.042]} />
        <mesh name="tree005" geometry={nodes.tree005.geometry} material={materials.Color_G07} position={[15.022, 79.438, -8.114]} scale={0.383} />
        <mesh name="tree006" geometry={nodes.tree006.geometry} material={materials.Color_G07} position={[12.698, 79.438, -10.676]} scale={0.383} />
        <mesh name="tree007" geometry={nodes.tree007.geometry} material={materials['Material.010']} position={[12.715, 78.969, -10.678]} scale={[0.042, 0.353, 0.042]} />
        <mesh name="tree008" geometry={nodes.tree008.geometry} material={materials['Material.010']} position={[13.652, 79.041, -10.433]} scale={[0.055, 0.467, 0.055]} />
        <mesh name="tree009" geometry={nodes.tree009.geometry} material={materials.Color_G07} position={[13.629, 79.662, -10.43]} scale={0.507} />
        <mesh name="tree010" geometry={nodes.tree010.geometry} material={materials.Color_G07} position={[12.359, 79.438, -9.348]} scale={0.383} />
        <mesh name="tree011" geometry={nodes.tree011.geometry} material={materials['Material.010']} position={[12.377, 78.969, -9.35]} scale={[0.042, 0.353, 0.042]} />
        <mesh name="tree012" geometry={nodes.tree012.geometry} material={materials.Color_G07} position={[12.359, 79.317, -9.748]} scale={0.278} />
        <mesh name="tree013" geometry={nodes.tree013.geometry} material={materials.Color_G07} position={[16.037, 79.555, -8.243]} scale={0.371} />
        <mesh name="tree014" geometry={nodes.tree014.geometry} material={materials.Color_G07} position={[13.926, 80.008, -10.566]} scale={0.317} />
        <mesh name="terragraph_pole" geometry={nodes.terragraph_pole.geometry} material={materials.Color_M07} position={[11.962, 78.863, -7.456]} scale={[0.042, 0.353, 0.042]} />
        <mesh name="terragraph" geometry={nodes.terragraph.geometry} material={materials['Material.013']} position={[11.888, 79.33, -7.341]} scale={0.115} />
        <mesh name="terragraph_pole001" geometry={nodes.terragraph_pole001.geometry} material={materials.Color_M07} position={[16.947, 78.863, -12.982]} scale={[0.042, 0.353, 0.042]} />
        <mesh name="terragraph001" geometry={nodes.terragraph001.geometry} material={nodes.terragraph001.material} position={[16.874, 79.33, -12.868]} scale={0.115} />
        <mesh name="terragraph_pole002" geometry={nodes.terragraph_pole002.geometry} material={materials.Color_M07} position={[21.067, 80.916, -9.044]} scale={[0.042, 0.353, 0.042]} />
        <mesh name="terragraph002" geometry={nodes.terragraph002.geometry} material={nodes.terragraph002.material} position={[20.994, 81.383, -8.929]} scale={0.115} />
        <mesh name="terragraph_pole003" geometry={nodes.terragraph_pole003.geometry} material={materials.Color_M07} position={[21.021, 80.714, -17.108]} scale={[0.042, 0.353, 0.042]} />
        <mesh name="terragraph003" geometry={nodes.terragraph003.geometry} material={nodes.terragraph003.material} position={[20.948, 81.181, -16.993]} scale={0.115} />
        <mesh name="terragraph_pole004" geometry={nodes.terragraph_pole004.geometry} material={materials.Color_M07} position={[11.349, 78.863, -11.442]} scale={[0.042, 0.353, 0.042]} />
        <mesh name="terragraph004" geometry={nodes.terragraph004.geometry} material={nodes.terragraph004.material} position={[11.276, 79.33, -11.327]} scale={0.115} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Color_M08} position={[11.946, 80.224, -16.464]} scale={[-0.05, -0.5, -1]} />
        <mesh name="Terragraph_Display001" geometry={nodes.Terragraph_Display001.geometry} material={materials['Material.014']} position={[17.007, 62, -13.073]} scale={[6, 1, 6]} />
        <mesh name="water" geometry={nodes.water.geometry} material={materials['Material.012']} position={[13.48, 78.56, -9.036]} scale={[1, 0.01, 1]} />
        <mesh name="Terrazed_Display002" geometry={nodes.Terrazed_Display002.geometry} material={materials['Material.014']} position={[17.007, 62, -30.256]} scale={[6, 1, 6]} />
        <mesh name="Terrazed_btn_base001" geometry={nodes.Terrazed_btn_base001.geometry} material={materials.Color_M08} position={[27.116, 76.8, -36.023]} rotation={[Math.PI / 2, 0.777, -Math.PI / 2]} />
        <mesh name="Terrazed_btn001" geometry={nodes.Terrazed_btn001.geometry} material={nodes.Terrazed_btn001.material} position={[27.336, 77.011, -36.036]} rotation={[Math.PI / 2, 0.777, -Math.PI / 2]} />
        <mesh name="landing_strip" geometry={nodes.landing_strip.geometry} material={materials.edge_color000255} position={[15.637, 78.567, -30.314]} rotation={[0, 0.452, 0]} scale={[2, 0.05, 6]} />
        <mesh name="radar_support001" geometry={nodes.radar_support001.geometry} material={materials.Color_M07} position={[18.295, 78.567, -35.723]} scale={[0.25, 0.05, 0.25]} />
        <mesh name="radar_dish" geometry={nodes.radar_dish.geometry} material={materials.Material} position={[18.293, 79.718, -35.709]} />
        <mesh name="radar_dish001" geometry={nodes.radar_dish001.geometry} material={materials.Material} position={[21.923, 79.718, -25.317]} />
        <mesh name="radar_support" geometry={nodes.radar_support.geometry} material={materials.Color_M07} position={[21.924, 78.567, -25.332]} scale={[0.25, 0.05, 0.25]} />
        <mesh name="tree015" geometry={nodes.tree015.geometry} material={materials.Color_G07} position={[13.946, 79.889, -24.957]} scale={0.317} />
        <mesh name="tree016" geometry={nodes.tree016.geometry} material={materials.Color_G07} position={[11.938, 79.714, -25.399]} scale={0.571} />
        <mesh name="tree017" geometry={nodes.tree017.geometry} material={materials.Color_G07} position={[13.649, 79.543, -24.82]} scale={0.507} />
        <mesh name="tree018" geometry={nodes.tree018.geometry} material={materials['Material.010']} position={[13.672, 78.922, -24.823]} rotation={[0, 0.873, 0]} scale={[0.055, 0.467, 0.055]} />
        <mesh name="tree019" geometry={nodes.tree019.geometry} material={materials['Material.010']} position={[11.203, 78.85, -28.281]} scale={[0.042, 0.353, 0.042]} />
        <mesh name="tree020" geometry={nodes.tree020.geometry} material={materials.Color_G07} position={[11.185, 79.319, -28.279]} scale={0.383} />
        <mesh name="tree021" geometry={nodes.tree021.geometry} material={materials.Color_G07} position={[15.043, 79.319, -24.314]} scale={0.383} />
        <mesh name="tree022" geometry={nodes.tree022.geometry} material={materials['Material.010']} position={[15.06, 78.85, -24.316]} scale={[0.042, 0.353, 0.042]} />
        <mesh name="tree025" geometry={nodes.tree025.geometry} material={materials.Color_G07} position={[11.938, 80.063, -26.04]} scale={0.835} />
        <mesh name="tree026" geometry={nodes.tree026.geometry} material={materials['Material.010']} position={[11.976, 79.039, -26.044]} scale={[0.091, 0.769, 0.091]} />
        <mesh name="tree023" geometry={nodes.tree023.geometry} material={materials['Material.010']} position={[11.266, 78.922, -29.862]} scale={[0.055, 0.467, 0.055]} />
        <mesh name="tree024" geometry={nodes.tree024.geometry} material={materials.Color_G07} position={[11.243, 79.543, -29.86]} scale={0.507} />
        <mesh name="tree027" geometry={nodes.tree027.geometry} material={materials.Color_G07} position={[11.54, 79.889, -29.996]} scale={0.317} />
        <mesh name="demo_stuff" geometry={nodes.demo_stuff.geometry} material={materials['Material.010']} position={[21.318, 79.517, -32.216]} scale={[0.05, 1, 0.05]} />
        <mesh name="demo_stuff004" geometry={nodes.demo_stuff004.geometry} material={materials['Material.010']} position={[21.318, 78.767, -32.316]} scale={[0.05, 0.25, 0.05]} />
        <mesh name="demo_stuff006" geometry={nodes.demo_stuff006.geometry} material={materials['Material.010']} position={[21.318, 79.517, -35.298]} scale={[0.05, 1, 0.05]} />
        <mesh name="demo_window" geometry={nodes.demo_window.geometry} material={materials.glass} position={[21.318, 79.267, -32.316]} scale={[0.05, 0.25, 0.05]} />
        <mesh name="demo_stuff005" geometry={nodes.demo_stuff005.geometry} material={materials['Material.010']} position={[21.318, 80.567, -32.216]} scale={0.05} />
        <mesh name="demo_stuff009" geometry={nodes.demo_stuff009.geometry} material={materials['Material.010']} position={[21.628, 78.667, -33.275]} scale={[0.05, 0.15, 0.05]} />
        <mesh name="demo_big_screen" geometry={nodes.demo_big_screen.geometry} material={materials.Color_M08} position={[21.628, 78.967, -33.275]} scale={[0.05, 0.15, 0.05]} />
        <mesh name="demo_stuff007" geometry={nodes.demo_stuff007.geometry} material={materials['Material.010']} position={[21.628, 78.667, -34.302]} scale={[0.05, 0.15, 0.05]} />
        <mesh name="demo_stuff008" geometry={nodes.demo_stuff008.geometry} material={materials['Material.010']} position={[21.646, 78.612, -35.216]} scale={[0.032, 0.095, 0.032]} />
        <mesh name="demo_right_screen" geometry={nodes.demo_right_screen.geometry} material={materials.Color_M08} position={[21.646, 78.803, -34.563]} scale={[0.032, 0.095, 0.032]} />
        <mesh name="demo_stuff003" geometry={nodes.demo_stuff003.geometry} material={materials['Material.010']} position={[21.646, 78.612, -34.563]} scale={[0.032, 0.095, 0.032]} />
        <mesh name="demo_stuff002" geometry={nodes.demo_stuff002.geometry} material={materials['Material.010']} position={[21.646, 78.612, -32.367]} scale={[0.032, 0.095, 0.032]} />
        <mesh name="demo_left_screen" geometry={nodes.demo_left_screen.geometry} material={materials.Color_M08} position={[21.646, 78.803, -32.367]} scale={[0.032, 0.095, 0.032]} />
        <mesh name="demo_stuff001" geometry={nodes.demo_stuff001.geometry} material={materials['Material.010']} position={[21.646, 78.612, -33.02]} scale={[0.032, 0.095, 0.032]} />
        <mesh name="Rayban_Display001" geometry={nodes.Rayban_Display001.geometry} material={materials['Material.014']} position={[17.007, 62, -47.462]} scale={[6, 1, 6]} />
        <mesh name="Rayban_btn_base002" geometry={nodes.Rayban_btn_base002.geometry} material={materials.Color_M08} position={[27.116, 76.8, -53.229]} rotation={[Math.PI / 2, 0.777, -Math.PI / 2]} />
        <mesh name="Rayban_btn002" geometry={nodes.Rayban_btn002.geometry} material={nodes.Rayban_btn002.material} position={[27.336, 77.011, -53.242]} rotation={[Math.PI / 2, 0.777, -Math.PI / 2]} />
        <mesh name="rayban_stand" geometry={nodes.rayban_stand.geometry} material={materials['SVGMat.003']} position={[28.297, 78.517, -27.069]} rotation={[0, Math.PI / 2, 0]} scale={104.388} />
        <mesh name="rayban_stand001" geometry={nodes.rayban_stand001.geometry} material={materials['SVGMat.003']} position={[28.297, 78.517, -27.069]} rotation={[0, Math.PI / 2, 0]} scale={104.388} />
        <mesh name="rayban_stand002" geometry={nodes.rayban_stand002.geometry} material={materials['SVGMat.003']} position={[28.297, 78.517, -27.069]} rotation={[0, Math.PI / 2, 0]} scale={104.388} />
        <mesh name="rayban_stand003" geometry={nodes.rayban_stand003.geometry} material={materials['SVGMat.003']} position={[28.297, 78.517, -27.069]} rotation={[0, Math.PI / 2, 0]} scale={104.388} />
        <mesh name="rayban_stand004" geometry={nodes.rayban_stand004.geometry} material={materials['SVGMat.003']} position={[28.297, 78.517, -27.069]} rotation={[0, Math.PI / 2, 0]} scale={104.388} />
        <mesh name="rayban_stand005" geometry={nodes.rayban_stand005.geometry} material={materials['SVGMat.003']} position={[28.297, 78.517, -27.069]} rotation={[0, Math.PI / 2, 0]} scale={104.388} />
        <mesh name="rayban_stand006" geometry={nodes.rayban_stand006.geometry} material={materials['SVGMat.003']} position={[28.297, 78.517, -27.069]} rotation={[0, Math.PI / 2, 0]} scale={104.388} />
        <mesh name="rayban_stand007" geometry={nodes.rayban_stand007.geometry} material={materials['SVGMat.003']} position={[28.297, 78.517, -27.069]} rotation={[0, Math.PI / 2, 0]} scale={104.388} />
        <mesh name="rayban_stand008" geometry={nodes.rayban_stand008.geometry} material={materials['SVGMat.003']} position={[28.297, 78.517, -27.069]} rotation={[0, Math.PI / 2, 0]} scale={104.388} />
        <mesh name="pdf" geometry={nodes.pdf.geometry} material={materials.Color_M07} position={[39.926, 82.019, -57.9]} scale={[2.5, 2, 0.1]} />
        <mesh name="pdf001" geometry={nodes.pdf001.geometry} material={nodes.pdf001.material} position={[39.137, 84.057, -57.526]} rotation={[-0.066, 0, 0]} scale={[1.5, 2, 0.05]} />
        <mesh name="pdf002" geometry={nodes.pdf002.geometry} material={nodes.pdf002.material} position={[40.838, 83.358, -57.178]} scale={[1.5, 2, 0.05]} />
        <mesh name="pdf003" geometry={nodes.pdf003.geometry} material={nodes.pdf003.material} position={[39.89, 83.277, -56.984]} rotation={[0.111, 0, 0]} scale={[1.5, 2, 0.05]} />
        <mesh name="Text" geometry={nodes.Text.geometry} material={materials['Material.001']} position={[40.147, 114.489, -57.75]} rotation={[Math.PI / 2, 0, 0]} scale={[6, 1, 5]} />
        <mesh name="Text001" geometry={nodes.Text001.geometry} material={materials['Material.001']} position={[42.278, 94.61, -57.75]} rotation={[Math.PI / 2, 0, 0]} scale={[5, 1, 4]} />
        <mesh name="pdf_arrow" geometry={nodes.pdf_arrow.geometry} material={materials['Material.012']} position={[39.986, 87.95, -57.8]} rotation={[0, 0, -Math.PI]} scale={[3.034, 3.034, 0.607]} />
        <mesh name="About" geometry={nodes.About.geometry} material={materials['Material.007']} position={[-54.95, 155, -6]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[10, 15, 10]} />
        <mesh name="03" geometry={nodes['03'].geometry} material={materials['Material.006']} position={[-54.6, 163, -6]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={20} />
        <mesh name="03_bg" geometry={nodes['03_bg'].geometry} material={materials.edge_color000255} position={[-57, 150, -29]} rotation={[0, Math.PI / 2, 0]} scale={[29, 29, 1]} />
        <mesh name="billboard_support" geometry={nodes.billboard_support.geometry} material={materials.edge_color000255} position={[-59, 102, 2]} scale={[1, 2, 2]} />
        <mesh name="billboard_support_1" geometry={nodes.billboard_support_1.geometry} material={materials.edge_color000255} position={[-59, 80, 2]} scale={[1, 2, 2]} />
        <mesh name="billboard_main" geometry={nodes.billboard_main.geometry} material={materials.Color_M08} position={[-59, 100.242, 18.56]} scale={[2, 30, 14.5]} />
        <mesh name="billboard_text" geometry={nodes.billboard_text.geometry} material={materials['Material.008']} position={[-55.95, 118.087, 16.632]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[20, 15, 13]} />
      </group>
    </group>
  )
}

useGLTF.preload('/tower.glb')
