/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\hut.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hut.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.03}>
        <group position={[-60, 0, 60]}>
          <mesh geometry={nodes.ID4003.geometry} material={materials['Mirror_02.001']} />
          <mesh geometry={nodes.ID4003_1.geometry} material={materials['Translucent_Glass_Blue.001']} />
        </group>
        <mesh geometry={nodes.group_1.geometry} material={materials['Wood_Veneer_02.002']} position={[54, 0, -54]} />
        <mesh geometry={nodes.group_10.geometry} material={materials['material.001']} position={[-61, 38.04, -19.2]} />
        <mesh geometry={nodes.group_11.geometry} material={materials['material.001']} position={[-61, 15.73, 20.05]} />
        <mesh geometry={nodes.group_12.geometry} material={materials['material.001']} position={[-61, 8.86, -42.33]} />
        <mesh geometry={nodes.group_2.geometry} material={materials['Stone_Marble.002']} position={[-54, 0, -42]} />
        <mesh geometry={nodes.group_3.geometry} material={materials['Stone_Marble.002']} position={[-53.5, 24, -42]} />
        <mesh geometry={nodes.group_4.geometry} material={materials['Metal_Steel_Textured_White.002']} position={[-66, 90, 48]} />
        <mesh geometry={nodes.group_5.geometry} material={materials['Metal_Steel_Textured_White.002']} position={[-66, 90, 12]} />
        <mesh geometry={nodes.group_6.geometry} material={materials['Metal_Steel_Textured_White.002']} position={[30, 6, 66]} />
        <mesh geometry={nodes.group_7.geometry} material={materials['material.001']} position={[-61, 107.35, -55]} />
        <mesh geometry={nodes.group_8.geometry} material={materials['material.001']} position={[-61, 85.23, -37.94]} />
        <mesh geometry={nodes.group_9.geometry} material={materials['material.001']} position={[-61, 56.23, -48.82]} />
        <mesh geometry={nodes.instance_0.geometry} material={materials['Chris_Shirt.003']} position={[-41.5, 0, 46]} rotation={[0, -0.71, 0]} />
        <mesh geometry={nodes.instance_0001.geometry} material={materials['Chris_Shirt.003']} position={[-41.5, 0, 46]} rotation={[0, -0.71, 0]} />
        <mesh geometry={nodes.instance_0002.geometry} material={materials['Chris_Shoe.003']} position={[-41.5, 0, 46]} rotation={[0, -0.71, 0]} />
        <mesh geometry={nodes.instance_0003.geometry} material={materials['Chris_Shirt.003']} position={[-41.5, 0, 46]} rotation={[0, -0.71, 0]} />
        <mesh geometry={nodes.instance_0004.geometry} material={materials['Chris_Skin.003']} position={[-41.5, 0, 46]} rotation={[0, -0.71, 0]} />
        <mesh geometry={nodes.instance_0005.geometry} material={materials['Chris_Shoe_Sole.003']} position={[-41.5, 0, 46]} rotation={[0, -0.71, 0]} />
        <mesh geometry={nodes.instance_0006.geometry} material={materials['Chris_Shoe_Sole.003']} position={[-41.5, 0, 46]} rotation={[0, -0.71, 0]} />
        <mesh geometry={nodes.instance_0007.geometry} material={materials['Chris_Skin.003']} position={[-41.5, 0, 46]} rotation={[0, -0.71, 0]} />
        <mesh geometry={nodes.instance_0008.geometry} material={materials['Chris_Hair.003']} position={[-41.5, 0, 46]} rotation={[0, -0.71, 0]} />
        <mesh geometry={nodes.instance_0009.geometry} material={materials['Chris_Shoe_Sole.003']} position={[-41.5, 0, 46]} rotation={[0, -0.71, 0]} />
        <mesh geometry={nodes.instance_0010.geometry} material={materials['Chris_Hair.003']} position={[-41.5, 0, 46]} rotation={[0, -0.71, 0]} />
        <mesh geometry={nodes.instance_0011.geometry} material={materials['Chris_Skin.003']} position={[-41.5, 0, 46]} rotation={[0, -0.71, 0]} />
        <mesh geometry={nodes.instance_0012.geometry} material={materials['Chris_Shoe.003']} position={[-41.5, 0, 46]} rotation={[0, -0.71, 0]} />
        <mesh geometry={nodes.instance_0013.geometry} material={materials['Chris_Pants.003']} position={[-41.5, 0, 46]} rotation={[0, -0.71, 0]} />
        <mesh geometry={nodes.instance_0014.geometry} material={materials['Chris_Skin.003']} position={[-41.5, 0, 46]} rotation={[0, -0.71, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/hut.glb')
