/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\hut5.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hut5.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SketchUp.geometry} material={materials.material} scale={0.03}>
        <group position={[-58, 113, -60]}>
          <mesh geometry={nodes.group_1.geometry} material={materials.Metal_Embossed} />
          <mesh geometry={nodes.group_2.geometry} material={materials.Color_A04} position={[0.5, 0.5, -2]} />
          <mesh geometry={nodes.group_3.geometry} material={materials.Color_G03} position={[1, 1, -2.5]} />
          <mesh geometry={nodes.group_3001.geometry} material={materials.Color_G03} position={[1, 1, -2.5]} />
        </group>
        <group position={[150.56, 0, -68.67]} rotation={[0, -0.96, 0]}>
          <mesh geometry={nodes.group_17.geometry} material={materials.Wood_Veneer_02} />
          <group position={[0, 84, 0]}>
            <mesh geometry={nodes.ID169.geometry} material={materials.Translucent_Glass_Gold} />
            <mesh geometry={nodes.ID169_1.geometry} material={materials.Translucent_Glass_Gray} />
          </group>
        </group>
        <group position={[50.6, 157.24, -41.98]} rotation={[Math.PI, 0, 0]} scale={[1.1, 1.33, 1.5]}>
          <mesh geometry={nodes.group_30.geometry} material={materials.material} />
          <mesh geometry={nodes.group_30001.geometry} material={materials.material} />
          <mesh geometry={nodes.group_31.geometry} material={materials.material} position={[1, 24, -1]} />
          <mesh geometry={nodes.group_32.geometry} material={materials.material} position={[1, 24, -33]} />
          <mesh geometry={nodes.group_33.geometry} material={materials.material} position={[2.55, 23, -35]} rotation={[-Math.PI, 0, 0]} scale={[0.91, 0.75, 0.67]} />
        </group>
        <group position={[21.05, 39.53, 54]}>
          <mesh geometry={nodes.group_35.geometry} material={materials.material} />
          <mesh geometry={nodes.group_35001.geometry} material={materials.material} />
          <mesh geometry={nodes.group_36.geometry} material={materials.Color_M00} position={[1, 1, -1]} />
        </group>
        <group position={[155.75, 77.52, -71.72]} rotation={[0, -0.96, 0]}>
          <mesh geometry={nodes.group_1001.geometry} material={materials.Metal_Embossed} />
          <mesh geometry={nodes.group_2001.geometry} material={materials.Color_A04} position={[0.5, 0.5, -2]} />
          <mesh geometry={nodes.group_3002.geometry} material={materials.Color_G03} position={[1, 1, -2.5]} />
          <mesh geometry={nodes.group_3003.geometry} material={materials.Color_G03} position={[1, 1, -2.5]} />
        </group>
        <group position={[-54, 43.6, -15.41]} rotation={[-Math.PI / 2, -1.57, 0]} scale={1.27}>
          <mesh geometry={nodes.group_35002.geometry} material={materials.material} />
          <mesh geometry={nodes.group_35003.geometry} material={materials.material} />
          <mesh geometry={nodes.group_36001.geometry} material={materials.Color_M00} position={[1, 1, -1]} />
        </group>
        <group position={[51, 148, 17.21]} rotation={[Math.PI, 0, 0]}>
          <mesh geometry={nodes.group_46.geometry} material={materials.material} />
          <mesh geometry={nodes.group_46001.geometry} material={materials.material} />
          <mesh geometry={nodes.group_47.geometry} material={materials.material} position={[1, 24, -1]} />
          <mesh geometry={nodes.group_48.geometry} material={materials.material} position={[1, 24, -33]} />
          <mesh geometry={nodes.group_49.geometry} material={materials.material} position={[3, 1, -1]} />
        </group>
        <mesh geometry={nodes.group_10.geometry} material={materials.material} position={[44.7, 18, -80.4]} rotation={[0, -0.14, Math.PI]} />
        <mesh geometry={nodes.group_11.geometry} material={materials.material} position={[-66, 90, 12]} />
        <mesh geometry={nodes.group_12.geometry} material={materials.Color_C04} position={[-53.5, 24, -42]} />
        <mesh geometry={nodes.group_13.geometry} material={materials.material} position={[57, 0, -13.94]} />
        <mesh geometry={nodes.group_14.geometry} material={materials.material} position={[55, 0, 21.92]} />
        <mesh geometry={nodes.group_15.geometry} material={materials.material} position={[-8.93, 18, -77.52]} rotation={[0, -0.14, Math.PI]} />
        <mesh geometry={nodes.group_19.geometry} material={materials.material} position={[57, 0, 19]} />
        <mesh geometry={nodes.group_20.geometry} material={materials.material} position={[54, 0, -54]} />
        <mesh geometry={nodes.group_21.geometry} material={materials.material} position={[56, 0, 54]} />
        <mesh geometry={nodes.group_22.geometry} material={materials.Color_C04} position={[-54, 0, -42]}>
          <mesh geometry={nodes.group_23.geometry} material={materials.Color_M02} position={[24.5, 24.5, -35]} />
        </mesh>
        <mesh geometry={nodes.group_22001.geometry} material={materials.Color_C04} position={[-54, 0, -42]} />
        <mesh geometry={nodes.group_24.geometry} material={materials.material} position={[55, 0, -21.63]} />
        <mesh geometry={nodes.group_25.geometry} material={materials.material} position={[20.56, 18, -78.52]} rotation={[0, 0.08, Math.PI]} />
        <group position={[-60, 0, 60]}>
          <mesh geometry={nodes.ID242.geometry} material={materials.Color_M02} />
          <mesh geometry={nodes.ID242_1.geometry} material={materials.Translucent_Glass_Blue} />
        </group>
        <group position={[-60, 0, 60]}>
          <mesh geometry={nodes.ID250.geometry} material={materials.Translucent_Glass_Blue} />
          <mesh geometry={nodes.ID250_1.geometry} material={materials.Color_I02} />
        </group>
        <group position={[-60, 0, 60]}>
          <mesh geometry={nodes.ID258.geometry} material={materials.Color_M02} />
          <mesh geometry={nodes.ID258_1.geometry} material={materials.Translucent_Glass_Blue} />
        </group>
        <mesh geometry={nodes.group_27.geometry} material={materials.material} position={[30, 6, 66]} />
        <mesh geometry={nodes.group_28.geometry} material={materials.material} position={[-66, 90, 48]} />
        <mesh geometry={nodes.group_37.geometry} material={materials.Color_M03} position={[56.94, 73.93, -60.1]} />
        <mesh geometry={nodes.group_37001.geometry} material={materials.Color_M03} position={[56.94, 73.93, -60.1]} />
        <mesh geometry={nodes.group_38.geometry} material={materials.material} position={[-61, 107.35, -55]} />
        <mesh geometry={nodes.group_39.geometry} material={materials.material} position={[-61, 66.16, -37.94]} />
        <mesh geometry={nodes.group_41.geometry} material={materials.material} position={[-61, 46.84, 2.32]} />
        <mesh geometry={nodes.group_42.geometry} material={materials.material} position={[-54, 82, -58]} />
        <mesh geometry={nodes.group_43.geometry} material={materials.material} position={[58, 82.03, 54]} />
        <mesh geometry={nodes.group_44.geometry} material={materials.material} position={[-49.56, 120, 48]} scale={[1, 0.6, 1]} />
        <mesh geometry={nodes.group_44001.geometry} material={materials.Wood_Veneer_02_0} position={[-49.56, 120, 48]} scale={[1, 0.6, 1]} />
        <mesh geometry={nodes.group_44002.geometry} material={materials.Color_C06} position={[-49.56, 120, 48]} scale={[1, 0.6, 1]} />
        <mesh geometry={nodes.group_44003.geometry} material={materials.material} position={[-49.56, 120, 48]} scale={[1, 0.6, 1]} />
        <group position={[-49.56, 120, 48]} scale={[1, 0.6, 1]}>
          <mesh geometry={nodes.ID461.geometry} material={materials.Wood_Veneer_02_0} />
          <mesh geometry={nodes.ID461_1.geometry} material={materials.Metal_Silver} />
        </group>
        <mesh geometry={nodes.group_44005.geometry} material={materials.Metal_Silver} position={[-49.56, 120, 48]} scale={[1, 0.6, 1]} />
        <mesh geometry={nodes.group_44006.geometry} material={materials.Metal_Silver} position={[-49.56, 120, 48]} scale={[1, 0.6, 1]} />
        <mesh geometry={nodes.group_44007.geometry} material={materials.Metal_Silver} position={[-49.56, 120, 48]} scale={[1, 0.6, 1]} />
        <mesh geometry={nodes.group_5.geometry} material={materials.material} position={[-61, 22.55, -27.22]} />
        <mesh geometry={nodes.group_50.geometry} material={materials.material} position={[16, 0, 53]} />
        <mesh geometry={nodes.group_51.geometry} material={materials.material} position={[-56.93, 120, -52.25]} />
        <mesh geometry={nodes.group_52.geometry} material={materials.Color_D01} position={[54.42, 67.79, -60]} />
        <mesh geometry={nodes.group_6.geometry} material={materials.material} position={[-61, 15.73, 20.05]} />
        <mesh geometry={nodes.group_7.geometry} material={materials.material} position={[-61, 10.44, -55]} />
        <mesh geometry={nodes.group_8.geometry} material={materials.material} position={[-54, 47.69, 37.04]} />
        <mesh geometry={nodes.group_9.geometry} material={materials.material} position={[57, 0, 51]} />
        <mesh geometry={nodes.instance_0.geometry} material={materials.material} position={[58.56, 90.08, -60]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh geometry={nodes.instance_0001.geometry} material={materials.material} position={[58.56, 90.08, -60]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh geometry={nodes.instance_0002.geometry} material={materials.material} position={[58.56, 90.08, -60]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh geometry={nodes.instance_1.geometry} material={materials.material} position={[60, 90, -21.47]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.instance_1001.geometry} material={materials.material} position={[60, 90, -21.47]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.instance_1002.geometry} material={materials.material} position={[60, 90, -21.47]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.instance_1003.geometry} material={materials.material} position={[60, 90, -21.47]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.instance_2.geometry} material={materials.Chris_Shirt} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.57, -Math.PI]} />
        <mesh geometry={nodes.instance_2001.geometry} material={materials.Chris_Shirt} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.57, -Math.PI]} />
        <mesh geometry={nodes.instance_2002.geometry} material={materials.Chris_Shoe} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.57, -Math.PI]} />
        <mesh geometry={nodes.instance_2003.geometry} material={materials.Chris_Shirt} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.57, -Math.PI]} />
        <mesh geometry={nodes.instance_2004.geometry} material={materials.Chris_Skin} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.57, -Math.PI]} />
        <mesh geometry={nodes.instance_2005.geometry} material={materials.Chris_Shoe_Sole} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.57, -Math.PI]} />
        <mesh geometry={nodes.instance_2006.geometry} material={materials.Chris_Shoe_Sole} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.57, -Math.PI]} />
        <mesh geometry={nodes.instance_2007.geometry} material={materials.Chris_Skin} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.57, -Math.PI]} />
        <mesh geometry={nodes.instance_2008.geometry} material={materials.Chris_Hair} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.57, -Math.PI]} />
        <mesh geometry={nodes.instance_2009.geometry} material={materials.Chris_Shoe_Sole} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.57, -Math.PI]} />
        <mesh geometry={nodes.instance_2010.geometry} material={materials.Chris_Hair} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.57, -Math.PI]} />
        <mesh geometry={nodes.instance_2011.geometry} material={materials.Chris_Skin} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.57, -Math.PI]} />
        <mesh geometry={nodes.instance_2012.geometry} material={materials.Chris_Shoe} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.57, -Math.PI]} />
        <mesh geometry={nodes.instance_2013.geometry} material={materials.Chris_Pants} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.57, -Math.PI]} />
        <mesh geometry={nodes.instance_2014.geometry} material={materials.Chris_Skin} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.57, -Math.PI]} />
      </mesh>
      <mesh geometry={nodes.SketchUp001.geometry} material={materials.material} scale={0.03} />
      <mesh geometry={nodes.Casing.geometry} material={materials['default']} position={[-0.49, 0.71, -1.57]} rotation={[Math.PI / 2, 0, -2.57]} scale={0.08} />
      <mesh geometry={nodes.DialFace.geometry} material={materials['default']} position={[-0.49, 0.71, -1.57]} rotation={[Math.PI / 2, 0, -2.57]} scale={0.08} />
      <mesh geometry={nodes.DialMarker.geometry} material={materials['default']} position={[-0.49, 0.71, -1.57]} rotation={[Math.PI / 2, 0, -2.57]} scale={0.08} />
      <mesh geometry={nodes.Glass.geometry} material={materials['default']} position={[-0.49, 0.71, -1.57]} rotation={[Math.PI / 2, 0, -2.57]} scale={0.08} />
      <mesh geometry={nodes.Selector.geometry} material={materials['default']} position={[-0.49, 0.71, -1.57]} rotation={[Math.PI / 2, 0, -2.57]} scale={0.08} />
      <mesh geometry={nodes.Speaker.geometry} material={materials['default']} position={[-0.49, 0.71, -1.57]} rotation={[Math.PI / 2, 0, -2.57]} scale={0.08} />
      <mesh geometry={nodes.Tunner.geometry} material={materials['default']} position={[-0.49, 0.71, -1.57]} rotation={[Math.PI / 2, 0, -2.57]} scale={0.08} />
      <mesh geometry={nodes.Volume.geometry} material={materials['default']} position={[-0.49, 0.71, -1.57]} rotation={[Math.PI / 2, 0, -2.57]} scale={0.08} />
    </group>
  )
}

useGLTF.preload('/hut5.glb')
