/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState, useRef } from "react";
import { Canvas, useFrame } from '@react-three/fiber'

// GLTF importer
import { useGLTF } from "@react-three/drei";

// Animation
import { useSpring, animated } from '@react-spring/three'

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/airpods_pro_centered.glb");

  // Animation
  const [active, setActive] = useState(false);
  const { scale } = useSpring({ scale: active ? 1.5 : 1 });

//   useFrame((state, delta) => (group.current.rotation.y += 0.001))

//   useFrame(({ clock }) => {
//     const a = clock.getElapsedTime()
//     console.log(a) // the value will be 0 at scene initialization and grow each frame
//     group.current.rotation.y = clock.getElapsedTime()
//   })

  return (
    <animated.group  scale={scale} onClick={() => setActive(!active)} ref={group} {...props} dispose={null}>
      <group
        position={[-2.29, 0, 0.34]}
        rotation={[-Math.PI, 1.29, -Math.PI]}
        scale={0.55}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={nodes.Cube014.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_1.geometry}
          material={nodes.Cube014_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_2.geometry}
          material={nodes.Cube014_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_3.geometry}
          material={nodes.Cube014_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_4.geometry}
          material={nodes.Cube014_4.material}
        />
      </group>
      <group
        position={[2.4, 0, 0.34]}
        rotation={[0, -1.08, 0]}
        scale={[-0.55, 0.55, 0.55]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017.geometry}
          material={nodes.Cube017.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_1.geometry}
          material={nodes.Cube017_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_2.geometry}
          material={nodes.Cube017_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_3.geometry}
          material={nodes.Cube017_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_4.geometry}
          material={nodes.Cube017_4.material}
        />
      </group>
    </animated.group>
  );
}

useGLTF.preload("/airpods_pro_centered.glb");
