/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/base_01.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_1.geometry}
        material={materials["Material.004"]}
        position={[2.15, 1.05, 0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_2.geometry}
        material={materials.Glass}
        position={[-0.62, 1.05, -2.15]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Doorframe.geometry}
        material={materials.Material}
        position={[-2.1, 2.06, -0.92]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.64, 0.12, 0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Doorframe_Cutout.geometry}
        material={nodes.Doorframe_Cutout.material}
        position={[-2.1, 0.1, -1.44]}
      />
      <group position={[-2.1, 0.1, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_1.geometry}
          material={nodes.Cube005_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_2.geometry}
          material={nodes.Cube005_2.material}
        />
      </group>
      <group position={[2.1, 0.1, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_1.geometry}
          material={nodes.Cube003_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_2.geometry}
          material={materials["Inside Wall.001"]}
        />
      </group>
      <group position={[0, 0.1, -2.1]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={nodes.Cube004_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_2.geometry}
          material={nodes.Cube004_2.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor.geometry}
        material={nodes.Floor.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_Ledge_1.geometry}
        material={nodes.Window_Ledge_1.material}
        position={[2.3, 0.9, -2.3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_Ledge_1001.geometry}
        material={nodes.Window_Ledge_1001.material}
        position={[2.3, 3.1, -2.3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Window_Ledge_2.geometry}
        material={nodes.Window_Ledge_2.material}
        position={[2.3, 0.1, -2.3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Neon_Text.geometry}
        material={materials["green neon"]}
        position={[-1.43, 2.03, -2.25]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={0.51}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[-2.15, 0.63, 2.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[-1.74, 2.26, 2.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[0.16, 0.6, 2.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[0.77, 2.44, 2.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[-2.15, 2.98, 1.95]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[-2.15, 0.98, 0.85]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[-2.15, 0.46, 0.32]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[-2.15, 2.34, 0.26]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[-0.63, 3.23, 2.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[-0.47, 0.85, 2.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={nodes.Cube010.material}
        position={[-2.15, 3.18, -0.85]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <group
        position={[-1.28, 0.92, 2.62]}
        rotation={[-Math.PI, 1.54, -Math.PI]}
        scale={[0.27, 0.89, 0.45]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_3.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_4.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_5.geometry}
          material={materials["Material.020"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_6.geometry}
          material={materials["Material.016"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_7.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_8.geometry}
          material={materials["Material.023"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_9.geometry}
          material={materials["Material.024"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bolt010.geometry}
          material={materials["Material.011"]}
          position={[-1.35, 1.14, 1.05]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.13, 0.08, 0.04]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_1.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011.geometry}
          material={materials["Material.007"]}
          position={[-1.66, -0.03, -0.54]}
          scale={[0.08, 0.01, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder012.geometry}
          material={materials["Material.008"]}
          position={[-1.66, -0.03, -0.42]}
          scale={[0.08, 0.01, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder020.geometry}
          material={materials["Material.006"]}
          position={[-1.2, -0.03, 0.44]}
          rotation={[-0.02, 0.05, 0.14]}
          scale={[0.06, 0.01, 0.04]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder029.geometry}
          material={materials["Material.009"]}
          position={[-1.67, -0.03, 0.83]}
          rotation={[-0.02, 0.05, 0.14]}
          scale={[0.06, 0.01, 0.04]}
        />
        <group position={[-1.56, -0.03, -0.74]} scale={[0.07, 0.01, 0.04]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder043.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder043_1.geometry}
            material={materials["Material.015"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text.geometry}
          material={materials["Material.021"]}
          position={[-1.39, 1.02, -0.78]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.32, 0.52, 0.14]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text001_1.geometry}
          material={materials["Material.025"]}
          position={[-0.45, 0.56, 0]}
          rotation={[1.74, -0.26, 1.83]}
          scale={[0.42, 0.68, 0.24]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text002.geometry}
          material={materials["Material.019"]}
          position={[-1.42, 1.11, -0.76]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.07, 0.11, 0.03]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text003.geometry}
          material={materials["Material.018"]}
          position={[-1.4, 1, 0.36]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.07, 0.11, 0.03]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text004.geometry}
          material={nodes.Text004.material}
          position={[-0.3, -0.55, 1.08]}
          rotation={[1.33, 0.71, -0.32]}
          scale={[0.18, 0.14, 0.13]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text005.geometry}
          material={nodes.Text005.material}
          position={[1.1, -0.2, -1.07]}
          rotation={[1.33, 0.7, 2.82]}
          scale={[0.19, 0.14, 0.13]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text006.geometry}
          material={materials["Material.027"]}
          position={[-0.6, 0.27, 0.01]}
          rotation={[1.74, -0.26, 1.83]}
          scale={[0.14, 0.23, 0.08]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/base_01.glb");