/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\hut.glb
*/
import { useRef, Suspense } from 'react';
import { useLoader, useFrame } from '@react-three/fiber';
import { useGLTF, SpotLight, useVideoTexture, useTexture, useAspect } from '@react-three/drei';
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { easing } from 'maath'

// import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
// import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass'
import Effects from './Effects'


function VideoMaterial({ url }) {
    const texture = useVideoTexture(url)
    return <meshBasicMaterial map={texture} toneMapped={false} />
}

function FallbackMaterial({ url }) {
    const texture = useTexture(url)
    return <meshBasicMaterial map={texture} toneMapped={false} />
}


export default function HutModel() {
    const group = useRef();
    const { nodes, materials } = useGLTF("./hut6.glb");

    const spotlight_01 = useRef();
    const spotlight_02 = useRef();

    const billboard_screen_01 = useRef();
    const billboard_screen_02 = useRef();

    const toggle_light = (light_ref) => {
        light_ref.current.distance = light_ref.current.intensity == 0 ? 5 : 0;

        light_ref.current.intensity = light_ref.current.intensity == 0 ? 5 : 0;
    }

    const size = useAspect(1800, 1000)


    return (
        <group dispose={null}>
            <group scale={0.03}>
                <group position={[-58, 113, -60]} onClick={() => toggle_light(spotlight_02)} >
                    <SpotLight ref={spotlight_02} penumbra={1} distance={5} angle={0.7} anglePower={4} intensity={3} position={[3, 84, 14]}>

                    </SpotLight>
                    <mesh geometry={nodes.group_1.geometry} material={materials['Metal_Embossed.001']} />
                    <mesh geometry={nodes.group_2.geometry} material={materials['Color_A04.001']} position={[0.5, 0.5, -2]} />
                    <mesh geometry={nodes.group_3.geometry} material={materials['Color_G03.001']} position={[1, 1, -2.5]} />
                    <mesh geometry={nodes.group_3001.geometry} material={materials['Color_G03.001']} position={[1, 1, -2.5]} />
                </group>

                {/* Halfpipe Spotlight */}
                <group position={[-58.93, 120, -44.25]}>
                    <mesh geometry={nodes.group_21.geometry} material={materials['material.001']} position={[0, 72, 0]} />
                    <mesh geometry={nodes.group_22.geometry} material={materials['material.001']} position={[2, 0, -8]} />
                </group>

                {/* Pipes */}
                <group position={[-66, 6, 66]}>
                    <mesh geometry={nodes.group_24.geometry} material={materials['material.001']} position={[1, 15.69, -1]} />
                    <mesh geometry={nodes.group_25.geometry} material={materials['material.001']} position={[0, 84, -54]} />
                    <mesh geometry={nodes.group_26.geometry} material={materials['material.001']} position={[96, 0, 0]} />
                    <mesh geometry={nodes.group_27.geometry} material={materials['material.001']} position={[0, 84, -18]} />
                </group>

                {/* Bricks */}
                <group position={[-61, 7.44, 62]}>
                    <group position={[0, 0, -35.95]}>
                        <mesh geometry={nodes.group_14.geometry} material={materials['material.001']} position={[0, 15.11, -53.27]} />
                        <mesh geometry={nodes.group_15.geometry} material={materials['material.001']} position={[0, 8.28, -6]} />
                        <mesh geometry={nodes.group_16.geometry} material={materials['material.001']} position={[0, 3, -81.05]} />
                        <mesh geometry={nodes.group_17.geometry} material={materials['material.001']} position={[0, 99.91, -81.05]} />
                        <mesh geometry={nodes.group_18.geometry} material={materials['material.001']} position={[0, 58.72, -63.99]} />
                        <mesh geometry={nodes.group_19.geometry} material={materials['material.001']} position={[0, 39.4, -23.73]} />
                    </group>
                    <group position={[0, 26.86, 0]}>
                        <mesh geometry={nodes.group_10.geometry} material={materials['material.001']} position={[98.27, 53.81, 0]} rotation={[0, 1.57, 0]} />
                        <mesh geometry={nodes.group_11.geometry} material={materials['material.001']} position={[58.01, 73.14, 0]} rotation={[0, 1.57, 0]} />
                        <mesh geometry={nodes.group_12.geometry} material={materials['material.001']} position={[68.73, 29.53, 0]} rotation={[0, 1.57, 0]} />
                        <mesh geometry={nodes.group_6.geometry} material={materials['material.001']} position={[6, 3, 0]} rotation={[0, 1.57, 0]} />
                        <mesh geometry={nodes.group_7.geometry} material={materials['material.001']} position={[6, 53.81, 0]} rotation={[0, 1.57, 0]} />
                        <mesh geometry={nodes.group_8.geometry} material={materials['material.001']} position={[40.95, 17.41, 0]} rotation={[0, 1.57, 0]} />
                        <mesh geometry={nodes.group_9.geometry} material={materials['material.001']} position={[116, 22.7, 0]} rotation={[0, 1.57, 0]} />
                    </group>
                </group>

                {/* Billboard 02 */}
                <group position={[50.6, 157.24, -41.98]} rotation={[Math.PI, 0, 0]} scale={[1.1, 1.33, 1.5]}>
                    <mesh geometry={nodes.group_41.geometry} material={materials['material.001']} />
                    <mesh geometry={nodes.group_41001.geometry} material={materials['material.001']} />
                    <mesh geometry={nodes.group_42.geometry} material={materials['material.001']} position={[1, 24, -1]} />
                    <mesh geometry={nodes.group_43.geometry} material={materials['material.001']} position={[1, 24, -33]} />

                    <group position={[3.5, 12, -18]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[0.9, 1.05, 0]}>
                        <mesh scale={size}>
                            <planeGeometry />
                            <Suspense fallback={<FallbackMaterial url="10.jpg" />}>
                                <VideoMaterial url="world.mp4" />
                            </Suspense>
                        </mesh>
                    </group>


                </group>

                {/* Poster 01*/}
                <group position={[21.05, 39.53, 54]}>
                    <mesh geometry={nodes.group_46.geometry} material={materials['material.001']} />
                    <mesh geometry={nodes.group_46001.geometry} material={materials['material.001']} />
                    <mesh geometry={nodes.group_47.geometry} material={materials['Color_M00.001']} position={[1, 1, -1]} />
                </group>

                {/* Poster 02*/}
                <group position={[-54, 43.6, -15.41]} rotation={[-Math.PI / 2, -1.57, 0]} scale={1.27}>
                    <mesh geometry={nodes.group_46002.geometry} material={materials['material.001']} />
                    <mesh geometry={nodes.group_46003.geometry} material={materials['material.001']} />
                    <mesh geometry={nodes.group_47001.geometry} material={materials['Color_M00.001']} position={[1, 1, -1]} />
                </group>

                {/* Matchstick light */}
                <group position={[150.56, 0, -63.77]}>
                    <group position={[5.19, 77.52, -7.95]} rotation={[0, -0.96, 0]} onClick={() => toggle_light(spotlight_01)} >
                        <SpotLight ref={spotlight_01} penumbra={1} distance={5} angle={0.7} anglePower={4} intensity={3} position={[3.2, 11, 1]}>

                        </SpotLight>
                        <mesh geometry={nodes.group_1001.geometry} material={materials['Metal_Embossed.001']} />
                        <mesh geometry={nodes.group_2001.geometry} material={materials['Color_A04.001']} position={[0.5, 0.5, -2]} />
                        <mesh geometry={nodes.group_3002.geometry} material={materials['Color_G03.001']} position={[1, 1, -2.5]} />
                        <mesh geometry={nodes.group_3003.geometry} material={materials['Color_G03.001']} position={[1, 1, -2.5]} />
                    </group>
                    <group position={[0, 0, -4.9]} rotation={[0, -0.96, 0]}>
                        <mesh geometry={nodes.group_55.geometry} material={materials['Wood_Veneer_02.001']} />
                        <group position={[0, 84, 0]}>
                            <mesh geometry={nodes.ID465.geometry} material={materials['Translucent_Glass_Gold.001']} />
                            <mesh geometry={nodes.ID465_1.geometry} material={materials['Translucent_Glass_Gray.001']} />
                        </group>
                    </group>
                </group>

                {/* Bar */}
                <group position={[-53.5, 0, -48]}>
                    <mesh geometry={nodes.group_58.geometry} material={materials['Color_C04.001']} position={[0, 24, 6]} />
                    <mesh geometry={nodes.group_59.geometry} material={materials['Color_C04.001']} position={[-0.5, 0, 6]}>
                        <mesh geometry={nodes.group_60.geometry} material={materials['Color_M02.001']} position={[24.5, 24.5, -35]} />
                    </mesh>
                    <mesh geometry={nodes.group_59001.geometry} material={materials['Color_C04.001']} position={[-0.5, 0, 6]} />
                </group>

                {/* Billboard 01 */}
                <group position={[51, 148, 17.21]} rotation={[Math.PI, 0, 0]}>
                    <mesh geometry={nodes.group_63.geometry} material={materials['material.001']} />
                    <mesh geometry={nodes.group_63001.geometry} material={materials['material.001']} />
                    <mesh geometry={nodes.group_64.geometry} material={materials['material.001']} position={[1, 24, -1]} />
                    <mesh geometry={nodes.group_65.geometry} material={materials['material.001']} position={[1, 24, -33]} />

                    <mesh geometry={nodes.group_66.geometry} material={materials['material.001']} position={[3, 1, -1]} >
                        <Suspense fallback={<FallbackMaterial url="10.jpg" />}>
                            <VideoMaterial url="static.mp4" />
                        </Suspense>
                    </mesh>

                    {/* 
                    <group position={[3.75, 12, -18]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[0.9, 1.05, 0]}>

                        <mesh scale={size}>
                            <planeGeometry />
                            <Suspense fallback={<FallbackMaterial url="10.jpg" />}>
                                <VideoMaterial url="static.mp4" />
                            </Suspense>
                        </mesh>
                    </group> */}


                    <mesh ref={billboard_screen_01} geometry={nodes.group_66.geometry} material={materials['material.001']} position={[3, 1, -1]} />
                </group>

                {/* Walls and Stools and Shelf*/}
                <group position={[0, 0, 0]}>
                    <mesh geometry={nodes.group_28.geometry} material={materials['material.001']} position={[-54, 47.69, 37.04]} />
                    <mesh geometry={nodes.group_29.geometry} material={materials['material.001']} position={[57, 0, 51]} />
                    <mesh geometry={nodes.group_30.geometry} material={materials['material.001']} position={[44.7, 18, -80.4]} rotation={[0, -0.14, Math.PI]} />
                    <mesh geometry={nodes.group_31.geometry} material={materials['material.001']} position={[57, 0, -13.94]} />
                    <mesh geometry={nodes.group_32.geometry} material={materials['material.001']} position={[55, 0, 21.92]} />
                    <mesh geometry={nodes.group_33.geometry} material={materials['material.001']} position={[-8.93, 18, -77.52]} rotation={[0, -0.14, Math.PI]} />
                    <mesh geometry={nodes.group_34.geometry} material={materials['material.001']} position={[57, 0, 19]} />
                    <mesh geometry={nodes.group_35.geometry} material={materials['material.001']} position={[54, 0, -54]} />
                    <mesh geometry={nodes.group_36.geometry} material={materials['material.001']} position={[56, 0, 54]} />
                    <mesh geometry={nodes.group_37.geometry} material={materials['material.001']} position={[55, 0, -21.63]} />
                    <mesh geometry={nodes.group_38.geometry} material={materials['material.001']} position={[20.56, 18, -78.52]} rotation={[0, 0.08, Math.PI]} />
                </group>

                {/* Backwall and artifacts */}
                <group position={[-60, 0, 60]}>
                    <mesh geometry={nodes.ID266.geometry} material={materials['Color_M02.001']} />
                    <mesh geometry={nodes.ID266_1.geometry} material={materials['Translucent_Glass_Blue.001']} />
                </group>
                <group position={[-60, 0, 60]}>
                    <mesh geometry={nodes.ID276.geometry} material={materials['Translucent_Glass_Blue.001']} />
                    <mesh geometry={nodes.ID276_1.geometry} material={materials['Color_I02.001']} />
                </group>
                <group position={[-60, 0, 60]}>
                    <mesh geometry={nodes.ID284.geometry} material={materials['Color_M02.001']} />
                    <mesh geometry={nodes.ID284_1.geometry} material={materials['Translucent_Glass_Blue.001']} />
                </group>

                {/* Halfpipe and Misc*/}
                <group position={[0, 0, 0]}>
                    <mesh geometry={nodes.group_48.geometry} material={materials['Color_M03.001']} position={[56.94, 73.93, -60.1]} />
                    <mesh geometry={nodes.group_48001.geometry} material={materials['Color_M03.001']} position={[56.94, 73.93, -60.1]} />
                    <mesh geometry={nodes.group_50.geometry} material={materials['material.001']} position={[-54, 82, -58]} />
                    <mesh geometry={nodes.group_51.geometry} material={materials['material.001']} position={[58, 82.03, 54]} />
                    <mesh geometry={nodes.group_61.geometry} material={materials['material.001']} position={[-49.56, 120, 48]} scale={[1, 0.6, 1]} />
                    <mesh geometry={nodes.group_61001.geometry} material={materials['Wood_Veneer_02_0.001']} position={[-49.56, 120, 48]} scale={[1, 0.6, 1]} />
                    <mesh geometry={nodes.group_61002.geometry} material={materials['Color_C06.001']} position={[-49.56, 120, 48]} scale={[1, 0.6, 1]} />
                    <mesh geometry={nodes.group_61003.geometry} material={materials['material.001']} position={[-49.56, 120, 48]} scale={[1, 0.6, 1]} />


                    <group position={[-49.56, 120, 48]} scale={[1, 0.6, 1]}>
                        <mesh geometry={nodes.ID544.geometry} material={materials['Wood_Veneer_02_0.001']} />
                        <mesh geometry={nodes.ID544_1.geometry} material={materials['Metal_Silver.001']} />
                    </group>
                    <mesh geometry={nodes.group_61005.geometry} material={materials['Metal_Silver.001']} position={[-49.56, 120, 48]} scale={[1, 0.6, 1]} />
                    <mesh geometry={nodes.group_61006.geometry} material={materials['Metal_Silver.001']} position={[-49.56, 120, 48]} scale={[1, 0.6, 1]} />
                    <mesh geometry={nodes.group_61007.geometry} material={materials['Metal_Silver.001']} position={[-49.56, 120, 48]} scale={[1, 0.6, 1]} />
                    <mesh geometry={nodes.group_67.geometry} material={materials['material.001']} position={[16, 0, 53]} />
                    <mesh geometry={nodes.group_68.geometry} material={materials['Color_D01.001']} position={[54.42, 67.79, -60]} />
                    <mesh geometry={nodes.instance_0.geometry} material={materials['material.001']} position={[58.56, 90.08, -60]} rotation={[Math.PI / 2, 0, Math.PI]} />
                    <mesh geometry={nodes.instance_0001.geometry} material={materials['material.001']} position={[58.56, 90.08, -60]} rotation={[Math.PI / 2, 0, Math.PI]} />
                    <mesh geometry={nodes.instance_0002.geometry} material={materials['material.001']} position={[58.56, 90.08, -60]} rotation={[Math.PI / 2, 0, Math.PI]} />
                    <mesh geometry={nodes.instance_1.geometry} material={materials['material.001']} position={[60, 90, -21.47]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
                    <mesh geometry={nodes.instance_1001.geometry} material={materials['material.001']} position={[60, 90, -21.47]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
                    <mesh geometry={nodes.instance_1002.geometry} material={materials['material.001']} position={[60, 90, -21.47]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
                    <mesh geometry={nodes.instance_1003.geometry} material={materials['material.001']} position={[60, 90, -21.47]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
                    <mesh geometry={nodes.instance_2.geometry} material={materials['Chris_Shirt.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.67, -Math.PI]} />
                    <mesh geometry={nodes.instance_2001.geometry} material={materials['Chris_Shirt.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.67, -Math.PI]} />
                    <mesh geometry={nodes.instance_2002.geometry} material={materials['Chris_Shoe.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.67, -Math.PI]} />
                    <mesh geometry={nodes.instance_2003.geometry} material={materials['Chris_Shirt.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.67, -Math.PI]} />
                    <mesh geometry={nodes.instance_2004.geometry} material={materials['Chris_Skin.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.67, -Math.PI]} />
                    <mesh geometry={nodes.instance_2005.geometry} material={materials['Chris_Shoe_Sole.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.67, -Math.PI]} />
                    <mesh geometry={nodes.instance_2006.geometry} material={materials['Chris_Shoe_Sole.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.67, -Math.PI]} />
                    <mesh geometry={nodes.instance_2007.geometry} material={materials['Chris_Skin.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.67, -Math.PI]} />
                    <mesh geometry={nodes.instance_2008.geometry} material={materials['Chris_Hair.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.67, -Math.PI]} />
                    <mesh geometry={nodes.instance_2009.geometry} material={materials['Chris_Shoe_Sole.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.67, -Math.PI]} />
                    <mesh geometry={nodes.instance_2010.geometry} material={materials['Chris_Hair.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.67, -Math.PI]} />
                    <mesh geometry={nodes.instance_2011.geometry} material={materials['Chris_Skin.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.67, -Math.PI]} />
                    <mesh geometry={nodes.instance_2012.geometry} material={materials['Chris_Shoe.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.67, -Math.PI]} />
                    <mesh geometry={nodes.instance_2013.geometry} material={materials['Chris_Pants.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.67, -Math.PI]} />
                    <mesh geometry={nodes.instance_2014.geometry} material={materials['Chris_Skin.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.67, -Math.PI]} />
                </group>
            </group>

            {/* Radio */}
            <group>
                <mesh geometry={nodes.Casing.geometry} material={materials['default']} position={[-0.49, 0.71, -1.57]} rotation={[Math.PI / 2, 0, -2.57]} scale={0.08} />
                <mesh geometry={nodes.DialFace.geometry} material={materials['default']} position={[-0.49, 0.71, -1.57]} rotation={[Math.PI / 2, 0, -2.57]} scale={0.08} />
                <mesh geometry={nodes.DialMarker.geometry} material={materials['default']} position={[-0.49, 0.71, -1.57]} rotation={[Math.PI / 2, 0, -2.57]} scale={0.08} />
                <mesh geometry={nodes.Glass.geometry} material={materials['default']} position={[-0.49, 0.71, -1.57]} rotation={[Math.PI / 2, 0, -2.57]} scale={0.08} />
                <mesh geometry={nodes.Selector.geometry} material={materials['default']} position={[-0.49, 0.71, -1.57]} rotation={[Math.PI / 2, 0, -2.57]} scale={0.08} />
                <mesh geometry={nodes.Speaker.geometry} material={materials['default']} position={[-0.49, 0.71, -1.57]} rotation={[Math.PI / 2, 0, -2.57]} scale={0.08} />
                <mesh geometry={nodes.Tunner.geometry} material={materials['default']} position={[-0.49, 0.71, -1.57]} rotation={[Math.PI / 2, 0, -2.57]} scale={0.08} />
                <mesh geometry={nodes.Volume.geometry} material={materials['default']} position={[-0.49, 0.71, -1.57]} rotation={[Math.PI / 2, 0, -2.57]} scale={0.08} />
            </group>
        </group>
    );
}
