/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\hut.glb
*/
import { useRef, Suspense } from 'react';
import { useLoader, useFrame } from '@react-three/fiber';
import { useGLTF, SpotLight, useVideoTexture, useTexture, useAspect } from '@react-three/drei';
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { easing } from 'maath'
import { useSpring, animated, config } from '@react-spring/three'

// import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
// import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass'
import Effects from './Effects'



export default function HutModel(props) {

    const { nodes, materials } = useGLTF("./py.glb");

    const mesh_ref = useRef();

    useFrame(({ clock }) => {
        const a = clock.getElapsedTime();
        mesh_ref.current.rotation.y = a;
    });

    const open_github = () => {
        window.open("https://github.com/MaxwellVolz")
    }

    return (
        <group {...props} scale={.35}>
            {/* <animated.mesh scale={scale} onClick={() => open_github()} ref={py_logo}> */}
            <group ref={mesh_ref} dispose={null} rotation={[.1, 0, 0]} >
                <mesh geometry={nodes.D.geometry} material={materials.orange} position={[-0.03, 0.29, 0]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={1.76} />
                <mesh geometry={nodes.Top_snake.geometry} material={materials.blue} position={[0.01, -0.08, 0]} rotation={[Math.PI / 2, 0, 0]} scale={1.76} />
            </group>
            {/* </animated.mesh > */}
        </group >
    );
}
