/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\hut.glb
*/
import { useRef, Suspense } from 'react';
import { useLoader, useFrame } from '@react-three/fiber';
import { useGLTF, SpotLight, useVideoTexture, useTexture, useAspect } from '@react-three/drei';
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { easing } from 'maath'
import { useSpring, animated, config } from '@react-spring/three'

// import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
// import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass'
import Effects from './Effects'



export default function HutModel() {

    const { nodes, materials } = useGLTF('/maxtower_base.glb')

    return (
        <group dispose={null}>
            <group scale={0.03}>
                <mesh geometry={nodes.group_0.geometry} material={materials['material.001']} position={[-120, 0, 120]} />
                <mesh geometry={nodes.group_1.geometry} material={materials['Grass_Dark_Green.001']} position={[-120, 3, 120]} />
                <group position={[-120, 0, 120]}>
                    <mesh geometry={nodes.ID27.geometry} material={materials['Groundcover_Wood_Mix.001']} />
                    <mesh geometry={nodes.ID27_1.geometry} material={materials['Vegetation_Bark_Ponderosa.001']} />
                </group>
            </group>
        </group>
    );
}
