/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\hut.glb
*/
import { useRef, Suspense } from 'react';
import { useLoader, useFrame } from '@react-three/fiber';
import { useGLTF, SpotLight, useVideoTexture, useTexture, useAspect } from '@react-three/drei';
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { easing } from 'maath'
import { useSpring, animated, config } from '@react-spring/three'

// import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
// import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass'
import Effects from './Effects'



export default function HutModel() {

    const { nodes, materials } = useGLTF('/maxtower_base.glb')

    return (
        <group dispose={null}>
            <group scale={0.03}>
                <group position={[-44.06, 88.16, 6]}>
                    <group position={[8.73, 216, -116]} rotation={[Math.PI / 2, 0, 0]}>
                        <mesh geometry={nodes.instance_0.geometry} material={materials.noon_3} position={[-1.45, 0, -11.48]} />
                        <mesh geometry={nodes.instance_0001.geometry} material={materials.noon_3} position={[-1.45, 0, -11.48]} />
                        <mesh geometry={nodes.instance_0002.geometry} material={materials.noon_3} position={[-1.45, 0, -11.48]} />
                        <mesh geometry={nodes.instance_1.geometry} material={materials.noon_3} position={[-0.02, 0, 0]} />
                        <mesh geometry={nodes.instance_1001.geometry} material={materials.noon_3} position={[-0.02, 0, 0]} />
                        <mesh geometry={nodes.instance_1002.geometry} material={materials.noon_3} position={[-0.02, 0, 0]} />
                        <mesh geometry={nodes.instance_1003.geometry} material={materials.noon_3} position={[-0.02, 0, 0]} />
                        <mesh geometry={nodes.instance_1004.geometry} material={materials.noon_3} position={[-0.02, 0, 0]} />
                        <mesh geometry={nodes.instance_1005.geometry} material={materials.noon_3} position={[-0.02, 0, 0]} />
                        <mesh geometry={nodes.instance_1006.geometry} material={materials.noon_3} position={[-0.02, 0, 0]} />
                        <mesh geometry={nodes.instance_1007.geometry} material={materials.noon_3} position={[-0.02, 0, 0]} />
                        <mesh geometry={nodes.instance_1008.geometry} material={materials.noon_3} position={[-0.02, 0, 0]} />
                        <mesh geometry={nodes.instance_1009.geometry} material={materials.noon_3} position={[-0.02, 0, 0]} />
                    </group>
                    <group position={[48.06, 115.62, -10.11]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
                        <mesh geometry={nodes.instance_2.geometry} material={materials.noon_3} position={[-1.49, 0, -11.83]} />
                        <mesh geometry={nodes.instance_2001.geometry} material={materials.noon_3} position={[-1.49, 0, -11.83]} />
                        <mesh geometry={nodes.instance_2002.geometry} material={materials.noon_3} position={[-1.49, 0, -11.83]} />
                        <mesh geometry={nodes.instance_2003.geometry} material={materials.noon_3} position={[-1.49, 0, -11.83]} />
                        <mesh geometry={nodes.instance_2004.geometry} material={materials.noon_3} position={[-1.49, 0, -11.83]} />
                        <mesh geometry={nodes.instance_3.geometry} material={materials.noon_3} position={[0.21, 2, -0.08]} />
                        <mesh geometry={nodes.instance_3001.geometry} material={materials.noon_3} position={[0.21, 2, -0.08]} />
                        <mesh geometry={nodes.instance_3002.geometry} material={materials.noon_3} position={[0.21, 2, -0.08]} />
                        <mesh geometry={nodes.instance_3003.geometry} material={materials.noon_3} position={[0.21, 2, -0.08]} />
                        <mesh geometry={nodes.instance_3004.geometry} material={materials.noon_3} position={[0.21, 2, -0.08]} />
                        <mesh geometry={nodes.instance_3005.geometry} material={materials.noon_3} position={[0.21, 2, -0.08]} />
                        <mesh geometry={nodes.instance_3006.geometry} material={materials.noon_3} position={[0.21, 2, -0.08]} />
                        <mesh geometry={nodes.instance_3007.geometry} material={materials.noon_3} position={[0.21, 2, -0.08]} />
                        <mesh geometry={nodes.instance_3008.geometry} material={materials.noon_3} position={[0.21, 2, -0.08]} />
                    </group>
                    <group position={[120, -6.66, 2]} rotation={[Math.PI / 2, 0, 0]}>
                        <mesh geometry={nodes.instance_4.geometry} material={materials.noon_3} position={[1.15, 0, -14.17]} />
                        <mesh geometry={nodes.instance_4001.geometry} material={materials.noon_3} position={[1.15, 0, -14.17]} />
                        <mesh geometry={nodes.instance_4002.geometry} material={materials.noon_3} position={[1.15, 0, -14.17]} />
                        <mesh geometry={nodes.instance_4003.geometry} material={materials.noon_3} position={[1.15, 0, -14.17]} />
                        <mesh geometry={nodes.instance_4004.geometry} material={materials.noon_3} position={[1.15, 0, -14.17]} />
                        <mesh geometry={nodes.instance_5.geometry} material={materials.noon_3} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5001.geometry} material={materials.noon_3} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5002.geometry} material={materials.noon_3} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5003.geometry} material={materials.noon_3} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5004.geometry} material={materials.noon_3} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5005.geometry} material={materials.noon_3} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5006.geometry} material={materials.noon_3} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5007.geometry} material={materials.noon_3} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5008.geometry} material={materials.noon_3} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5009.geometry} material={materials.noon_3} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5010.geometry} material={materials.noon_3} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5011.geometry} material={materials.noon_3} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5012.geometry} material={materials.noon_3} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5013.geometry} material={materials.noon_3} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5014.geometry} material={materials.noon_3} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5015.geometry} material={materials.noon_3} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5016.geometry} material={materials.noon_3} position={[-0.69, 0, 0]} />
                    </group>
                    <mesh geometry={nodes.group_5.geometry} material={materials.noon1} position={[32.06, -82.16, -2]} />
                    <mesh geometry={nodes.group_6.geometry} material={materials.noon1} position={[44.06, 37.84, -6]} />
                    <mesh geometry={nodes.group_7.geometry} material={materials.noon1} position={[-69.94, 157.84, -116]} />
                </group>
                <mesh geometry={nodes.group_0.geometry} material={materials.material} position={[-120, 0, 120]} />
                <mesh geometry={nodes.group_8.geometry} material={materials.Grass_Dark_Green} position={[-120, 3, 120]} />
                <group position={[-120, 0, 120]}>
                    <mesh geometry={nodes.ID362.geometry} material={materials.Groundcover_Wood_Mix} />
                    <mesh geometry={nodes.ID362_1.geometry} material={materials.Vegetation_Bark_Ponderosa} />
                </group>
            </group>
        </group>
    );
}
