/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\hut.glb
*/
import { useRef, Suspense, useState } from 'react';
import { useLoader, useFrame } from '@react-three/fiber';
import { useGLTF, SpotLight, useVideoTexture, useTexture, useAspect } from '@react-three/drei';
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { easing } from 'maath'
import { useSpring, animated, config } from '@react-spring/three'

// import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
// import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass'
import Effects from './Effects'

import ResumePDF from '../mvolz_resume.pdf'


export default function HutModel() {

    const { nodes, materials } = useGLTF('/maxtower_02.glb')
    const [active, setActive] = useState(false);


    const { scale } = useSpring({
        scale: active ? 1 : 1,
        config: config.wobbly
    });

    const download_pdf = () => {
        window.open(ResumePDF)
    }

    const open_github = () => {
        window.open("https://github.com/MaxwellVolz")
    }

    useFrame(({ clock }) => {
        const a = clock.getElapsedTime();
        let decimals = a % 1

    });

    return (
        <group dispose={null}>
            <group scale={0.03}>
                <group position={[6, 126, -6]}>
                    <group position={[52.99, 18.1, -94.57]}>
                        <mesh geometry={nodes.group_2.geometry} material={materials.Color_M06} position={[11, 0, 0]} />
                        <mesh geometry={nodes.group_3.geometry} material={materials.Color_M06} position={[15, 1, -2]} />
                        <mesh geometry={nodes.group_4.geometry} material={materials.Color_M06} position={[15, 3, 0]} />
                        <group position={[15, 3, 0]}>
                            <mesh geometry={nodes.ID28.geometry} material={materials.Color_M06} />
                            <mesh geometry={nodes.ID28_1.geometry} material={materials.Color_M09} />
                        </group>
                        <mesh geometry={nodes.group_4002.geometry} material={materials.Color_M06} position={[15, 3, 0]} />
                    </group>
                    <group position={[0, 0.1, 0]}>
                        <mesh geometry={nodes.group_17.geometry} material={materials.noon_5} />
                        <mesh geometry={nodes.group_18.geometry} material={materials.noon_5} position={[4, 0, -51.99]} />
                        <mesh geometry={nodes.group_19.geometry} material={materials.noon_5} position={[4, 0, 0]} />
                        <mesh geometry={nodes.group_20.geometry} material={materials.noon_5} position={[4, 0, -51.99]} />
                        <mesh geometry={nodes.group_21.geometry} material={materials.noon_5} position={[4, 0, -30]} />
                        <mesh geometry={nodes.group_22.geometry} material={materials.noon_5} position={[4, 15, -51.99]} />
                        <mesh geometry={nodes.group_23.geometry} material={materials.noon_5} position={[4, 15, -30]} />
                    </group>
                    <group position={[60, 0.1, 0]}>
                        <mesh geometry={nodes.group_7.geometry} material={materials.noon1} />
                        <group onClick={() => download_pdf()} >
                            <mesh geometry={nodes.group_8.geometry} material={materials.noon_5} position={[45.12, 12.36, -2.88]} />
                            <mesh geometry={nodes.instance_1.geometry} material={materials.noon_3} position={[3.78, 17.55, -26.55]} scale={[1.19, 1.19, 2.07]} />
                            <mesh geometry={nodes.instance_1001.geometry} material={materials.noon_3} position={[3.78, 17.55, -26.55]} scale={[1.19, 1.19, 2.07]} />
                            <mesh geometry={nodes.instance_1002.geometry} material={materials.noon_3} position={[3.78, 17.55, -26.55]} scale={[1.19, 1.19, 2.07]} />
                            <mesh geometry={nodes.instance_1003.geometry} material={materials.noon_3} position={[3.78, 17.55, -26.55]} scale={[1.19, 1.19, 2.07]} />
                            <mesh geometry={nodes.instance_1004.geometry} material={materials.noon_3} position={[3.78, 17.55, -26.55]} scale={[1.19, 1.19, 2.07]} />
                            <mesh geometry={nodes.instance_1005.geometry} material={materials.noon_3} position={[3.78, 17.55, -26.55]} scale={[1.19, 1.19, 2.07]} />
                            <mesh geometry={nodes.instance_1006.geometry} material={materials.noon_3} position={[3.78, 17.55, -26.55]} scale={[1.19, 1.19, 2.07]} />
                            <mesh geometry={nodes.instance_2.geometry} material={materials.noon_3} position={[2.67, 17.49, -7.73]} scale={1.3} />
                            <mesh geometry={nodes.instance_2001.geometry} material={materials.noon_3} position={[2.67, 17.49, -7.73]} scale={1.3} />
                            <mesh geometry={nodes.instance_2002.geometry} material={materials.noon_3} position={[2.67, 17.49, -7.73]} scale={1.3} />
                            <mesh geometry={nodes.instance_2003.geometry} material={materials.noon_3} position={[2.67, 17.49, -7.73]} scale={1.3} />
                            <mesh geometry={nodes.instance_2004.geometry} material={materials.noon_3} position={[2.67, 17.49, -7.73]} scale={1.3} />
                        </group>

                    </group>
                    <group position={[99.99, 18.1, -83.26]} rotation={[0, 0, -Math.PI]}>
                        <mesh geometry={nodes.group_10.geometry} material={materials.Translucent_Glass_Gray} />
                        <mesh geometry={nodes.group_10001.geometry} material={materials.Translucent_Glass_Gray} />
                        <mesh geometry={nodes.group_11.geometry} material={materials.noon1} position={[1, 2, -1]} />
                        <mesh geometry={nodes.group_12.geometry} material={materials.noon1} position={[57, 2, -1]} />
                        <mesh geometry={nodes.group_13.geometry} material={materials.noon1} position={[57, 2, -21]} />
                        <mesh geometry={nodes.group_14.geometry} material={materials.noon1} position={[1, 2, -21]} />
                        <mesh geometry={nodes.group_15.geometry} material={materials.Translucent_Glass_Gray} position={[0, 12, 0]} />
                        <mesh geometry={nodes.group_15001.geometry} material={materials.Translucent_Glass_Gray} position={[0, 12, 0]} />
                    </group>
                    <mesh geometry={nodes.group_24.geometry} material={materials.noon_2} position={[0.12, 0, 3.71]} />

                </group>
                <group position={[4, 203.78, -4.11]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
                    <mesh geometry={nodes.instance_4.geometry} material={materials.noon_3} position={[-1.49, 0, -11.83]} />
                    <mesh geometry={nodes.instance_4001.geometry} material={materials.noon_3} position={[-1.49, 0, -11.83]} />
                    <mesh geometry={nodes.instance_4002.geometry} material={materials.noon_3} position={[-1.49, 0, -11.83]} />
                    <mesh geometry={nodes.instance_4003.geometry} material={materials.noon_3} position={[-1.49, 0, -11.83]} />
                    <mesh geometry={nodes.instance_4004.geometry} material={materials.noon_3} position={[-1.49, 0, -11.83]} />
                    <mesh geometry={nodes.instance_5.geometry} material={materials.noon_3} position={[0.21, 2, -0.08]} />
                    <mesh geometry={nodes.instance_5001.geometry} material={materials.noon_3} position={[0.21, 2, -0.08]} />
                    <mesh geometry={nodes.instance_5002.geometry} material={materials.noon_3} position={[0.21, 2, -0.08]} />
                    <mesh geometry={nodes.instance_5003.geometry} material={materials.noon_3} position={[0.21, 2, -0.08]} />
                    <mesh geometry={nodes.instance_5004.geometry} material={materials.noon_3} position={[0.21, 2, -0.08]} />
                    <mesh geometry={nodes.instance_5005.geometry} material={materials.noon_3} position={[0.21, 2, -0.08]} />
                    <mesh geometry={nodes.instance_5006.geometry} material={materials.noon_3} position={[0.21, 2, -0.08]} />
                    <mesh geometry={nodes.instance_5007.geometry} material={materials.noon_3} position={[0.21, 2, -0.08]} />
                    <mesh geometry={nodes.instance_5008.geometry} material={materials.noon_3} position={[0.21, 2, -0.08]} />
                </group>
                <mesh geometry={nodes.group_26.geometry} material={materials.noon1} position={[0, 126, 0]} />
            </group>

        </group>




    );
}
