/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\hut.glb
*/
import { useRef, Suspense } from 'react';
import { useLoader, useFrame } from '@react-three/fiber';
import { useGLTF, SpotLight, useVideoTexture, useTexture, useAspect } from '@react-three/drei';
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { easing } from 'maath'
import { useSpring, animated, config } from '@react-spring/three'

// import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
// import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass'
import Effects from './Effects'



export default function HutModel() {

    const { nodes, materials } = useGLTF('/maxtower_base.glb')

    // Assuming you have references to your materials
    const material1 = materials['noon_5.002'];
    // const material2 = materials['Color_F06.002'];

    // Set the opacity for each material (a value between 0 and 1, where 0 is completely transparent and 1 is fully opaque)
    material1.opacity = 0.0;
    // material2.opacity = 0.8;

    // To make the materials render transparent correctly, you also need to enable the transparent property:
    material1.transparent = true;
    // material2.transparent = true;

    // After changing the material properties, you might need to update the meshes to see the changes:
    // mesh1.material.needsUpdate = true;
    // mesh2.material.needsUpdate = true;

    return (
        <group dispose={null}>
            <group scale={0.03}>
                <mesh geometry={nodes.group_0.geometry} material={materials['material.004']} position={[-120, 0, 120]} />
                <mesh geometry={nodes.group_1.geometry} material={materials['Color_G07.002']} position={[-120, 3, 120]} />
                <group position={[-120, 0, 120]}>
                    <mesh geometry={nodes.ID22002.geometry} material={materials['Color_I05.002']} />
                    <mesh geometry={nodes.ID22002_1.geometry} material={nodes.ID22002_1.material} />
                </group>
                <mesh geometry={nodes.group_3.geometry} material={materials['noon_5.002']} position={[27.965, 144.15, -13.34]} />
                <mesh geometry={nodes.group_4.geometry} material={materials['noon_5.002']} position={[85.22, 144.15, -70.595]} />
                <mesh geometry={nodes.group_6.geometry} material={materials['noon_5.002']} position={[36.54, 150.15, -55.05]} />
                <mesh geometry={nodes.group_7.geometry} material={materials['noon_5.002']} position={[0, 126, 0]} />
                <mesh geometry={nodes.group_8.geometry} material={materials['noon_5.002']} position={[-114, 246, 0]} />
                <mesh geometry={nodes.group_9.geometry} material={materials['noon_5.002']} position={[-86.568, 6, 120]} />
            </group>
        </group>
    );
}
