/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\hut.glb
*/
import { useRef, useState } from 'react';
import { useLoader, useFrame, useThree } from '@react-three/fiber';
import { useGLTF, SpotLight, useVideoTexture, useTexture } from '@react-three/drei';
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { easing } from 'maath'
import { useSpring, animated, config } from '@react-spring/three'
// import * as THREE from 'three'
// import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
// import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass'
import Effects from './Effects'

import ResumePDF from '../mvolz_resume.pdf'



function VideoMaterial({ url }) {
    const texture = useVideoTexture(url)
    return <meshBasicMaterial map={texture} toneMapped={false} />
}

function FallbackMaterial({ url }) {
    const texture = useTexture(url)
    return <meshBasicMaterial map={texture} toneMapped={false} />
}


// make it glow - insert in mesh
{/* <meshStandardMaterial emissive={[0.5, 0.5, 0.5]} color={[0, 0, 0]} /> */ }

export default function HutModel(app_state) {
    const group = useRef();
    const { nodes, materials } = useGLTF("./maxtower.glb");


    const spotlight_01 = useRef();
    const spotlight_02 = useRef();
    const light_inside = useRef();

    const garage_door = useRef();
    const js_logo = useRef();
    const py_logo = useRef();

    const [active, setActive] = useState(false);

    const { scale } = useSpring({
        scale: active ? 1 : 1,
        config: config.wobbly
    });

    useFrame(({ clock }) => {
        const a = clock.getElapsedTime();
        let decimals = a % 1

        // garage door
        if (!active && garage_door.current.position.y < 100) garage_door.current.position.y += decimals * .2;
        if (active && garage_door.current.position.y > 0) garage_door.current.position.y -= 3;


        // logos
        js_logo.current.rotation.y = -a
        py_logo.current.rotation.y = a
    });


    const toggle_light = (light_ref) => {
        // light_ref.current.distance = light_ref.current.intensity == 0 ? 0 : 0;
        light_ref.current.intensity = light_ref.current.intensity == 0 ? 1 : 0;
    }

    const download_pdf = () => {
        window.open(ResumePDF)
    }

    const open_github = () => {
        window.open("https://github.com/MaxwellVolz")
    }

    const camera_lookat = () => {
        // useFrame((state, delta) => {
        //     state.camera.lookAt(0, 20, 0)
        // })
        console.log("hey")
    }

    return (
        <group dispose={null}>

            <group scale={0.03}>

                {/* 01 - ABOUT */}
                <group position={[-44.06, 88.16, 6]} onClick={() => camera_lookat()} >
                    <group position={[8.73, 216, -116]} rotation={[Math.PI / 2, 0, 0]}>
                        <mesh geometry={nodes.instance_0.geometry} material={materials['noon_3.002']} position={[-1.45, 0, -11.48]} />
                        <mesh geometry={nodes.instance_0001.geometry} material={materials['noon_3.002']} position={[-1.45, 0, -11.48]} />
                        <mesh geometry={nodes.instance_0002.geometry} material={materials['noon_3.002']} position={[-1.45, 0, -11.48]} />
                        <mesh geometry={nodes.instance_1.geometry} material={materials['noon_3.002']} position={[-0.02, 0, 0]} />
                        <mesh geometry={nodes.instance_1001.geometry} material={materials['noon_3.002']} position={[-0.02, 0, 0]} />
                        <mesh geometry={nodes.instance_1002.geometry} material={materials['noon_3.002']} position={[-0.02, 0, 0]} />
                        <mesh geometry={nodes.instance_1003.geometry} material={materials['noon_3.002']} position={[-0.02, 0, 0]} />
                        <mesh geometry={nodes.instance_1004.geometry} material={materials['noon_3.002']} position={[-0.02, 0, 0]} />
                        <mesh geometry={nodes.instance_1005.geometry} material={materials['noon_3.002']} position={[-0.02, 0, 0]} />
                        <mesh geometry={nodes.instance_1006.geometry} material={materials['noon_3.002']} position={[-0.02, 0, 0]} />
                        <mesh geometry={nodes.instance_1007.geometry} material={materials['noon_3.002']} position={[-0.02, 0, 0]} />
                        <mesh geometry={nodes.instance_1008.geometry} material={materials['noon_3.002']} position={[-0.02, 0, 0]} />
                        <mesh geometry={nodes.instance_1009.geometry} material={materials['noon_3.002']} position={[-0.02, 0, 0]} />
                    </group>
                    <group position={[48.06, 115.62, -10.11]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
                        <mesh geometry={nodes.instance_2.geometry} material={materials['noon_3.002']} position={[-1.49, 0, -11.83]} />
                        <mesh geometry={nodes.instance_2001.geometry} material={materials['noon_3.002']} position={[-1.49, 0, -11.83]} />
                        <mesh geometry={nodes.instance_2002.geometry} material={materials['noon_3.002']} position={[-1.49, 0, -11.83]} />
                        <mesh geometry={nodes.instance_2003.geometry} material={materials['noon_3.002']} position={[-1.49, 0, -11.83]} />
                        <mesh geometry={nodes.instance_2004.geometry} material={materials['noon_3.002']} position={[-1.49, 0, -11.83]} />
                        <mesh geometry={nodes.instance_3.geometry} material={materials['noon_3.002']} position={[0.21, 2, -0.08]} />
                        <mesh geometry={nodes.instance_3001.geometry} material={materials['noon_3.002']} position={[0.21, 2, -0.08]} />
                        <mesh geometry={nodes.instance_3002.geometry} material={materials['noon_3.002']} position={[0.21, 2, -0.08]} />
                        <mesh geometry={nodes.instance_3003.geometry} material={materials['noon_3.002']} position={[0.21, 2, -0.08]} />
                        <mesh geometry={nodes.instance_3004.geometry} material={materials['noon_3.002']} position={[0.21, 2, -0.08]} />
                        <mesh geometry={nodes.instance_3005.geometry} material={materials['noon_3.002']} position={[0.21, 2, -0.08]} />
                        <mesh geometry={nodes.instance_3006.geometry} material={materials['noon_3.002']} position={[0.21, 2, -0.08]} />
                        <mesh geometry={nodes.instance_3007.geometry} material={materials['noon_3.002']} position={[0.21, 2, -0.08]} />
                        <mesh geometry={nodes.instance_3008.geometry} material={materials['noon_3.002']} position={[0.21, 2, -0.08]} />
                    </group>
                    <group position={[120, -6.66, 2]} rotation={[Math.PI / 2, 0, 0]}>
                        <mesh geometry={nodes.instance_4.geometry} material={materials['noon_3.002']} position={[1.15, 0, -14.17]} />
                        <mesh geometry={nodes.instance_4001.geometry} material={materials['noon_3.002']} position={[1.15, 0, -14.17]} />
                        <mesh geometry={nodes.instance_4002.geometry} material={materials['noon_3.002']} position={[1.15, 0, -14.17]} />
                        <mesh geometry={nodes.instance_4003.geometry} material={materials['noon_3.002']} position={[1.15, 0, -14.17]} />
                        <mesh geometry={nodes.instance_4004.geometry} material={materials['noon_3.002']} position={[1.15, 0, -14.17]} />
                        <mesh geometry={nodes.instance_5.geometry} material={materials['noon_3.002']} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5001.geometry} material={materials['noon_3.002']} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5002.geometry} material={materials['noon_3.002']} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5003.geometry} material={materials['noon_3.002']} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5004.geometry} material={materials['noon_3.002']} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5005.geometry} material={materials['noon_3.002']} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5006.geometry} material={materials['noon_3.002']} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5007.geometry} material={materials['noon_3.002']} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5008.geometry} material={materials['noon_3.002']} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5009.geometry} material={materials['noon_3.002']} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5010.geometry} material={materials['noon_3.002']} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5011.geometry} material={materials['noon_3.002']} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5012.geometry} material={materials['noon_3.002']} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5013.geometry} material={materials['noon_3.002']} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5014.geometry} material={materials['noon_3.002']} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5015.geometry} material={materials['noon_3.002']} position={[-0.69, 0, 0]} />
                        <mesh geometry={nodes.instance_5016.geometry} material={materials['noon_3.002']} position={[-0.69, 0, 0]} />
                    </group>
                    <mesh geometry={nodes.group_4.geometry} material={materials['noon1.002']} position={[32.06, -82.16, -2]} />
                    <mesh geometry={nodes.group_5.geometry} material={materials['noon1.002']} position={[44.06, 37.84, -6]} />
                    <mesh geometry={nodes.group_6.geometry} material={materials['noon1.002']} position={[-69.94, 157.84, -116]} />
                </group>

                {/*  */}
                <group position={[-110.17, 246, -2]}>
                    <group position={[80.07, 0.5, -5.76]}>
                        <group position={[2.35, 18, 0]} rotation={[-Math.PI, -1.57, 0]}>
                            <mesh geometry={nodes.group_14.geometry} material={materials['material.002']} position={[0, -8.81, 0]} />
                            <mesh geometry={nodes.group_15.geometry} material={materials['material.002']} position={[1, 2, -1]} />
                            <mesh geometry={nodes.group_16.geometry} material={materials['material.002']} position={[45, 2, -1]} />
                            <mesh geometry={nodes.group_17.geometry} material={materials['material.002']} position={[45, 2, -21]} />
                            <mesh geometry={nodes.group_18.geometry} material={materials['material.002']} position={[1, 2, -21]} />
                        </group>
                        <group position={[21.55, 26.81, -35.9]} rotation={[0, -1.57, 0]} scale={0.7}>
                            <mesh geometry={nodes.group_20.geometry} material={materials['Color_M06.002']} position={[11, 0, 0]} />
                            <mesh geometry={nodes.group_21.geometry} material={materials['Color_M06.002']} position={[15, 1, -2]} />
                            <mesh geometry={nodes.group_22.geometry} material={materials['Color_M06.002']} position={[15, 3.21, 1.05]} rotation={[-0.11, 0, 0]} />
                            <group position={[15, 3.21, 1.05]} rotation={[-0.11, 0, 0]}>
                                <mesh geometry={nodes.ID449001.geometry} material={materials['Color_M06.002']} />
                                <mesh geometry={nodes.ID449001_1.geometry} material={materials['Color_M09.002']} />
                            </group>
                            <mesh geometry={nodes.group_22002.geometry} material={materials['Color_M06.002']} position={[15, 3.21, 1.05]} rotation={[-0.11, 0, 0]} />
                        </group>
                        <group position={[6.1, 26.81, -11.98]}>
                            <group position={[7.37, 2.76, 0]} rotation={[0, 0, -2.99]} scale={1.66}>
                                <mesh geometry={nodes.group_26.geometry} material={materials['Chris_Shoe_Sole.002']} position={[0, 0.25, 0]} />
                                <group position={[0, 0.25, 0]}>
                                    <mesh geometry={nodes.ID483001.geometry} material={materials['Color_M06.002']} />
                                    <mesh geometry={nodes.ID483001_1.geometry} material={materials['Chris_Shoe_Sole.002']} />
                                </group>
                                <mesh geometry={nodes.group_26002.geometry} material={materials['Chris_Shoe_Sole.002']} position={[0, 0.25, 0]} />
                                <mesh geometry={nodes.group_26003.geometry} material={materials['Chris_Shoe_Sole.002']} position={[0, 0.25, 0]} />
                                <mesh geometry={nodes.group_26004.geometry} material={materials['Chris_Shoe_Sole.002']} position={[0, 0.25, 0]} />
                                <mesh geometry={nodes.group_26005.geometry} material={materials['Chris_Shoe_Sole.002']} position={[0, 0.25, 0]} />
                            </group>
                            <mesh geometry={nodes.group_24.geometry} material={materials['Color_M07.002']} position={[1.97, 1.54, -19.27]} scale={1.66} />
                            <mesh geometry={nodes.group_27.geometry} material={materials['Color_G06.002']} position={[1.93, 1.54, -7.83]} scale={1.66} />
                            <mesh geometry={nodes.group_28.geometry} material={materials['Color_A05.002']} position={[1.93, 1.54, -13.51]} scale={1.66} />
                            <mesh geometry={nodes.group_29.geometry} material={materials['Color_I04.002']} position={[1.93, 1.54, -2.11]} scale={1.66} />
                            <mesh geometry={nodes.group_30.geometry} material={materials['noon1.002']} position={[-2, -0.1, 3.73]} />
                        </group>
                        <group position={[0.37, 26.81, -48.36]} rotation={[0, -Math.PI / 6, 0]} scale={0.7}>
                            <mesh geometry={nodes.group_32.geometry} material={materials['Color_M06.002']} position={[11, 0, 0]} />
                            <mesh geometry={nodes.group_33.geometry} material={materials['Color_M06.002']} position={[15, 1, -2]} />
                            <mesh geometry={nodes.group_34.geometry} material={materials['Color_M06.002']} position={[15, 3.21, 1.05]} rotation={[-0.11, 0, 0]} />
                            <group position={[15, 3.21, 1.05]} rotation={[-0.11, 0, 0]}>
                                <mesh geometry={nodes.ID569001.geometry} material={materials['Color_M06.002']} />
                                <mesh geometry={nodes.ID569001_1.geometry} material={materials['Color_M09.002']} />
                            </group>
                            <mesh geometry={nodes.group_34002.geometry} material={materials['Color_M06.002']} position={[15, 3.21, 1.05]} rotation={[-0.11, 0, 0]} />
                        </group>
                    </group>
                    <group position={[108.66, 0, -88.65]} rotation={[-Math.PI, 1.48, -Math.PI]}>
                        <mesh geometry={nodes.group_37.geometry} material={materials['noon_2.002']} />
                        <mesh geometry={nodes.group_38.geometry} material={materials['noon_3.002']} position={[3, 15.81, -0.35]} rotation={[-1.49, 0, 0]} />
                        <mesh geometry={nodes.group_38001.geometry} material={materials['material.002']} position={[3, 15.81, -0.35]} rotation={[-1.49, 0, 0]} />
                        <mesh geometry={nodes.group_38002.geometry} material={materials['noon1.002']} position={[3, 15.81, -0.35]} rotation={[-1.49, 0, 0]} />
                        <mesh geometry={nodes.group_38003.geometry} material={materials['noon1.002']} position={[3, 15.81, -0.35]} rotation={[-1.49, 0, 0]} />
                    </group>
                    <group position={[0, 0, -3.57]}>
                        <group position={[23.87, 0, 0]} rotation={[0, 1.47, 0]}>
                            <mesh geometry={nodes.group_41.geometry} material={materials['noon1.002']} />
                            <mesh geometry={nodes.group_42.geometry} material={materials['afternoon_3.002']} position={[2.99, 1, 1]} />
                            <mesh geometry={nodes.group_42001.geometry} material={materials['afternoon_3.002']} position={[2.99, 1, 1]} />
                            <mesh geometry={nodes.group_42002.geometry} material={materials['afternoon_3.002']} position={[2.99, 1, 1]} />
                            <mesh geometry={nodes.group_42003.geometry} material={materials['afternoon_3.002']} position={[2.99, 1, 1]} />
                            <mesh geometry={nodes.group_43.geometry} material={materials['afternoon_3.002']} position={[1, 19.38, 0.32]} scale={0.32} />
                            <mesh geometry={nodes.group_43001.geometry} material={materials['afternoon_3.002']} position={[1, 19.38, 0.32]} scale={0.32} />
                            <mesh geometry={nodes.group_43002.geometry} material={materials['afternoon_3.002']} position={[1, 19.38, 0.32]} scale={0.32} />
                            <mesh geometry={nodes.group_43003.geometry} material={materials['afternoon_3.002']} position={[1, 19.38, 0.32]} scale={0.32} />
                            <mesh geometry={nodes.group_44.geometry} material={materials['Sketchy_Siding_Straight.002']} position={[2.01, 26.81, -2.01]} />
                        </group>
                        <mesh geometry={nodes.group_45.geometry} material={materials['Color_M08.002']} position={[4.75, 30.81, -3.86]} />
                        <mesh geometry={nodes.group_45001.geometry} material={materials['Color_M08.002']} position={[4.75, 30.81, -3.86]} />
                        <mesh geometry={nodes.group_46.geometry} material={materials['noon1.002']} position={[4.75, 31.81, -3.86]} />
                        <mesh geometry={nodes.group_46001.geometry} material={materials['noon1.002']} position={[4.75, 31.81, -3.86]} />
                        <group position={[4.75, 31.81, -3.86]}>
                            <mesh geometry={nodes.ID728001.geometry} material={materials['noon1.002']} />
                            <mesh geometry={nodes.ID728001_1.geometry} material={materials['noon_5.002']} />
                        </group>
                        <mesh geometry={nodes.group_47.geometry} material={materials['Color_M06.002']} position={[17.54, 30.81, -18.96]} />
                        <mesh geometry={nodes.group_47001.geometry} material={materials['Color_M06.002']} position={[17.54, 30.81, -18.96]} />
                        <mesh geometry={nodes.group_48.geometry} material={materials['material.002']} position={[19.4, 31.06, -19.3]} />
                    </group>
                    <mesh geometry={nodes.group_35.geometry} material={materials['noon_5.002']} position={[31.42, 0, 0]} />
                    <mesh geometry={nodes.group_49.geometry} material={materials['material.002']} position={[-3.83, 25.69, -30.97]} />
                </group>
                <group position={[6, 126, -6]}>
                    <group position={[52.99, 18, -94.57]}>
                        <mesh geometry={nodes.group_52.geometry} material={materials['Color_M06.002']} position={[11, 0, 0]} />
                        <mesh geometry={nodes.group_53.geometry} material={materials['Color_M06.002']} position={[15, 1, -2]} />
                        <mesh geometry={nodes.group_54.geometry} material={materials['Color_M06.002']} position={[15, 3, 0]} />
                        <group position={[15, 3, 0]}>
                            <mesh geometry={nodes.ID790.geometry} material={materials['Color_M06.002']} />
                            <mesh geometry={nodes.ID790_1.geometry} material={materials['Color_M09.002']} />
                        </group>
                        <mesh geometry={nodes.group_54002.geometry} material={materials['Color_M06.002']} position={[15, 3, 0]} />
                    </group>
                    <group position={[0, 1, 0]}>
                        <mesh geometry={nodes.group_56.geometry} material={materials['Suede_Brown.002']} position={[0, 9, 0]} />
                        <mesh geometry={nodes.group_57.geometry} material={materials['Suede_Brown.002']} position={[0, 18, 0]} />
                        <mesh geometry={nodes.group_58.geometry} material={materials['Suede_Brown.002']} />
                    </group>

                    <group position={[60, 0, 0]} onClick={() => download_pdf()} >
                        <mesh geometry={nodes.group_61.geometry} material={materials['noon_4.002']} />
                        <mesh geometry={nodes.group_62.geometry} material={materials['noon_5.002']} position={[45.12, 12.36, -2.88]} />
                        <mesh geometry={nodes.instance_7.geometry} material={materials['noon_3.002']} position={[3.78, 17.55, -26.55]} scale={[1.19, 1.19, 2.07]} />
                        <mesh geometry={nodes.instance_7001.geometry} material={materials['noon_3.002']} position={[3.78, 17.55, -26.55]} scale={[1.19, 1.19, 2.07]} />
                        <mesh geometry={nodes.instance_7002.geometry} material={materials['noon_3.002']} position={[3.78, 17.55, -26.55]} scale={[1.19, 1.19, 2.07]} />
                        <mesh geometry={nodes.instance_7003.geometry} material={materials['noon_3.002']} position={[3.78, 17.55, -26.55]} scale={[1.19, 1.19, 2.07]} />
                        <mesh geometry={nodes.instance_7004.geometry} material={materials['noon_3.002']} position={[3.78, 17.55, -26.55]} scale={[1.19, 1.19, 2.07]} />
                        <mesh geometry={nodes.instance_7005.geometry} material={materials['noon_3.002']} position={[3.78, 17.55, -26.55]} scale={[1.19, 1.19, 2.07]} />
                        <mesh geometry={nodes.instance_7006.geometry} material={materials['noon_3.002']} position={[3.78, 17.55, -26.55]} scale={[1.19, 1.19, 2.07]} />
                        <mesh geometry={nodes.instance_8.geometry} material={materials['noon_3.002']} position={[2.67, 17.49, -7.73]} scale={1.3} />
                        <mesh geometry={nodes.instance_8001.geometry} material={materials['noon_3.002']} position={[2.67, 17.49, -7.73]} scale={1.3} />
                        <mesh geometry={nodes.instance_8002.geometry} material={materials['noon_3.002']} position={[2.67, 17.49, -7.73]} scale={1.3} />
                        <mesh geometry={nodes.instance_8003.geometry} material={materials['noon_3.002']} position={[2.67, 17.49, -7.73]} scale={1.3} />
                        <mesh geometry={nodes.instance_8004.geometry} material={materials['noon_3.002']} position={[2.67, 17.49, -7.73]} scale={1.3} />
                    </group>

                    <group position={[99.99, 18, -83.26]} rotation={[0, 0, -Math.PI]}>
                        <mesh geometry={nodes.group_64.geometry} material={materials['Translucent_Glass_Gray.002']} />
                        <mesh geometry={nodes.group_64001.geometry} material={materials['Translucent_Glass_Gray.002']} />
                        <mesh geometry={nodes.group_65.geometry} material={materials['noon1.002']} position={[1, 2, -1]} />
                        <mesh geometry={nodes.group_66.geometry} material={materials['noon1.002']} position={[57, 2, -1]} />
                        <mesh geometry={nodes.group_67.geometry} material={materials['noon1.002']} position={[57, 2, -21]} />
                        <mesh geometry={nodes.group_68.geometry} material={materials['noon1.002']} position={[1, 2, -21]} />
                        <mesh geometry={nodes.group_69.geometry} material={materials['Translucent_Glass_Gray.002']} position={[0, 12, 0]} />
                        <mesh geometry={nodes.group_69001.geometry} material={materials['Translucent_Glass_Gray.002']} position={[0, 12, 0]} />
                    </group>

                    {/* js_logo */}
                    <group position={[105.29, 21.88, -93.64]}>
                        <animated.mesh scale={scale} onClick={() => open_github()} ref={js_logo}>
                            <mesh geometry={nodes.group_59.geometry} material={materials['Color_E05.002']} position={[-10, 0, 0]} scale={0.62}>
                                <mesh geometry={nodes.instance_6.geometry} material={materials['Color_M09.002']} position={[17.37, 2.76, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.24, 0.24, 0.23]} />
                                <mesh geometry={nodes.instance_6001.geometry} material={materials['Color_M09.002']} position={[17.37, 2.76, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.24, 0.24, 0.23]} />
                            </mesh>
                        </animated.mesh>
                    </group>

                    {/* py logo */}
                    <group position={[38.61, 32.96, -97.22]}>
                        <animated.mesh scale={scale} onClick={() => open_github()} ref={py_logo}>
                            <mesh geometry={nodes.instance_9.geometry} material={materials['__auto_.002']} position={[0, 0, 0]} scale={0.3} />
                            <mesh geometry={nodes.instance_9001.geometry} material={materials['__auto_.002']} position={[0, 0, 0]} scale={0.3} />
                            <mesh geometry={nodes.instance_9002.geometry} material={materials['__auto_1.002']} position={[0, 0, 0]} scale={0.3} />
                            <mesh geometry={nodes.instance_9003.geometry} material={materials['__auto_1.002']} position={[0, 0, 0]} scale={0.3} />
                        </animated.mesh>

                    </group>

                    {/* 
                            <planeGeometry />
                            <Suspense fallback={<FallbackMaterial url="10.jpg" />}>
                                <VideoMaterial url="world.mp4" />
                            </Suspense>
                    */}
                </group>
                <group position={[-28.76, 6, 132.94]}>
                    <group position={[16.76, 0, -8.94]}>

                        <animated.mesh scale={scale} onClick={() => setActive(!active)} ref={garage_door}>

                            <group position={[6, 116, -10]} rotation={[0, 0, Math.PI]}>
                                <mesh geometry={nodes.group_74.geometry} material={materials['noon_2.002']} />
                                <mesh geometry={nodes.group_74001.geometry} material={materials['noon_2.002']} />
                                <mesh geometry={nodes.group_74002.geometry} material={materials['noon_2.002']} />
                                <mesh geometry={nodes.group_74003.geometry} material={materials['noon_2.002']} />
                                <mesh geometry={nodes.group_75.geometry} material={materials['Translucent_Glass_Blue.002']} position={[0, 110, -4]} rotation={[0, 0, -Math.PI]} />
                                <mesh geometry={nodes.group_75001.geometry} material={materials['Translucent_Glass_Blue.002']} position={[0, 110, -4]} rotation={[0, 0, -Math.PI]} />
                                <mesh geometry={nodes.group_75002.geometry} material={materials['Translucent_Glass_Blue.002']} position={[0, 110, -4]} rotation={[0, 0, -Math.PI]} />
                                <mesh geometry={nodes.group_75003.geometry} material={materials['Translucent_Glass_Blue.002']} position={[0, 110, -4]} rotation={[0, 0, -Math.PI]} />
                                <mesh geometry={nodes.group_75004.geometry} material={materials['Translucent_Glass_Blue.002']} position={[0, 110, -4]} rotation={[0, 0, -Math.PI]} />
                                <mesh geometry={nodes.group_75005.geometry} material={materials['Translucent_Glass_Blue.002']} position={[0, 110, -4]} rotation={[0, 0, -Math.PI]} />
                                <mesh geometry={nodes.group_75006.geometry} material={materials['Translucent_Glass_Blue.002']} position={[0, 110, -4]} rotation={[0, 0, -Math.PI]} />
                            </group>
                        </animated.mesh>
                        <mesh geometry={nodes.group_72.geometry} material={materials['noon_2.002']} />
                    </group>
                    <group position={[-1.84, 0, 0]}>
                        <group position={[1.92, 32.99, 0]}>
                            <mesh geometry={nodes.group_79.geometry} material={materials['noon_5.002']} position={[6.96, 1.3, -1]} />
                            <mesh geometry={nodes.group_80.geometry} material={materials['Color_M08.002']} position={[0, 0, -17]} rotation={[Math.PI / 2, 0, 0]} scale={[1.74, 1, 1.31]} />
                            <group position={[0, 0, -17]} rotation={[Math.PI / 2, 0, 0]} scale={[1.74, 1, 1.31]}>
                                <mesh geometry={nodes.ID1153.geometry} material={materials['Color_M07.002']} />
                                <mesh geometry={nodes.ID1153_1.geometry} material={materials['Color_M08.002']} />
                            </group>
                            <mesh geometry={nodes.group_80002.geometry} material={materials['Color_M08.002']} position={[0, 0, -17]} rotation={[Math.PI / 2, 0, 0]} scale={[1.74, 1, 1.31]} />
                            <group position={[0, 0, -17]} rotation={[Math.PI / 2, 0, 0]} scale={[1.74, 1, 1.31]}>
                                <mesh geometry={nodes.ID1165.geometry} material={materials['Color_M07.002']} />
                                <mesh geometry={nodes.ID1165_1.geometry} material={materials['Color_M08.002']} />
                            </group>
                            <mesh geometry={nodes.group_80004.geometry} material={materials['Color_M08.002']} position={[0, 0, -17]} rotation={[Math.PI / 2, 0, 0]} scale={[1.74, 1, 1.31]} />
                        </group>
                        <mesh geometry={nodes.group_77.geometry} material={materials['material.002']} position={[7.4, 0, -17]} rotation={[0, 1.57, 0]} />
                        <mesh geometry={nodes.group_77001.geometry} material={materials['material.002']} position={[7.4, 0, -17]} rotation={[0, 1.57, 0]} />
                        <mesh geometry={nodes.group_77002.geometry} material={materials['material.002']} position={[7.4, 0, -17]} rotation={[0, 1.57, 0]} />
                    </group>
                    <mesh geometry={nodes.instance_10.geometry} material={materials['noon_5.002']} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes.instance_10001.geometry} material={materials['noon_5.002']} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes.instance_10002.geometry} material={materials['noon_5.002']} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes.instance_10003.geometry} material={materials['noon_5.002']} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes.instance_10004.geometry} material={materials['noon_5.002']} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes.instance_10005.geometry} material={materials['noon_5.002']} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes.instance_10006.geometry} material={materials['noon_5.002']} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes.instance_10007.geometry} material={materials['noon_5.002']} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes.instance_10008.geometry} material={materials['noon_5.002']} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes.instance_10009.geometry} material={materials['noon_5.002']} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes.instance_10010.geometry} material={materials['noon_5.002']} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes.instance_10011.geometry} material={materials['noon_5.002']} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes.instance_10012.geometry} material={materials['noon_5.002']} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
                </group>
                <mesh geometry={nodes.group_10.geometry} material={materials['material.002']} position={[-120, 0, 120]} />
                <mesh geometry={nodes.group_7.geometry} material={materials['Grass_Dark_Green.002']} position={[-120, 3, 120]} />
                <group position={[-120, 0, 120]}>
                    <mesh geometry={nodes.ID353001.geometry} material={materials['Groundcover_Wood_Mix.002']} />
                    <mesh geometry={nodes.ID353001_1.geometry} material={materials['Vegetation_Bark_Ponderosa.002']} />
                </group>
                <mesh geometry={nodes.group_9.geometry} material={materials['material.002']} position={[-68.5, 283.36, -115]} />
                <mesh geometry={nodes.image_0.geometry} material={materials['material_0.002']} position={[-68.5, 283.36, -114.8]} rotation={[Math.PI / 2, 0, 0]} scale={[0.04, 1, 0.04]} />
            </group>
        </group>
    );
}
