/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 .\\models\\02-assets\\raybans.glb 
*/

import { useRef, Suspense } from 'react';
import { useLoader, useFrame } from '@react-three/fiber';
import { useGLTF, SpotLight, useVideoTexture, useTexture, useAspect } from '@react-three/drei';
import { Object3D } from 'three'; // Import Object3D class from Three.js


export default function RayBans(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/raybans.glb')
  const mesh_ref = useRef();
  const spotlight_ref = useRef();
  let moving_down = false;

  const spotlightTarget = new Object3D();
  spotlightTarget.position.set(1.2, 0, -1.3); // Replace with your desired coordinates

  useFrame(({ clock }) => {
    const a = clock.getElapsedTime();

    if (moving_down) {
      mesh_ref.current.position.y -= .001;
    }
    else {
      mesh_ref.current.position.y += .001;
    }
    if (mesh_ref.current.position.y > 9.8) {
      moving_down = true
    }
    else if (mesh_ref.current.position.y < 9.45) {
      moving_down = false
    }
    // easing.dampE(logo_ref.current.rotation, [0, state.pointer.x * (state.camera.position.z > 1 ? 1 : -1), 0], 0.4, delta)
  })
  return (
    <group {...props} dispose={null} scale={.5}>
      <SpotLight
        ref={spotlight_ref}
        position={[6.5, 14, -7]}
        intensity={.8}
        angle={Math.PI / 7}
        penumbra={1}
        decay={1}
        distance={8}
        color="white"
        target={spotlightTarget} // Point the spotlight at the mesh_ref
      />
      <group ref={mesh_ref} position={[5.75, 9.55, -4.3]} scale={0.025}>
        <mesh name="test_mesh" geometry={nodes.group_0.geometry} material={materials.Color_M08} position={[-10.544, 1.02, -10.92]} />
        <mesh geometry={nodes.group_0001.geometry} material={materials.Color_M08} position={[-10.544, 1.02, -10.92]} />
        <mesh geometry={nodes.group_0002.geometry} material={materials.Color_M08} position={[-10.544, 1.02, -10.92]} />
        <mesh geometry={nodes.group_1.geometry} material={materials.Translucent_Glass_Blue} position={[-8.911, 1.553, -11.92]} />
        <mesh geometry={nodes.group_2.geometry} material={materials.Translucent_Glass_Blue} position={[2.151, 1.553, -11.92]} />
        <mesh geometry={nodes.group_3.geometry} material={materials.Color_M07} position={[-10.015, 7.017, -11.955]} scale={1.28} />

        <group position={[-10.015, 7.017, -11.955]} scale={1.28}>
          <mesh geometry={nodes.ID49.geometry} material={materials.Color_M07} />
          <mesh geometry={nodes.ID49_1.geometry} material={materials.Color_M09} />
        </group>
        <mesh geometry={nodes.group_3002.geometry} material={materials.Color_M07} position={[-10.015, 7.017, -11.955]} scale={1.28} />
        <mesh geometry={nodes.group_4.geometry} material={materials.Color_M08} position={[-10.544, 6.763, -12.92]} />
        <mesh geometry={nodes.group_5.geometry} material={materials.Color_M08} position={[10.676, 6.763, -12.92]} />
        <mesh geometry={nodes.group_6.geometry} material={materials.Color_M07} position={[10.047, 7.017, -11.955]} scale={1.28} />
        <group position={[10.047, 7.017, -11.955]} scale={1.28}>
          <mesh geometry={nodes.ID84.geometry} material={materials.Color_M07} />
          <mesh geometry={nodes.ID84_1.geometry} material={materials.Color_M09} />
        </group>
        <mesh geometry={nodes.group_6002.geometry} material={materials.Color_M07} position={[10.047, 7.017, -11.955]} scale={1.28} />
      </group>
    </group>
  )
}
