/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\hut.glb
*/
import { useRef } from 'react';
import { useLoader, useFrame, useThree } from '@react-three/fiber';
import { useGLTF, SpotLight, useVideoTexture, useTexture } from '@react-three/drei';
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { easing } from 'maath'
// import * as THREE from 'three'
// import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
// import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass'
import Effects from './Effects'



function VideoMaterial({ url }) {
    const texture = useVideoTexture(url)
    return <meshBasicMaterial map={texture} toneMapped={false} />
}

function FallbackMaterial({ url }) {
    const texture = useTexture(url)
    return <meshBasicMaterial map={texture} toneMapped={false} />
}

// make it glow - insert in mesh
{/* <meshStandardMaterial emissive={[0.5, 0.5, 0.5]} color={[0, 0, 0]} /> */ }

export default function HutModel() {
    const group = useRef();
    const { nodes, materials } = useGLTF("./seabar.glb");

    const spotlight_01 = useRef();
    const spotlight_02 = useRef();
    const light_inside = useRef();

    const toggle_light = (light_ref) => {
        // light_ref.current.distance = light_ref.current.intensity == 0 ? 0 : 0;

        light_ref.current.intensity = light_ref.current.intensity == 0 ? 1 : 0;
    }


    return (
        <group dispose={null}>
            <group scale={0.03}>
                <pointLight ref={light_inside} position={[5, 10, 5]} intensity={1} />

                <group position={[52.33, 6, -3.32]}>
                    <mesh geometry={nodes.group_22.geometry} material={materials.__Wood_Bamboo_1} />
                    <mesh geometry={nodes.group_23.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23001.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23002.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23003.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23004.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23005.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23006.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23007.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23008.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23009.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23010.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23011.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23012.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23013.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23014.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23015.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23016.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23017.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23018.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23019.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                    <mesh geometry={nodes.group_23020.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0.64]} />
                </group>
                <group position={[3.21, 6, 59.45]}>
                    <mesh geometry={nodes.group_25.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_25001.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_25002.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_25003.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_25004.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_25005.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_25006.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_25007.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_25008.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_25009.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_25010.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_25011.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_25012.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_25013.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_25014.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_25015.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_25016.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_25017.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_25018.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_25019.geometry} material={materials.__Wood_Bamboo_1} position={[-0.31, 0, 0.5]} />
                    <mesh geometry={nodes.group_26.geometry} material={materials.__Wood_Bamboo_1} />
                </group>
                <group position={[52.33, 6, 53.45]}>
                    <mesh geometry={nodes.group_29.geometry} material={materials.__Wood_Bamboo_1} />
                    <mesh geometry={nodes.group_30.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30001.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30002.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30003.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30004.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30005.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30006.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30007.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30008.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30009.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30010.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30011.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30012.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30013.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30014.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30015.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30016.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30017.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30018.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30019.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                    <mesh geometry={nodes.group_30020.geometry} material={materials.__Wood_Bamboo_1} position={[6, 0, 0]} />
                </group>

                <group position={[-18.88, 154, 50.45]} rotation={[Math.PI, 1.57, 0]}>
                    <mesh geometry={nodes.group_41.geometry} material={materials.Formica_Laminate_Dark} />
                    <mesh geometry={nodes.group_41001.geometry} material={materials.Formica_Laminate_Dark} />
                    <mesh geometry={nodes.group_42.geometry} material={materials.Steel_Brushed_Stainless} position={[1, 24, -1]} />
                    <mesh geometry={nodes.group_43.geometry} material={materials.Steel_Brushed_Stainless} position={[1, 24, -33]} />
                    <mesh geometry={nodes.group_44.geometry} material={materials['material.001']} position={[3, 1, -1]} />
                </group>
                <group position={[40.31, 163.24, 50.05]} rotation={[Math.PI, 1.57, 0]} scale={[1.1, 1.33, 1.5]}>
                    <mesh geometry={nodes.group_49.geometry} material={materials.Formica_Laminate_Dark} />
                    <mesh geometry={nodes.group_49001.geometry} material={materials.Formica_Laminate_Dark} />
                    <mesh geometry={nodes.group_50.geometry} material={materials.Steel_Brushed_Stainless} position={[1, 24, -1]} />
                    <mesh geometry={nodes.group_51.geometry} material={materials.Steel_Brushed_Stainless} position={[1, 24, -33]} />
                    <mesh geometry={nodes.group_52.geometry} material={materials['material.001']} position={[2.55, 23, -35]} rotation={[-Math.PI, 0, 0]} scale={[0.91, 0.75, 0.67]} />
                </group>

                {/* Painting */}
                <group position={[-55.67, 45.53, 20.51]} rotation={[0, -1.57, 0]}>
                    <mesh geometry={nodes.group_54.geometry} material={materials.Terrazzo_Light_Blue} />
                    <mesh geometry={nodes.group_54001.geometry} material={materials.Terrazzo_Light_Blue} />
                    <mesh geometry={nodes.group_55.geometry} material={materials['Color_M00.001']} position={[1, 1, -1]} onClick={() => toggle_light(light_inside)} />
                </group>

                <group position={[13.74, 49.6, -54.55]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={1.27}>
                    <mesh geometry={nodes.group_58.geometry} material={materials.Metal_Seamed} />
                    <mesh geometry={nodes.group_58001.geometry} material={materials.Metal_Seamed} />
                    <mesh geometry={nodes.group_59.geometry} material={materials['Color_M00.001']} position={[1, 1, -1]} />
                </group>
                <group position={[32.22, 60, -17.36]} rotation={[0, -0.52, 0]}>
                    <mesh geometry={nodes.group_10.geometry} material={materials['material.001']} position={[3, 1, -1]} />
                    <mesh geometry={nodes.group_7.geometry} material={materials.Formica_Laminate_Dark} />
                    <mesh geometry={nodes.group_7001.geometry} material={materials.Formica_Laminate_Dark} />
                    <mesh geometry={nodes.group_8.geometry} material={materials.Steel_Brushed_Stainless} position={[1, 24, -1]} />
                    <mesh geometry={nodes.group_9.geometry} material={materials.Steel_Brushed_Stainless} position={[1, 24, -33]} />
                </group>
                <group position={[-67.67, 12, -66.55]} rotation={[0, -1.57, 0]}>
                    <mesh geometry={nodes.group_62.geometry} material={materials.Metal_Silver_1} position={[1, 15.69, -1]} />
                    <mesh geometry={nodes.group_63.geometry} material={materials.__Metal_Aluminum_Anodized_1} position={[0, 84, -54]} />
                    <mesh geometry={nodes.group_64.geometry} material={materials.__Metal_Aluminum_Anodized_1} position={[96, 0, 0]} />
                    <mesh geometry={nodes.group_65.geometry} material={materials.__Metal_Aluminum_Anodized_1} position={[0, 84, -18]} />
                </group>
                <group position={[-63.67, 13.44, -61.55]} rotation={[0, -1.57, 0]}>
                    <group position={[0, 26.86, 0]}>
                        <mesh geometry={nodes.group_68.geometry} material={materials.Formica_Beige} position={[6, 3, 0]} rotation={[0, 1.57, 0]} />
                        <mesh geometry={nodes.group_69.geometry} material={materials.Formica_Beige} position={[6, 53.81, 0]} rotation={[0, 1.57, 0]} />
                        <mesh geometry={nodes.group_70.geometry} material={materials.Formica_Beige} position={[40.95, 17.41, 0]} rotation={[0, 1.57, 0]} />
                        <mesh geometry={nodes.group_71.geometry} material={materials.Formica_Beige} position={[116, 22.7, 0]} rotation={[0, 1.57, 0]} />
                        <mesh geometry={nodes.group_72.geometry} material={materials.Formica_Beige} position={[98.27, 53.81, 0]} rotation={[0, 1.57, 0]} />
                        <mesh geometry={nodes.group_73.geometry} material={materials.Formica_Beige} position={[58.01, 73.14, 0]} rotation={[0, 1.57, 0]} />
                        <mesh geometry={nodes.group_74.geometry} material={materials.Formica_Beige} position={[68.73, 29.53, 0]} rotation={[0, 1.57, 0]} />
                    </group>
                    <group position={[0, 0, -35.95]}>
                        <mesh geometry={nodes.group_76.geometry} material={materials.Formica_Beige} position={[0, 15.11, -53.27]} />
                        <mesh geometry={nodes.group_77.geometry} material={materials.Formica_Beige} position={[0, 8.28, -6]} />
                        <mesh geometry={nodes.group_78.geometry} material={materials.Formica_Beige} position={[0, 3, -81.05]} />
                        <mesh geometry={nodes.group_79.geometry} material={materials.Formica_Beige} position={[0, 99.91, -81.05]} />
                        <mesh geometry={nodes.group_80.geometry} material={materials.Formica_Beige} position={[0, 58.72, -63.99]} />
                        <mesh geometry={nodes.group_81.geometry} material={materials.Formica_Beige} position={[0, 39.4, -23.73]} />
                    </group>
                </group>

                <group position={[58.33, 109, -55.55]} rotation={[0, -1.57, 0]} scale={3}>
                    <mesh geometry={nodes.group_84.geometry} material={materials['Color_M08.001']} emissive={[0.5, 0.5, 0.5]} color={[0, 0, 0]} />
                    <mesh geometry={nodes.group_85.geometry} material={materials['Color_G03.001']} position={[0.5, 0.5, -2]} onClick={() => toggle_light(spotlight_02)} />
                </group>

                <group position={[62.1, -8.19, 150.01]} rotation={[0, -1.57, 0]}>
                    <group position={[-5.47, 10, -23.07]} rotation={[Math.PI / 2, 0, 0.96]} scale={3}>
                        <mesh geometry={nodes.group_88.geometry} material={materials['Color_M08.001']} />
                        <mesh geometry={nodes.group_89.geometry} material={materials['Color_A05.001']} position={[0.5, 0.5, -2]} onClick={() => toggle_light(spotlight_01)} />
                    </group>
                    <group position={[0, 10, -4.9]} rotation={[0, -0.96, 0]}>
                        <mesh geometry={nodes.group_91.geometry} material={materials.Wood_Veneer_02_2} />
                        <group position={[0, 84, 0]}>
                            <SpotLight ref={spotlight_01} penumbra={1} distance={0} angle={0.7} anglePower={4} intensity={1} position={[0, 0, 0]} />

                            <mesh geometry={nodes.ID1413.geometry} material={materials['Translucent_Glass_Gold.001']} />
                            <mesh geometry={nodes.ID1413_1.geometry} material={materials['Translucent_Glass_Gray.001']} />
                        </group>
                    </group>
                </group>
                <group position={[42.58, 126, -59.48]} rotation={[0, -1.57, 0]}>
                    <SpotLight ref={spotlight_02} penumbra={1} distance={4} angle={0.8} anglePower={4} intensity={0} position={[5, 76, -1]} />
                    <mesh geometry={nodes.group_94.geometry} material={materials['material.001']} position={[0, 72, 0]} />
                    <mesh geometry={nodes.group_95.geometry} material={materials['material.001']} position={[2, 0, -8]} />
                </group>
                <group position={[-55.67, 6, 59.45]}>
                    <mesh geometry={nodes.group_100.geometry} material={materials.Wood_Board_Cork} position={[52.88, 0, -6]} rotation={[0, -1.57, 0]} />
                    <mesh geometry={nodes.group_97.geometry} material={materials.Wood_Board_Cork} position={[108, 0, -6]} rotation={[0, -1.57, 0]} />
                    <mesh geometry={nodes.group_98.geometry} material={materials.Wood_Board_Cork} position={[0, 0, -4]} rotation={[0, -1.57, 0]} />
                    <mesh geometry={nodes.group_99.geometry} material={materials.Wood_Board_Cork} position={[108, 0, -62.77]} rotation={[0, -1.57, 0]} />
                </group>
                <mesh geometry={nodes.group_0.geometry} material={materials.Wood_Lumber_ButtJoined} position={[71.84, 24.1, -7.3]} rotation={[Math.PI, -1.43, 0]} />
                <mesh geometry={nodes.group_1.geometry} material={materials.Wood_Lumber_ButtJoined} position={[69.5, 24.1, -30.87]} rotation={[Math.PI, -1.43, 0]} />
                <mesh geometry={nodes.group_11.geometry} material={materials.Wood_Plywood_Knots} position={[-85.06, 4, -132.44]} rotation={[-Math.PI, 0, -Math.PI]} />
                <mesh geometry={nodes.group_12.geometry} material={materials.Wood_Plywood_Knots} position={[-33.02, 4, -132.44]} rotation={[-Math.PI, 0, -Math.PI]} />
                <mesh geometry={nodes.group_13.geometry} material={materials.Wood_Plywood_Knots} position={[-72.05, 4, -132.44]} rotation={[-Math.PI, 0, -Math.PI]} />
                <mesh geometry={nodes.group_14.geometry} material={materials.Wood_Plywood_Knots} position={[-46.03, 4, -132.44]} rotation={[-Math.PI, 0, -Math.PI]} />
                <mesh geometry={nodes.group_15.geometry} material={materials.Wood_Plywood_Knots} position={[111.07, 4, 132.44]} />
                <group position={[111.07, 4, 132.44]}>
                    <mesh geometry={nodes.ID167001.geometry} material={materials.Wood_Plywood_Knots} />
                    <mesh geometry={nodes.ID167001_1.geometry} material={materials.Wood_Plywood_Knots_0} />
                </group>

                <mesh geometry={nodes.group_16.geometry} material={materials.Wood_Plywood_Knots} position={[85.06, 4, 132.44]} />
                <mesh geometry={nodes.group_17.geometry} material={materials.Wood_Plywood_Knots} position={[-7.01, 4, -132.44]} rotation={[-Math.PI, 0, -Math.PI]} />
                <mesh geometry={nodes.group_18.geometry} material={materials.Wood_Plywood_Knots} position={[-59.04, 4, -132.44]} rotation={[-Math.PI, 0, -Math.PI]} />
                <mesh geometry={nodes.group_19.geometry} material={materials.Wood_Plywood_Knots} position={[-20.02, 4, -132.44]} rotation={[-Math.PI, 0, -Math.PI]} />
                <mesh geometry={nodes.group_2.geometry} material={materials.Wood_Lumber_ButtJoined} position={[68.22, 24.1, 23.65]} rotation={[Math.PI, -1.43, 0]} />
                <mesh geometry={nodes.group_20.geometry} material={materials.Wood_Lumber_ButtJoined} position={[29.2, 24.1, 88.84]} rotation={[Math.PI, -1.43, 0]} />
                <mesh geometry={nodes.group_27.geometry} material={materials.Wood_Lumber_ButtJoined} position={[2.38, 24.1, 84.98]} rotation={[Math.PI, -1.43, 0]} />
                <mesh geometry={nodes.group_3.geometry} material={materials.Wood_Plywood_Knots} position={[98.06, 4, 132.44]} />
                <mesh geometry={nodes.group_31.geometry} material={materials.Wood_Lumber_ButtJoined} position={[64.06, 24.1, 46.71]} rotation={[Math.PI, -1.43, 0]} />
                <mesh geometry={nodes.group_32.geometry} material={materials.Wood_Plywood_Knots} position={[33.02, 4, 132.44]} />
                <mesh geometry={nodes.group_33.geometry} material={materials['material.001']} position={[-57.35, 0, 165.55]} rotation={[0, Math.PI / 6, 0]} />
                <mesh geometry={nodes.group_34.geometry} material={materials.Wood_Plywood_Knots} position={[72.05, 4, 132.44]} />
                <mesh geometry={nodes.group_35.geometry} material={materials.Wood_Plywood_Knots} position={[46.03, 4, 132.44]} />
                <mesh geometry={nodes.group_36.geometry} material={materials.Wood_Plywood_Knots} position={[-6, 4, 132.44]} />
                <mesh geometry={nodes.group_37.geometry} material={materials.Wood_Plywood_Knots} position={[7.01, 4, 132.44]} />
                <mesh geometry={nodes.group_38.geometry} material={materials.Wood_Plywood_Knots} position={[20.02, 4, 132.44]} />

                <mesh geometry={nodes.group_39.geometry} material={materials['material.001']} position={[-49.67, 126, -50.11]} rotation={[0, -1.57, 0]} scale={[1, 0.6, 1]} />
                <mesh geometry={nodes.group_39001.geometry} material={materials['Wood_Veneer_02.001']} position={[-49.67, 126, -50.11]} rotation={[0, -1.57, 0]} scale={[1, 0.6, 1]} />
                <mesh geometry={nodes.group_39002.geometry} material={materials['Color_C06.001']} position={[-49.67, 126, -50.11]} rotation={[0, -1.57, 0]} scale={[1, 0.6, 1]} />
                <mesh geometry={nodes.group_39003.geometry} material={materials['material.001']} position={[-49.67, 126, -50.11]} rotation={[0, -1.57, 0]} scale={[1, 0.6, 1]} />
                <group position={[-49.67, 126, -50.11]} rotation={[0, -1.57, 0]} scale={[1, 0.6, 1]}>
                    <mesh geometry={nodes.ID872.geometry} material={materials['Wood_Veneer_02.001']} />
                    <mesh geometry={nodes.ID872_1.geometry} material={materials['Metal_Silver.001']} />
                </group>
                <mesh geometry={nodes.group_39005.geometry} material={materials['Metal_Silver.001']} position={[-49.67, 126, -50.11]} rotation={[0, -1.57, 0]} scale={[1, 0.6, 1]} />
                <mesh geometry={nodes.group_39006.geometry} material={materials['Metal_Silver.001']} position={[-49.67, 126, -50.11]} rotation={[0, -1.57, 0]} scale={[1, 0.6, 1]} />
                <mesh geometry={nodes.group_39007.geometry} material={materials['Metal_Silver.001']} position={[-49.67, 126, -50.11]} rotation={[0, -1.57, 0]} scale={[1, 0.6, 1]} />
                <mesh geometry={nodes.group_4.geometry} material={materials.Wood_Plywood_Knots} position={[-98.06, 4, -132.44]} rotation={[-Math.PI, 0, -Math.PI]} />
                <mesh geometry={nodes.group_45.geometry} material={materials.Formica_Speckled_Grey} position={[-54.67, 6, -3.3]} rotation={[0, -1.57, 0]} />
                <mesh geometry={nodes.group_46.geometry} material={materials.Formica_Laminate_Light} position={[-38.71, 53.69, -54.55]} rotation={[0, -1.57, 0]} />

                <group position={[-61.67, 6, -60.55]} rotation={[0, -1.57, 0]}>
                    <mesh geometry={nodes.ID995.geometry} material={materials['Color_M02.001']} />
                    <mesh geometry={nodes.ID995_1.geometry} material={materials['Translucent_Glass_Blue.001']} />
                </group>

                <group position={[-61.67, 6, -60.55]} rotation={[0, -1.57, 0]}>
                    <mesh geometry={nodes.ID1005.geometry} material={materials['Translucent_Glass_Blue.001']} />
                    <mesh geometry={nodes.ID1005_1.geometry} material={materials.Siding_Rusty_Metal} />
                </group>

                <group position={[-61.67, 6, -60.55]} rotation={[0, -1.57, 0]}>
                    <mesh geometry={nodes.ID1018.geometry} material={materials['Color_M02.001']} />
                    <mesh geometry={nodes.ID1018_1.geometry} material={materials['Translucent_Glass_Blue.001']} />
                </group>

                <mesh geometry={nodes.group_5.geometry} material={materials.Wood_Plywood_Knots} position={[-111.07, 4, -132.44]} rotation={[-Math.PI, 0, -Math.PI]} />
                <mesh geometry={nodes.group_56.geometry} material={materials['Color_M03.001']} position={[58.43, 79.93, 56.39]} rotation={[0, -1.57, 0]} />
                <mesh geometry={nodes.group_56001.geometry} material={materials['Color_M03.001']} position={[58.43, 79.93, 56.39]} rotation={[0, -1.57, 0]} />
                <mesh geometry={nodes.group_60.geometry} material={materials['Color_D01.001']} position={[58.33, 73.79, 53.87]} rotation={[0, -1.57, 0]} />
                <mesh geometry={nodes.group_82.geometry} material={materials.Wood_Plywood_Knots} position={[59.04, 4, 132.44]} />


                <mesh geometry={nodes.instance_1.geometry} material={materials['Chris_Shirt.001']} position={[-29.29, 6, -23.99]} rotation={[0, 1.18, 0]} />
                <mesh geometry={nodes.instance_1001.geometry} material={materials['Chris_Shirt.001']} position={[-29.29, 6, -23.99]} rotation={[0, 1.18, 0]} />
                <mesh geometry={nodes.instance_1002.geometry} material={materials['Chris_Shoe.001']} position={[-29.29, 6, -23.99]} rotation={[0, 1.18, 0]} />
                <mesh geometry={nodes.instance_1003.geometry} material={materials['Chris_Shirt.001']} position={[-29.29, 6, -23.99]} rotation={[0, 1.18, 0]} />
                <mesh geometry={nodes.instance_1004.geometry} material={materials['Chris_Skin.001']} position={[-29.29, 6, -23.99]} rotation={[0, 1.18, 0]} />
                <mesh geometry={nodes.instance_1005.geometry} material={materials['Chris_Shoe_Sole.001']} position={[-29.29, 6, -23.99]} rotation={[0, 1.18, 0]} />
                <mesh geometry={nodes.instance_1006.geometry} material={materials['Chris_Shoe_Sole.001']} position={[-29.29, 6, -23.99]} rotation={[0, 1.18, 0]} />
                <mesh geometry={nodes.instance_1007.geometry} material={materials['Chris_Skin.001']} position={[-29.29, 6, -23.99]} rotation={[0, 1.18, 0]} />
                <mesh geometry={nodes.instance_1008.geometry} material={materials['Chris_Hair.001']} position={[-29.29, 6, -23.99]} rotation={[0, 1.18, 0]} />
                <mesh geometry={nodes.instance_1009.geometry} material={materials['Chris_Shoe_Sole.001']} position={[-29.29, 6, -23.99]} rotation={[0, 1.18, 0]} />
                <mesh geometry={nodes.instance_1010.geometry} material={materials['Chris_Hair.001']} position={[-29.29, 6, -23.99]} rotation={[0, 1.18, 0]} />
                <mesh geometry={nodes.instance_1011.geometry} material={materials['Chris_Skin.001']} position={[-29.29, 6, -23.99]} rotation={[0, 1.18, 0]} />
                <mesh geometry={nodes.instance_1012.geometry} material={materials['Chris_Shoe.001']} position={[-29.29, 6, -23.99]} rotation={[0, 1.18, 0]} />
                <mesh geometry={nodes.instance_1013.geometry} material={materials['Chris_Pants.001']} position={[-29.29, 6, -23.99]} rotation={[0, 1.18, 0]} />
                <mesh geometry={nodes.instance_1014.geometry} material={materials['Chris_Skin.001']} position={[-29.29, 6, -23.99]} rotation={[0, 1.18, 0]} />

                {/* Wassuh */}
                <group>
                    <mesh geometry={nodes.instance_0.geometry} material={materials['material.001']} position={[19.8, 96, 59.45]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes.instance_2.geometry} material={materials['material.001']} position={[58.33, 96.08, 58.01]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
                    <mesh geometry={nodes.instance_2001.geometry} material={materials['material.001']} position={[58.33, 96.08, 58.01]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
                    <mesh geometry={nodes.instance_2002.geometry} material={materials['material.001']} position={[58.33, 96.08, 58.01]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
                    <mesh geometry={nodes.instance_0001.geometry} material={materials['material.001']} position={[19.8, 96, 59.45]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes.instance_0002.geometry} material={materials['material.001']} position={[19.8, 96, 59.45]} rotation={[Math.PI / 2, 0, 0]} />
                    <mesh geometry={nodes.instance_0003.geometry} material={materials['material.001']} position={[19.8, 96, 59.45]} rotation={[Math.PI / 2, 0, 0]} />
                </group>

            </group>
        </group>
    );
}
