/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\hut.glb
*/

import { useGLTF, SpotLight, useVideoTexture, useTexture, useAspect } from '@react-three/drei';

// import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
// import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass'
import Effects from './Effects'

export default function Snowboard() {
    const { nodes, materials } = useGLTF('/snowboard.glb')
    return (
        <group dispose={null} scale={0.01} position={[1, 1, 0.2]} rotation={[-.1, 0, 0]}>
            <mesh geometry={nodes['10535_Snowboard_v1_L3'].geometry} material={materials['10535_Snowboard_v1_SG']} rotation={[Math.PI / 2, 0, 0]} />
        </group>
    );
}
