/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\github.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/github.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Github_logo.geometry} material={nodes.Github_logo.material} />
    </group>
  )
}

useGLTF.preload('/github.glb')
