/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\hut3.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hut3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SketchUp.geometry} material={materials.material} scale={0.03}>
        <group position={[-60, 0, 60]}>
          <mesh geometry={nodes.ID4.geometry} material={materials.Color_M02} />
          <mesh geometry={nodes.ID4_1.geometry} material={materials.Translucent_Glass_Blue} />
        </group>
        <group position={[-60, 0, 60]}>
          <mesh geometry={nodes.ID14.geometry} material={materials.Translucent_Glass_Blue} />
          <mesh geometry={nodes.ID14_1.geometry} material={materials.Color_I02} />
        </group>
        <group position={[-60, 0, 60]}>
          <mesh geometry={nodes.ID22.geometry} material={materials.Color_M02} />
          <mesh geometry={nodes.ID22_1.geometry} material={materials.Translucent_Glass_Blue} />
        </group>
        <mesh geometry={nodes.group_1.geometry} material={materials.Wood_Veneer_02} position={[54, 0, -54]} />
        <mesh geometry={nodes.group_10.geometry} material={materials.material} position={[-61, 22.55, -27.22]} />
        <mesh geometry={nodes.group_11.geometry} material={materials.material} position={[-61, 15.73, 20.05]} />
        <mesh geometry={nodes.group_12.geometry} material={materials.material} position={[-61, 10.44, -55]} />
        <mesh geometry={nodes.group_13.geometry} material={materials.Color_C06} position={[-37.38, 120, 48]} />
        <group position={[-37.38, 120, 48]}>
          <mesh geometry={nodes.ID178.geometry} material={materials.Color_C06} />
          <mesh geometry={nodes.ID178_1.geometry} material={materials.Wood_Veneer_02_0} />
        </group>
        <mesh geometry={nodes.group_13002.geometry} material={materials.Color_C06} position={[-37.38, 120, 48]} />
        <mesh geometry={nodes.group_13003.geometry} material={materials.Color_C06} position={[-37.38, 120, 48]} />
        <group position={[-37.38, 120, 48]}>
          <mesh geometry={nodes.ID203.geometry} material={materials.Wood_Veneer_02_0} />
          <mesh geometry={nodes.ID203_1.geometry} material={materials.Metal_Silver} />
        </group>
        <group position={[-37.38, 120, 48]}>
          <mesh geometry={nodes.ID216.geometry} material={materials.Color_C06} />
          <mesh geometry={nodes.ID216_1.geometry} material={materials.Metal_Silver} />
        </group>
        <group position={[-37.38, 120, 48]}>
          <mesh geometry={nodes.ID224.geometry} material={materials.Color_C06} />
          <mesh geometry={nodes.ID224_1.geometry} material={materials.Metal_Silver} />
        </group>
        <group position={[-37.38, 120, 48]}>
          <mesh geometry={nodes.ID232.geometry} material={materials.Color_C06} />
          <mesh geometry={nodes.ID232_1.geometry} material={materials.Metal_Silver} />
        </group>
        <mesh geometry={nodes.group_14.geometry} material={materials.material} position={[-56.93, 120, -52.25]} />
        <group position={[-54, 0, -42]}>
          <mesh geometry={nodes.ID61.geometry} material={materials.Color_M02} />
          <mesh geometry={nodes.ID61_1.geometry} material={materials.Stone_Marble} />
        </group>
        <group position={[-54, 0, -42]}>
          <mesh geometry={nodes.ID74.geometry} material={materials.Stone_Marble} />
          <mesh geometry={nodes.ID74_1.geometry} material={materials.Color_M05} />
        </group>
        <group position={[-53.5, 24, -42]}>
          <mesh geometry={nodes.ID85.geometry} material={materials.Stone_Marble} />
          <mesh geometry={nodes.ID85_1.geometry} material={materials.Color_M05} />
        </group>
        <mesh geometry={nodes.group_4.geometry} material={materials.Metal_Steel_Textured_White} position={[-66, 90, 48]} />
        <mesh geometry={nodes.group_5.geometry} material={materials.Metal_Steel_Textured_White} position={[-66, 90, 12]} />
        <mesh geometry={nodes.group_6.geometry} material={materials.Metal_Steel_Textured_White} position={[30, 6, 66]} />
        <mesh geometry={nodes.group_7.geometry} material={materials.material} position={[-61, 107.35, -55]} />
        <mesh geometry={nodes.group_8.geometry} material={materials.material} position={[-61, 66.16, -37.94]} />
        <mesh geometry={nodes.group_9.geometry} material={materials.material} position={[-61, 46.84, 2.32]} />
        <mesh geometry={nodes.instance_0.geometry} material={materials.Chris_Shirt} position={[-41.5, 0, 46]} rotation={[-Math.PI, 0.05, -Math.PI]} />
        <mesh geometry={nodes.instance_0001.geometry} material={materials.Chris_Shirt} position={[-41.5, 0, 46]} rotation={[-Math.PI, 0.05, -Math.PI]} />
        <mesh geometry={nodes.instance_0002.geometry} material={materials.Chris_Shoe} position={[-41.5, 0, 46]} rotation={[-Math.PI, 0.05, -Math.PI]} />
        <mesh geometry={nodes.instance_0003.geometry} material={materials.Chris_Shirt} position={[-41.5, 0, 46]} rotation={[-Math.PI, 0.05, -Math.PI]} />
        <mesh geometry={nodes.instance_0004.geometry} material={materials.Chris_Skin} position={[-41.5, 0, 46]} rotation={[-Math.PI, 0.05, -Math.PI]} />
        <mesh geometry={nodes.instance_0005.geometry} material={materials.Chris_Shoe_Sole} position={[-41.5, 0, 46]} rotation={[-Math.PI, 0.05, -Math.PI]} />
        <mesh geometry={nodes.instance_0006.geometry} material={materials.Chris_Shoe_Sole} position={[-41.5, 0, 46]} rotation={[-Math.PI, 0.05, -Math.PI]} />
        <mesh geometry={nodes.instance_0007.geometry} material={materials.Chris_Skin} position={[-41.5, 0, 46]} rotation={[-Math.PI, 0.05, -Math.PI]} />
        <mesh geometry={nodes.instance_0008.geometry} material={materials.Chris_Hair} position={[-41.5, 0, 46]} rotation={[-Math.PI, 0.05, -Math.PI]} />
        <mesh geometry={nodes.instance_0009.geometry} material={materials.Chris_Shoe_Sole} position={[-41.5, 0, 46]} rotation={[-Math.PI, 0.05, -Math.PI]} />
        <mesh geometry={nodes.instance_0010.geometry} material={materials.Chris_Hair} position={[-41.5, 0, 46]} rotation={[-Math.PI, 0.05, -Math.PI]} />
        <mesh geometry={nodes.instance_0011.geometry} material={materials.Chris_Skin} position={[-41.5, 0, 46]} rotation={[-Math.PI, 0.05, -Math.PI]} />
        <mesh geometry={nodes.instance_0012.geometry} material={materials.Chris_Shoe} position={[-41.5, 0, 46]} rotation={[-Math.PI, 0.05, -Math.PI]} />
        <mesh geometry={nodes.instance_0013.geometry} material={materials.Chris_Pants} position={[-41.5, 0, 46]} rotation={[-Math.PI, 0.05, -Math.PI]} />
        <mesh geometry={nodes.instance_0014.geometry} material={materials.Chris_Skin} position={[-41.5, 0, 46]} rotation={[-Math.PI, 0.05, -Math.PI]} />
      </mesh>
      <mesh geometry={nodes.SketchUp001.geometry} material={materials.material} scale={0.03} />
    </group>
  )
}

useGLTF.preload('/hut3.glb')
