/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\hut4.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hut4.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SketchUp.geometry} material={materials['material.001']} scale={0.03}>
        <group position={[21.05, 39.53, 54]}>
          <mesh geometry={nodes.group_22.geometry} material={materials.Color_M08} />
          <mesh geometry={nodes.group_22001.geometry} material={materials.Color_M08} />
          <mesh geometry={nodes.group_23.geometry} material={materials.Color_M00} position={[1, 1, -1]} />
        </group>
        <group position={[125.86, 0, -106.45]}>
          <mesh geometry={nodes.group_26.geometry} material={materials['Wood_Veneer_02.001']} />
          <group position={[0, 84, 0]}>
            <mesh geometry={nodes.ID356.geometry} material={materials.Translucent_Glass_Gold} />
            <mesh geometry={nodes.ID356_1.geometry} material={materials.Translucent_Glass_Gray} />
          </group>
        </group>
        <group position={[-60, 0, 60]}>
          <mesh geometry={nodes.ID4001.geometry} material={materials['Color_M02.001']} />
          <mesh geometry={nodes.ID4001_1.geometry} material={materials['Translucent_Glass_Blue.001']} />
        </group>
        <group position={[-60, 0, 60]}>
          <mesh geometry={nodes.ID14001.geometry} material={materials['Translucent_Glass_Blue.001']} />
          <mesh geometry={nodes.ID14001_1.geometry} material={materials['Color_I02.001']} />
        </group>
        <group position={[-60, 0, 60]}>
          <mesh geometry={nodes.ID22001.geometry} material={materials['Color_M02.001']} />
          <mesh geometry={nodes.ID22001_1.geometry} material={materials['Translucent_Glass_Blue.001']} />
        </group>
        <mesh geometry={nodes.group_1.geometry} material={materials['Wood_Veneer_02.001']} position={[54, 0, -54]} />
        <mesh geometry={nodes.group_10.geometry} material={materials.Color_A04} position={[-61, 46.84, 2.32]} />
        <mesh geometry={nodes.group_11.geometry} material={materials.Color_A04} position={[-61, 22.55, -27.22]} />
        <mesh geometry={nodes.group_12.geometry} material={materials.Color_A04} position={[-61, 15.73, 20.05]} />
        <mesh geometry={nodes.group_13.geometry} material={materials.Color_A04} position={[-61, 10.44, -55]} />
        <mesh geometry={nodes.group_14.geometry} material={materials['Color_C06.001']} position={[-49.56, 120, 48]} scale={[1, 0.6, 1]} />
        <group position={[-49.56, 120, 48]} scale={[1, 0.6, 1]}>
          <mesh geometry={nodes.ID181.geometry} material={materials['Color_C06.001']} />
          <mesh geometry={nodes.ID181_1.geometry} material={materials['Wood_Veneer_02_0.001']} />
        </group>
        <mesh geometry={nodes.group_14002.geometry} material={materials['Color_C06.001']} position={[-49.56, 120, 48]} scale={[1, 0.6, 1]} />
        <mesh geometry={nodes.group_14003.geometry} material={materials['Color_C06.001']} position={[-49.56, 120, 48]} scale={[1, 0.6, 1]} />
        <group position={[-49.56, 120, 48]} scale={[1, 0.6, 1]}>
          <mesh geometry={nodes.ID206.geometry} material={materials['Wood_Veneer_02_0.001']} />
          <mesh geometry={nodes.ID206_1.geometry} material={materials['Metal_Silver.001']} />
        </group>
        <group position={[-49.56, 120, 48]} scale={[1, 0.6, 1]}>
          <mesh geometry={nodes.ID219.geometry} material={materials['Color_C06.001']} />
          <mesh geometry={nodes.ID219_1.geometry} material={materials['Metal_Silver.001']} />
        </group>
        <group position={[-49.56, 120, 48]} scale={[1, 0.6, 1]}>
          <mesh geometry={nodes.ID227.geometry} material={materials['Color_C06.001']} />
          <mesh geometry={nodes.ID227_1.geometry} material={materials['Metal_Silver.001']} />
        </group>
        <group position={[-49.56, 120, 48]} scale={[1, 0.6, 1]}>
          <mesh geometry={nodes.ID235.geometry} material={materials['Color_C06.001']} />
          <mesh geometry={nodes.ID235_1.geometry} material={materials['Metal_Silver.001']} />
        </group>
        <mesh geometry={nodes.group_15.geometry} material={materials['material.001']} position={[-56.93, 120, -52.25]} />
        <mesh geometry={nodes.group_16.geometry} material={materials.Color_D01} position={[54.42, 67.79, -60]} />
        <mesh geometry={nodes.group_17.geometry} material={materials.Color_M03} position={[56.94, 73.93, -60.1]} />
        <mesh geometry={nodes.group_17001.geometry} material={materials.Color_M03} position={[56.94, 73.93, -60.1]} />
        <mesh geometry={nodes.group_18.geometry} material={materials['material.001']} position={[-54, 82, -58]} />
        <mesh geometry={nodes.group_19.geometry} material={materials['Color_M02.001']} position={[16, 0, 53]} />
        <mesh geometry={nodes.group_2.geometry} material={materials.Color_C04} position={[-54, 0, -42]}>
          <group position={[24.5, 24.5, -35]}>
            <mesh geometry={nodes.ID62.geometry} material={materials['Color_M02.001']} />
            <mesh geometry={nodes.ID62_1.geometry} material={materials.Color_C04} />
          </group>
        </mesh>
        <mesh geometry={nodes.group_2001.geometry} material={materials.Color_C04} position={[-54, 0, -42]} />
        <mesh geometry={nodes.group_20.geometry} material={materials['material.001']} position={[-54, 47.69, 11.11]} />
        <mesh geometry={nodes.group_24.geometry} material={materials['material.001']} position={[58, 82.03, 54]} />
        <mesh geometry={nodes.group_28.geometry} material={materials['material.001']} position={[56, 0, 54]} />
        <mesh geometry={nodes.group_29.geometry} material={materials.Color_H03} position={[57, 0, 51]} />
        <mesh geometry={nodes.group_30.geometry} material={materials.Color_H03} position={[57, 0, 19]} />
        <mesh geometry={nodes.group_31.geometry} material={materials.Color_H03} position={[57, 0, -13.94]} />
        <mesh geometry={nodes.group_32.geometry} material={materials['material.001']} position={[55, 0, 21.92]} />
        <mesh geometry={nodes.group_33.geometry} material={materials.Color_H03} position={[55, 0, -21.63]} />
        <mesh geometry={nodes.group_34.geometry} material={materials.Color_C08} position={[44.7, 18, -80.4]} rotation={[0, -0.14, Math.PI]} />
        <mesh geometry={nodes.group_35.geometry} material={materials.Color_C08} position={[20.56, 18, -78.52]} rotation={[0, 0.08, Math.PI]} />
        <mesh geometry={nodes.group_36.geometry} material={materials.Color_C08} position={[-8.93, 18, -77.52]} rotation={[0, -0.14, Math.PI]} />
        <group position={[-53.5, 24, -42]}>
          <mesh geometry={nodes.ID83.geometry} material={materials.Color_C04} />
          <mesh geometry={nodes.ID83_1.geometry} material={materials['Stone_Marble.001']} />
        </group>
        <mesh geometry={nodes.group_5.geometry} material={materials['Metal_Steel_Textured_White.001']} position={[-66, 90, 48]} />
        <mesh geometry={nodes.group_6.geometry} material={materials['Metal_Steel_Textured_White.001']} position={[-66, 90, 12]} />
        <mesh geometry={nodes.group_7.geometry} material={materials['Metal_Steel_Textured_White.001']} position={[30, 6, 66]} />
        <mesh geometry={nodes.group_8.geometry} material={materials.Color_A04} position={[-61, 107.35, -55]} />
        <mesh geometry={nodes.group_9.geometry} material={materials.Color_A04} position={[-61, 66.16, -37.94]} />
        <mesh geometry={nodes.instance_0.geometry} material={materials['Chris_Shirt.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.71, -Math.PI]} />
        <mesh geometry={nodes.instance_0001.geometry} material={materials['Chris_Shirt.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.71, -Math.PI]} />
        <mesh geometry={nodes.instance_0002.geometry} material={materials['Chris_Shoe.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.71, -Math.PI]} />
        <mesh geometry={nodes.instance_0003.geometry} material={materials['Chris_Shirt.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.71, -Math.PI]} />
        <mesh geometry={nodes.instance_0004.geometry} material={materials['Chris_Skin.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.71, -Math.PI]} />
        <mesh geometry={nodes.instance_0005.geometry} material={materials['Chris_Shoe_Sole.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.71, -Math.PI]} />
        <mesh geometry={nodes.instance_0006.geometry} material={materials['Chris_Shoe_Sole.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.71, -Math.PI]} />
        <mesh geometry={nodes.instance_0007.geometry} material={materials['Chris_Skin.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.71, -Math.PI]} />
        <mesh geometry={nodes.instance_0008.geometry} material={materials['Chris_Hair.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.71, -Math.PI]} />
        <mesh geometry={nodes.instance_0009.geometry} material={materials['Chris_Shoe_Sole.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.71, -Math.PI]} />
        <mesh geometry={nodes.instance_0010.geometry} material={materials['Chris_Hair.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.71, -Math.PI]} />
        <mesh geometry={nodes.instance_0011.geometry} material={materials['Chris_Skin.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.71, -Math.PI]} />
        <mesh geometry={nodes.instance_0012.geometry} material={materials['Chris_Shoe.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.71, -Math.PI]} />
        <mesh geometry={nodes.instance_0013.geometry} material={materials['Chris_Pants.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.71, -Math.PI]} />
        <mesh geometry={nodes.instance_0014.geometry} material={materials['Chris_Skin.001']} position={[-23.44, 0, 27.63]} rotation={[-Math.PI, 0.71, -Math.PI]} />
        <mesh geometry={nodes.instance_1.geometry} material={materials['material.001']} position={[60, 90, -21.47]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.instance_1001.geometry} material={materials['material.001']} position={[60, 90, -21.47]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.instance_1002.geometry} material={materials['material.001']} position={[60, 90, -21.47]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.instance_1003.geometry} material={materials['material.001']} position={[60, 90, -21.47]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.instance_2.geometry} material={materials['material.001']} position={[58.56, 90.08, -60]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh geometry={nodes.instance_2001.geometry} material={materials['material.001']} position={[58.56, 90.08, -60]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh geometry={nodes.instance_2002.geometry} material={materials['material.001']} position={[58.56, 90.08, -60]} rotation={[Math.PI / 2, 0, Math.PI]} />
      </mesh>
      <mesh geometry={nodes.SketchUp001.geometry} material={materials['material.001']} scale={0.03} />
      <mesh geometry={nodes.Casing.geometry} material={materials['default']} position={[-0.37, 0.71, -1.47]} rotation={[Math.PI / 2, 0, -2.29]} scale={0.1} />
      <mesh geometry={nodes.DialFace.geometry} material={materials['default']} position={[-0.37, 0.71, -1.47]} rotation={[Math.PI / 2, 0, -2.29]} scale={0.1} />
      <mesh geometry={nodes.DialMarker.geometry} material={materials['default']} position={[-0.37, 0.71, -1.47]} rotation={[Math.PI / 2, 0, -2.29]} scale={0.1} />
      <mesh geometry={nodes.Glass.geometry} material={materials['default']} position={[-0.37, 0.71, -1.47]} rotation={[Math.PI / 2, 0, -2.29]} scale={0.1} />
      <mesh geometry={nodes.Speaker.geometry} material={materials['default']} position={[-0.37, 0.71, -1.47]} rotation={[Math.PI / 2, 0, -2.29]} scale={0.1} />
      <mesh geometry={nodes.Tunner.geometry} material={materials['default']} position={[-0.37, 0.71, -1.47]} rotation={[Math.PI / 2, 0, -2.29]} scale={0.1} />
      <mesh geometry={nodes.Volume.geometry} material={materials['default']} position={[-0.37, 0.71, -1.47]} rotation={[Math.PI / 2, 0, -2.29]} scale={0.1} />
      <mesh geometry={nodes.Selector.geometry} material={materials['default']} position={[-0.37, 0.71, -1.47]} rotation={[Math.PI / 2, 0, -2.29]} scale={0.1} />
    </group>
  )
}

useGLTF.preload('/hut4.glb')
