/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\logos\\js.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/js.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[-0.01, 0, 0.03]} rotation={[-0.36, 1.53, 0.35]} scale={[0.84, 1, 1]} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.002']} position={[0, -0.05, 0]} rotation={[1.57, 0.01, -3.11]} scale={0.1} />
    </group>
  )
}

useGLTF.preload('/js.glb')
