/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\maxtower_03.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/maxtower_03.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.03}>
        <group position={[-28.76, 6, 132.94]}>
          <group position={[16.76, 0, -8.94]}>
            <group position={[6, 116, -10]} rotation={[0, 0, Math.PI]}>
              <mesh geometry={nodes.group_4.geometry} material={materials.noon_2} />
              <mesh geometry={nodes.group_4001.geometry} material={materials.noon_2} />
              <mesh geometry={nodes.group_4002.geometry} material={materials.noon_2} />
              <mesh geometry={nodes.group_4003.geometry} material={materials.noon_2} />
              <mesh geometry={nodes.group_5.geometry} material={materials.Translucent_Glass_Blue} position={[0, 110, -4]} rotation={[0, 0, -Math.PI]} />
              <mesh geometry={nodes.group_5001.geometry} material={materials.Translucent_Glass_Blue} position={[0, 110, -4]} rotation={[0, 0, -Math.PI]} />
              <mesh geometry={nodes.group_5002.geometry} material={materials.Translucent_Glass_Blue} position={[0, 110, -4]} rotation={[0, 0, -Math.PI]} />
              <mesh geometry={nodes.group_5003.geometry} material={materials.Translucent_Glass_Blue} position={[0, 110, -4]} rotation={[0, 0, -Math.PI]} />
              <mesh geometry={nodes.group_5004.geometry} material={materials.Translucent_Glass_Blue} position={[0, 110, -4]} rotation={[0, 0, -Math.PI]} />
              <mesh geometry={nodes.group_5005.geometry} material={materials.Translucent_Glass_Blue} position={[0, 110, -4]} rotation={[0, 0, -Math.PI]} />
              <mesh geometry={nodes.group_5006.geometry} material={materials.Translucent_Glass_Blue} position={[0, 110, -4]} rotation={[0, 0, -Math.PI]} />
            </group>
            <mesh geometry={nodes.group_2.geometry} material={materials.noon_2} />
          </group>
          <group position={[-1.84, 0, 0]}>
            <group position={[1.92, 32.99, 0]}>
              <mesh geometry={nodes.group_10.geometry} material={materials.Color_M08} position={[0, 0, -17]} rotation={[Math.PI / 2, 0, 0]} scale={[1.74, 1, 1.31]} />
              <group position={[0, 0, -17]} rotation={[Math.PI / 2, 0, 0]} scale={[1.74, 1, 1.31]}>
                <mesh geometry={nodes.ID126.geometry} material={materials.Color_M08} />
                <mesh geometry={nodes.ID126_1.geometry} material={materials.Color_M07} />
              </group>
              <mesh geometry={nodes.group_10002.geometry} material={materials.Color_M08} position={[0, 0, -17]} rotation={[Math.PI / 2, 0, 0]} scale={[1.74, 1, 1.31]} />
              <group position={[0, 0, -17]} rotation={[Math.PI / 2, 0, 0]} scale={[1.74, 1, 1.31]}>
                <mesh geometry={nodes.ID140.geometry} material={materials.Color_M08} />
                <mesh geometry={nodes.ID140_1.geometry} material={materials.Color_M07} />
              </group>
              <mesh geometry={nodes.group_10004.geometry} material={materials.Color_M08} position={[0, 0, -17]} rotation={[Math.PI / 2, 0, 0]} scale={[1.74, 1, 1.31]} />
              <mesh geometry={nodes.group_9.geometry} material={materials.noon_5} position={[6.96, 1.3, -1]} />
            </group>
            <mesh geometry={nodes.group_7.geometry} material={materials.material} position={[7.4, 0, -17]} rotation={[0, 1.57, 0]} />
            <mesh geometry={nodes.group_7001.geometry} material={materials.material} position={[7.4, 0, -17]} rotation={[0, 1.57, 0]} />
            <mesh geometry={nodes.group_7002.geometry} material={materials.material} position={[7.4, 0, -17]} rotation={[0, 1.57, 0]} />
          </group>
          <mesh geometry={nodes.instance_0.geometry} material={materials.noon_5} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.instance_0001.geometry} material={materials.noon_5} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.instance_0002.geometry} material={materials.noon_5} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.instance_0003.geometry} material={materials.noon_5} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.instance_0004.geometry} material={materials.noon_5} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.instance_0005.geometry} material={materials.noon_5} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.instance_0006.geometry} material={materials.noon_5} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.instance_0007.geometry} material={materials.noon_5} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.instance_0008.geometry} material={materials.noon_5} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.instance_0009.geometry} material={materials.noon_5} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.instance_0010.geometry} material={materials.noon_5} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.instance_0011.geometry} material={materials.noon_5} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.instance_0012.geometry} material={materials.noon_5} position={[38.07, 9.89, -65.75]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
        <mesh geometry={nodes.group_11.geometry} material={materials.Grass_Dark_Green} position={[-120, 3, 120]} />
        <group position={[-120, 0, 120]}>
          <mesh geometry={nodes.ID247.geometry} material={materials.Groundcover_Wood_Mix} />
          <mesh geometry={nodes.ID247_1.geometry} material={materials.Vegetation_Bark_Ponderosa} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/maxtower_03.glb')
