/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\maxtower_01_interactive.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/maxtower_01_interactive.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.03}>
        <group position={[-16.64, 276.07, -19.74]} rotation={[0, 0, -2.99]} scale={1.66}>
          <mesh geometry={nodes.group_7.geometry} material={materials['Chris_Shoe_Sole.001']} position={[0, 0.25, 0]} />
          <group position={[0, 0.25, 0]}>
            <mesh geometry={nodes.ID71.geometry} material={materials['Chris_Shoe_Sole.001']} />
            <mesh geometry={nodes.ID71_1.geometry} material={materials['Color_M06.004']} />
          </group>
          <mesh geometry={nodes.group_7002.geometry} material={materials['Chris_Shoe_Sole.001']} position={[0, 0.25, 0]} />
          <mesh geometry={nodes.group_7003.geometry} material={materials['Chris_Shoe_Sole.001']} position={[0, 0.25, 0]} />
          <mesh geometry={nodes.group_7004.geometry} material={materials['Chris_Shoe_Sole.001']} position={[0, 0.25, 0]} />
          <mesh geometry={nodes.group_7005.geometry} material={materials['Chris_Shoe_Sole.001']} position={[0, 0.25, 0]} />
        </group>
        <mesh geometry={nodes.group_0.geometry} material={materials['Color_M09.003']} position={[-30.11, 246.5, -7.76]}>
          <group position={[6.1, 26.81, -11.98]}>
            <mesh geometry={nodes.group_2.geometry} material={materials['Color_M07.001']} position={[1.97, 1.54, -19.27]} scale={1.66} />
            <mesh geometry={nodes.group_3.geometry} material={materials['Color_G06.001']} position={[1.93, 1.54, -7.83]} scale={1.66} />
            <mesh geometry={nodes.group_4.geometry} material={materials['Color_A05.001']} position={[1.93, 1.54, -13.51]} scale={1.66} />
            <mesh geometry={nodes.group_5.geometry} material={materials['Color_I04.001']} position={[1.93, 1.54, -2.11]} scale={1.66} />
          </group>
        </mesh>
        <mesh geometry={nodes.group_0001.geometry} material={materials['Color_M09.003']} position={[-30.11, 246.5, -7.76]} />
        <mesh geometry={nodes.group_0002.geometry} material={materials['Color_M09.003']} position={[-30.11, 246.5, -7.76]} />
      </group>
    </group>
  )
}

useGLTF.preload('/maxtower_01_interactive.glb')
